    db 19        ; wTilemap_Width
    dw $010A     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/pathwayisland_rescueroom/Cald_Vents_PathwayIsland_RescueRoom.collision.tilemap.rle"