    db 36        ;wTilemap_Width
    dw $0240     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/coral/tunnelschute/Orothe_Coral_TunnelsChute.collision.tilemap.rle"