    db 30        ;wTilemap_Width
    dw $01E0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/dock/eastern_ferry/Orothe_Dock_Eastern_Ferry.collision.tilemap.rle"