    db 60        ;wTilemap_Width
    dw $0E10     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/seers/house/Naroom_Seers_House.collision.tilemap.rle"