    db 10        ; wTilemap_Width
    dw $0064     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/bogrom/historianroom/Underneath_Bogrom_HistorianRoom.collision.tilemap.rle"