    db 10        ; wTilemap_Width
    dw $005A     ; wTilemap_YMapPad
    db 255       ;
    db 0         ; wTilemap_VStop
    dw $0064     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/bogrom/historianroom/Underneath_Bogrom_HistorianRoom.metatile.tilemap.rle"