    db 60        ; wTilemap_Width
    dw $0960     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/pathwaya/Cald_Vents_PathwayA.collision.tilemap.rle"