    db 48        ;wTilemap_Width
    dw $01B0     ;wTilemap_YMapPad
    db 37        ;
    db 38        ;wTilemap_VStop
    dw $0900     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/geyser/middle/Orothe_Geyser_Middle.metatile.tilemap.rle"