    db 20        ; wTilemap_Width
    dw $00B4     ; wTilemap_YMapPad
    db 9         ;
    db 20        ; wTilemap_VStop
    dw $0258     ; Uncompressed file size (excluding header)
    ; The imported file size was actually $025F because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/orothe/mar/mobisroom/Orothe_Mar_MobisRoom.metatile.tilemap.rle"