    db 20        ;wTilemap_Width
    dw $0258     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/mar/mobisroom/Orothe_Mar_MobisRoom.collision.tilemap.rle"