    db 22        ; wTilemap_Width
    dw $0370     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/pathwaymarunderwater/Orothe_Tunnels_PathwayMarUnderwater.collision.tilemap.rle"