    db 30        ; wTilemap_Width
    dw $010E     ; wTilemap_YMapPad
    db 19        ;
    db 40        ; wTilemap_VStop
    dw $05DC     ; Uncompressed file size (excluding header)
    ; The imported file size was actually $05E3 because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/underneath/geyser/southentrance/Underneath_Geyser_SouthEntrance.metatile.tilemap.rle"