    db 11        ; wTilemap_Width
    dw $0134     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/southwest_pipesroom_pathway/Naroom_Vash_Southwest_PipesRoom_Pathway.collision.tilemap.rle"