    db 11        ;wTilemap_Width
    dw $0063     ;wTilemap_YMapPad
    db 0         ;
    db 18        ;wTilemap_VStop
    dw $0134     ;Uncompressed file size (excluding header)
    ;The imported file size was actually $013B because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/southwest_pipesroom_pathway/Naroom_Vash_Southwest_PipesRoom_Pathway.metatile.tilemap.rle"