    db 16        ;wTilemap_Width
    dw $0200     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/geyser/south/Orothe_Geyser_South.collision.tilemap.rle"