DEF Status_PLAGUE EQU $01
DEF Status_STONE EQU $02
DEF Status_HICCUPS EQU $04
DEF Status_ERUPT EQU $08
DEF Status_HIDDEN EQU $10
DEF Status_MIRROR EQU $20
DEF Status_CONFUSED EQU $40
DEF Status_DIVERT EQU $80


DEF elementNone         EQU $00
DEF elementEarth        EQU $01     ;Strong vs Arderial. Weak vs Orothe
DEF elementFire         EQU $02     ;Strong vs Orothe. Weak vs Arderial
DEF elementWind         EQU $04     ;Strong vs Cald. Weak vs Underneath
DEF elementWater        EQU $08     ;Strong vs Underneath. Weak vs Cald
DEF elementGrass        EQU $10     ;Strong vs Core
DEF elementShadow       EQU $20     ;Strong vs Naroom
DEF elementElectrical   EQU $40     ;No interactions
DEF elementUNUSED       EQU $80     ;Unused

DEF Battle_Actor_Effect_SPARKLE EQU 1

RSRESET
DEF BATTLE_SLOT_HERO RB 1
DEF BATTLE_SLOT_ALLY0 RB 1
DEF BATTLE_SLOT_ALLY1 RB 1
DEF BATTLE_SLOT_ALLY2 RB 1
DEF BATTLE_SLOT_ALLY3 RB 1
DEF BATTLE_SLOT_ENEMY0 RB 1
DEF BATTLE_SLOT_ENEMY1 RB 1
DEF BATTLE_SLOT_ENEMY2 RB 1
DEF BATTLE_SLOT_ENEMY3 RB 1
DEF BATTLE_SLOT_MAGI RB 1

; TODO - change to RB (don't need to RSRESET!)

; The list starts at $0A to avoid confusion with 0-9 which refer to the hero, 8 cards and enemy magi respectively
DEF Battle_TARGET_START EQU $0A ; start of the list

DEF Battle_TARGET_ME EQU $0A
DEF Battle_TARGET_NONE EQU $0B
DEF Battle_TARGET_ALLYEMPTY EQU $0C
DEF Battle_TARGET_ENEMYEMPTY EQU $0D
DEF Battle_TARGET_ANYCREATURE EQU $0E
DEF Battle_TARGET_ALLYMAGI EQU $0F
DEF Battle_TARGET_ENEMYMAGI EQU $10
DEF Battle_TARGET_ENEMYMAGI_EVASION EQU $11
DEF Battle_TARGET_ANY EQU $12
DEF Battle_TARGET_ANY_EVASION EQU $13
; All target modes below target multiple creatures / don't have a single defined target
DEF Battle_TARGET_MANY_START EQU $14 ; start of the list

DEF Battle_TARGET_ALLENEMY EQU $14
DEF Battle_TARGET_ALLENEMY_MAGI EQU $15
DEF Battle_TARGET_ALLALLY EQU $16
DEF Battle_TARGET_ALLALLY_ME EQU $17
DEF Battle_TARGET_ALLALLY_MAGI EQU $18
DEF Battle_TARGET_ALLALLY_MAGI_ME EQU $19
DEF Battle_TARGET_ALL EQU $1A
DEF Battle_TARGET_ALL_ME EQU $1B
DEF Battle_TARGET_ALL_MAGI EQU $1C
DEF Battle_TARGET_ALL_MAGI_ME EQU $1D
DEF Battle_TARGET_DEPENDANT EQU $1E


DEF BATTLE_ACTOR_TONY EQU $0B
DEF BATTLE_ACTOR_MAGI EQU $0C

;wBattle_ExitCode
RSRESET
DEF BATTLE_EXITCODE_NOEXIT RB 1 ; Must be zero
DEF BATTLE_EXITCODE_RUN RB 1
DEF BATTLE_EXITCODE_WIN RB 1
DEF BATTLE_EXITCODE_LOSE RB 1
DEF BATTLE_EXITCODE_TODO RB 1 ;todo ???

;.Rating
; BATTLE ATTACK0 -4
DEF BATTLE_RATING_HEAL EQU $05
;HEAL 1-4
;NONE


; Battle Script AI targets


; Menu options for Tony/Creature
DEF BATTLE_MENU_TILEMAP_CARD EQU WINDOW_COORD_00_00
DEF BATTLE_MENU_TILEMAP_CARD_ATTR EQU $07
DEF BATTLE_MENU_TILEMAP_CMD0NAME EQU WINDOW_COORD_00_05
DEF BATTLE_MENU_TILEMAP_CMD1NAME EQU WINDOW_COORD_01_05
DEF BATTLE_MENU_TILEMAP_CMD2NAME EQU WINDOW_COORD_02_05
DEF BATTLE_MENU_TILEMAP_CMD3NAME EQU WINDOW_COORD_03_05
DEF BATTLE_MENU_TILEMAP_CMD4NAME EQU WINDOW_COORD_04_05
DEF BATTLE_MENU_TILEMAP_DEFEND EQU WINDOW_COORD_05_05
DEF BATTLE_MENU_TILEMAP_ENERGY EQU WINDOW_COORD_00_0D
DEF BATTLE_MENU_TILEMAP_CMD1COST EQU WINDOW_COORD_01_0F
DEF BATTLE_MENU_TILEMAP_CMD2COST EQU WINDOW_COORD_02_0F
DEF BATTLE_MENU_TILEMAP_CMD3COST EQU WINDOW_COORD_03_0F
DEF BATTLE_MENU_TILEMAP_CMD4COST EQU WINDOW_COORD_04_0F
    ; Bank 0
    VRAM_TILEID_SPRITE
    ; 
    VRAM_TILEID_BG
    ; Tiles $00 - $7F defined in cardscene_equ.asm
    ; Bank 1
    VRAM_TILEID_SPRITE
    ; vTonySpritesChars
    ; Tiles $40 - $7F are undefined
    VRAM_TILEID_BG
    ; Tiles $80 - $85 defined in textbox
    VRAM_TILEID BATTLE_MENU, CMDNAME0, $86
    VRAM_TILEID BATTLE_MENU, CMDNAME1, $8D
    VRAM_TILEID BATTLE_MENU, CMDNAME2, $94
    VRAM_TILEID BATTLE_MENU, CMDNAME3, $9B
    VRAM_TILEID BATTLE_MENU, CMDNAME4, $A2
    VRAM_TILEID BATTLE_MENU, ENERGY, $A9
    VRAM_TILEID BATTLE_MENU, CMDCOST1, $B0
    VRAM_TILEID BATTLE_MENU, CMDCOST2, $B3
    VRAM_TILEID BATTLE_MENU, CMDCOST3, $B6
    VRAM_TILEID BATTLE_MENU, CMDCOST4, $B9
    ; 
    ; Tiles $C7 - $05 are undefined
    VRAM_TILEID BATTLE_MENU, DEFEND, $06
    VRAM_TILEID BATTLE_MENU, RIGHTARROW, $0C
    VRAM_TILEID BATTLE_MENU, DOWNARROW, $0D
    ; Tiles $0E - $2F are undefined
    ; Tiles $30 - $7F are defined in cardscene_equ.asm


; Menu options for Summon Menu
DEF BATTLE_MENU_TILEMAP_SUMMONNAME0 EQU WINDOW_COORD_00_03
DEF BATTLE_MENU_TILEMAP_SUMMONNAME1 EQU WINDOW_COORD_01_03
DEF BATTLE_MENU_TILEMAP_SUMMONNAME2 EQU WINDOW_COORD_02_03
DEF BATTLE_MENU_TILEMAP_SUMMONNAME3 EQU WINDOW_COORD_03_03
DEF BATTLE_MENU_TILEMAP_SUMMONNAME4 EQU WINDOW_COORD_04_03
DEF BATTLE_MENU_TILEMAP_SUMMONCOST0 EQU WINDOW_COORD_00_0F
DEF BATTLE_MENU_TILEMAP_SUMMONCOST1 EQU WINDOW_COORD_01_0F
DEF BATTLE_MENU_TILEMAP_SUMMONCOST2 EQU WINDOW_COORD_02_0F
DEF BATTLE_MENU_TILEMAP_SUMMONCOST3 EQU WINDOW_COORD_03_0F
DEF BATTLE_MENU_TILEMAP_SUMMONCOST4 EQU WINDOW_COORD_04_0F
    ; Bank 1
    VRAM_TILEID_SPRITE
    ; vTonySpritesChars
    ; Tiles $40 - $7F are undefined
    VRAM_TILEID_BG
    ; Tiles $80 - $85 defined in textbox
    VRAM_TILEID BATTLE_MENU, SUMMONNAME0, $86
    VRAM_TILEID BATTLE_MENU, SUMMONNAME1, $90
    VRAM_TILEID BATTLE_MENU, SUMMONNAME2, $9A
    VRAM_TILEID BATTLE_MENU, SUMMONNAME3, $A4
    VRAM_TILEID BATTLE_MENU, SUMMONNAME4, $AE
    VRAM_TILEID BATTLE_MENU, SUMMONCOST0, $B8
    VRAM_TILEID BATTLE_MENU, SUMMONCOST1, $BB
    VRAM_TILEID BATTLE_MENU, SUMMONCOST2, $BE
    VRAM_TILEID BATTLE_MENU, SUMMONCOST3, $C1
    VRAM_TILEID BATTLE_MENU, SUMMONCOST4, $C4
    ; 
    ; Tiles $C7 - $2F are undefined
    ; Tiles $30 - $7F are defined in cardscene_equ.asm



DEF BATTLE_MENU_TILEMAP_PREVIOUS EQU WINDOW_COORD_03_00
DEF BATTLE_MENU_PREVIOUS_ATTR EQU $4F ; Vflip
DEF BATTLE_MENU_TILEMAP_NEXT EQU WINDOW_COORD_03_13