    db 15        ;wTilemap_Width
    dw $0087     ;wTilemap_YMapPad
    db 4         ;
    db 5         ;wTilemap_VStop
    dw $00E1     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/bogrom/genericroom/Underneath_Bogrom_GenericRoom.metatile.tilemap.rle"