    db 15        ;wTilemap_Width
    dw $00E1     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/bogrom/genericroom/Underneath_Bogrom_GenericRoom.collision.tilemap.rle"