    db 50        ; wTilemap_Width
    dw $03E8     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/easttunnel/pathwaytunnels/Underneath_EastTunnel_PathwayTunnels.collision.tilemap.rle"