    db 24        ; wTilemap_Width
    dw $03C0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/palace/doubleroom/Arderial_Palace_DoubleRoom.collision.tilemap.rle"