    db 24        ; wTilemap_Width
    dw $00D8     ; wTilemap_YMapPad
    db 13        ;
    db 30        ; wTilemap_VStop
    dw $03C0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/palace/doubleroom/Arderial_Palace_DoubleRoom.metatile.tilemap.rle"