    db 20        ; wTilemap_Width
    dw $0190     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/deep_wenceroom/Naroom_Forest_Deep_WenceRoom.collision.tilemap.rle"