    db 40        ; wTilemap_Width
    dw $03C0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/smith/backyard_entrance/Core_Smith_Backyard_Entrance.collision.tilemap.rle"