    db 40        ; wTilemap_Width
    dw $0168     ; wTilemap_YMapPad
    db 29        ;
    db 14        ; wTilemap_VStop
    dw $03C0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/smith/backyard_entrance/Core_Smith_Backyard_Entrance.metatile.tilemap.rle"