    db 32        ; wTilemap_Width
    dw $0400     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/entrance/Orothe_Tunnels_Entrance.collision.tilemap.rle"