    db 20        ; wTilemap_Width
    dw $00F0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/southeast/Naroom_Vash_Southeast.collision.tilemap.rle"