    db 26        ; wTilemap_Width
    dw $00EA     ; wTilemap_YMapPad
    db 15        ;
    db 20        ; wTilemap_VStop
    dw $030C     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/labyrinth_south/Core_Shadowhold_Labyrinth_South.metatile.tilemap.rle"