    db 26        ; wTilemap_Width
    dw $030C     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/labyrinth_south/Core_Shadowhold_Labyrinth_South.collision.tilemap.rle"