    db 27        ; wTilemap_Width
    dw $01E6     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/marina_pathway/Core_Shadowhold_Marina_Pathway.collision.tilemap.rle"