    db 40        ; wTilemap_Width
    dw $0708     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/center/Cald_Ashyn_Center.collision.tilemap.rle"