    db 40        ;wTilemap_Width
    dw $0168     ;wTilemap_YMapPad
    db 29        ;
    db 35        ;wTilemap_VStop
    dw $0708     ;Uncompressed file size (excluding header)
    ;The imported file size was actually $070F because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/center/Cald_Ashyn_Center.metatile.tilemap.rle"