    db 24        ;wTilemap_Width
    dw $0180     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/ocean/ferry/Orothe_Ocean_Ferry.collision.tilemap.rle"