    db 24        ;wTilemap_Width
    dw $00D8     ;wTilemap_YMapPad
    db 13        ;
    db 6         ;wTilemap_VStop
    dw $0180     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/ocean/ferry/Orothe_Ocean_Ferry.metatile.tilemap.rle"