    db 16        ; wTilemap_Width
    dw $0090     ; wTilemap_YMapPad
    db 5         ;
    db 10        ; wTilemap_VStop
    dw $0140     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/island/outside/Orothe_Island_Outside.metatile.tilemap.rle"