    db 24        ; wTilemap_Width
    dw $0198     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/south/Naroom_Vash_South.collision.tilemap.rle"