    db 24        ;wTilemap_Width
    dw $00D8     ;wTilemap_YMapPad
    db 13        ;
    db 7         ;wTilemap_VStop
    dw $0198     ;Uncompressed file size (excluding header)
    ;The imported file size was actually $019F because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/south/Naroom_Vash_South.metatile.tilemap.rle"