    db 50        ; wTilemap_Width
    dw $05DC     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/middle_eastpathway_arrowroom/Core_Shadowhold_Middle_EastPathway_ArrowRoom.collision.tilemap.rle"