    db 12        ;wTilemap_Width
    dw $0090     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/grove/cache/Naroom_Grove_Cache.collision.tilemap.rle"