    db 30        ;wTilemap_Width
    dw $010E     ;wTilemap_YMapPad
    db 19        ;
    db 14        ;wTilemap_VStop
    dw $02D0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/middle_northpathway_cells/Core_Shadowhold_Middle_NorthPathway_Cells.metatile.tilemap.rle"