    db 30        ;wTilemap_Width
    dw $02D0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/middle_northpathway_cells/Core_Shadowhold_Middle_NorthPathway_Cells.collision.tilemap.rle"