    db 20        ;wTilemap_Width
    dw $0320     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/fort/outside/Arderial_Fort_Outside.collision.tilemap.rle"