    db 20        ; wTilemap_Width
    dw $0190     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/southbridge/Cald_Ashyn_SouthBridge.collision.tilemap.rle"