    db 45        ;wTilemap_Width
    dw $07E9     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/intersectiontriple/Cald_Caverns_IntersectionTriple.collision.tilemap.rle"