
    ; Tilesets for combat sprites of dream creatures.
    ; Only a small amount of space remaining but these sprites can be placed anywhere

    ; $4000
BITMAP_Combat_DarkAyebawRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/DarkAyebaw.tileset.rle"
    ; $42EB
BITMAP_Combat_DarkVellupRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/DarkVellup.tileset.rle"
    ; $4513
BITMAP_Combat_Hook_WingRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Hook_Wing.tileset.rle"
    ; $45E7
BITMAP_Combat_JingjackRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Jingjack.tileset.rle"
    ; $49A8
BITMAP_Combat_KazorRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Kazor.tileset.rle"
    ; $4E14
BITMAP_Combat_KletchRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Kletch.tileset.rle"
    ; $4F2A
BITMAP_Combat_SarbilRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sarbil.tileset.rle"
    ; $52AB
BITMAP_Combat_SpindleRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Spindle.tileset.rle"
    ; $5512
BITMAP_Combat_Vile_YoguRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vile_Yogu.tileset.rle"
    ; $5816
BITMAP_Combat_GhostBwispRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/GhostBwisp.tileset.rle"
    ; $59B9
BITMAP_Combat_PorkuslimeRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Porkuslime.tileset.rle"
    ; $5ADC
BITMAP_Combat_Tusk_BwispRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Tusk_Bwisp.tileset.rle"
    ; $5DA3
BITMAP_Combat_WeebatRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Weebat.tileset.rle"
    ; $5F62
BITMAP_Combat_GrawRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Graw.tileset.rle"
    ; $62B7
BITMAP_Combat_SabrebackRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sabreback.tileset.rle"
    ; $6646
BITMAP_Combat_Leaf_ChogoRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Leaf_Chogo.tileset.rle"
    ; $6A8F
BITMAP_Combat_RabbageRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Rabbage.tileset.rle"
    ; $6BEF
BITMAP_Combat_TreebitRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Treebit.tileset.rle"
    ; $6CE2
BITMAP_Combat_WasperineRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Wasperine.tileset.rle"
    ; $6EC6
BITMAP_Combat_Sea_JileRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sea_Jile.tileset.rle"
    ; $7281
BITMAP_Combat_SharblootRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sharbloot.tileset.rle"
    ; $7341