
    ; Tilesets for combat sprites of dream creatures.
    ; Only a small amount of space remaining but these sprites can be placed anywhere

    ; $4000
BITMAP_Combat_Agram1RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agram1.tileset.rle"
    ; $43B2
BITMAP_Combat_Agram2RLE::
    ; Single empty tile
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agram2.tileset.rle"
    ; $43B5
BITMAP_Combat_Agram3RLE::
    ; Single empty tile
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agram3.tileset.rle"
    ; $43B8
BITMAP_Combat_ShadowMagi1RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi1.tileset.rle"
    ; $44DB
BITMAP_Combat_ShadowMagi2RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi2.tileset.rle"
    ; $45E6
BITMAP_Combat_ShadowMagi3RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi3.tileset.rle"
    ; $4783
BITMAP_Combat_ShadowMagi4RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi4.tileset.rle"
    ; $4899
BITMAP_Combat_ShadowMagi5RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi5.tileset.rle"
    ; $4998
BITMAP_Combat_ShadowMagi6RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi6.tileset.rle"
    ; $4A98
BITMAP_Combat_ShadowMagi7RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi7.tileset.rle"
    ; $4BE8
BITMAP_Combat_ShadowMagi8RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi8.tileset.rle"
    ; $4D1D
BITMAP_Combat_SalafyRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Salafy.tileset.rle"
    ; $4E25
BITMAP_Combat_ArbolitRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Arbolit.tileset.rle"
    ; $4F40
BITMAP_Combat_OrpusRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Orpus.tileset.rle"
    ; $50B4
BITMAP_Combat_PlithRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Plith.tileset.rle"
    ; $51CA
BITMAP_Combat_ParmalagRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Parmalag.tileset.rle"
    ; $52D6
BITMAP_Combat_FlameHyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/FlameHyren.tileset.rle"
    ; $57C5
BITMAP_Combat_OrmagonRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Ormagon.tileset.rle"
    ; $5E55
BITMAP_Combat_Cave_HyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Cave_Hyren.tileset.rle"
    ; $63A1
BITMAP_Combat_Deep_HyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Deep_Hyren.tileset.rle"
    ; $6A86
BITMAP_Combat_MagmaHyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/MagmaHyren.tileset.rle"
    ; $6F96
BITMAP_Combat_BhatarRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Bhatar.tileset.rle"
    ; $71C5
BITMAP_Combat_Bolt_HyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Bolt_Hyren.tileset.rle"
    ; $755F
BITMAP_Combat_ShadwKarakRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadwKarak.tileset.rle"
    ; $77DC