

    ; For all the dream creatures and magi combat sprites,
    ; Contains all the tilemaps and attrmaps compressed with rle
    ; There's room for many more in this bank

    ; $4000
ATTRTILE_Combat_ArbollRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Arboll.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Arboll.tilemap.rle"
    ; $4028
ATTRTILE_Combat_BhatarRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Bhatar.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Bhatar.tilemap.rle"
    ; $4067
ATTRTILE_Combat_EebitRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Eebit.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Eebit.tilemap.rle"
    ; $4082
ATTRTILE_Combat_FurokRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Furok.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Furok.tilemap.rle"
    ; $410B
ATTRTILE_Combat_Leaf_ChogoRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Leaf_Chogo.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Leaf_Chogo.tilemap.rle"
    ; $418E
ATTRTILE_Combat_Leaf_HyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Leaf_Hyren.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Leaf_Hyren.tilemap.rle"
    ; $4237
ATTRTILE_Combat_PlithRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Plith.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Plith.tilemap.rle"
    ; $425A
ATTRTILE_Combat_RabbageRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Rabbage.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Rabbage.tilemap.rle"
    ; $427D
ATTRTILE_Combat_RudwotRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Rudwot.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Rudwot.tilemap.rle"
    ; $42AB
ATTRTILE_Combat_TimberHyrnRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/TimberHyrn.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/TimberHyrn.tilemap.rle"
    ; $4374
ATTRTILE_Combat_TreebitRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Treebit.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Treebit.tilemap.rle"
    ; $4392
ATTRTILE_Combat_TweeRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Twee.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Twee.tilemap.rle"
    ; $43BE
ATTRTILE_Combat_VinocRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vinoc.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vinoc.tilemap.rle"
    ; $4439
ATTRTILE_Combat_WasperineRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Wasperine.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Wasperine.tilemap.rle"
    ; $4466
ATTRTILE_Combat_WeeboRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Weebo.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Weebo.tilemap.rle"
    ; $4478
ATTRTILE_Combat_AbaquistRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Abaquist.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Abaquist.tilemap.rle"
    ; $44B9
ATTRTILE_Combat_BwillRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Bwill.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Bwill.tilemap.rle"
    ; $4517
ATTRTILE_Combat_CoralHyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/CoralHyren.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/CoralHyren.tilemap.rle"
    ; $45C6
ATTRTILE_Combat_Deep_HyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Deep_Hyren.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Deep_Hyren.tilemap.rle"
    ; $46A9
ATTRTILE_Combat_KarakRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Karak.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Karak.tilemap.rle"
    ; $475B
ATTRTILE_Combat_MegathanRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Megathan.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Megathan.tilemap.rle"
    ; $4836
ATTRTILE_Combat_OrpusRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Orpus.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Orpus.tilemap.rle"
    ; $4876
ATTRTILE_Combat_ParalitRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Paralit.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Paralit.tilemap.rle"
    ; $48E4
ATTRTILE_Combat_PlatheusRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Platheus.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Platheus.tilemap.rle"
    ; $4944
ATTRTILE_Combat_Sea_JileRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sea_Jile.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sea_Jile.tilemap.rle"
    ; $49E6
ATTRTILE_Combat_SharblootRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sharbloot.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sharbloot.tilemap.rle"
    ; $49FB
ATTRTILE_Combat_SphorRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sphor.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sphor.tilemap.rle"
    ; $4A74
ATTRTILE_Combat_AgovoRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agovo.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agovo.tilemap.rle"
    ; $4A8D
ATTRTILE_Combat_BisiwogRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Bisiwog.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Bisiwog.tilemap.rle"
    ; $4AC5
ATTRTILE_Combat_BrubRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Brub.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Brub.tilemap.rle"
    ; $4AD9
ATTRTILE_Combat_Cave_HyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Cave_Hyren.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Cave_Hyren.tilemap.rle"
    ; $4B85
ATTRTILE_Combat_CaveRudwotRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/CaveRudwot.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/CaveRudwot.tilemap.rle"
    ; $4BB9
ATTRTILE_Combat_GhostBwispRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/GhostBwisp.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/GhostBwisp.tilemap.rle"
    ; $4BF5
ATTRTILE_Combat_GiantKoritRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/GiantKorit.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/GiantKorit.tilemap.rle"
    ; $4C3D
ATTRTILE_Combat_Gum_GumRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Gum_Gum.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Gum_Gum.tilemap.rle"
    ; $4C4B
ATTRTILE_Combat_Mush_HyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Mush_Hyren.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Mush_Hyren.tilemap.rle"
    ; $4CB1
ATTRTILE_Combat_OrmagonRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Ormagon.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Ormagon.tilemap.rle"
    ; $4DA1
ATTRTILE_Combat_ParmalagRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Parmalag.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Parmalag.tilemap.rle"
    ; $4DCB
ATTRTILE_Combat_PorkuslimeRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Porkuslime.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Porkuslime.tilemap.rle"
    ; $4DE4
ATTRTILE_Combat_Tusk_BwispRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Tusk_Bwisp.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Tusk_Bwisp.tilemap.rle"
    ; $4E5A
ATTRTILE_Combat_VulborRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vulbor.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vulbor.tilemap.rle"
    ; $4EA9
ATTRTILE_Combat_WeebatRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Weebat.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Weebat.tilemap.rle"
    ; $4EEA
ATTRTILE_Combat_ArbolitRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Arbolit.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Arbolit.tilemap.rle"
    ; $4F0B
ATTRTILE_Combat_DioborRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Diobor.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Diobor.tilemap.rle"
    ; $4F44
ATTRTILE_Combat_DrakanRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Drakan.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Drakan.tilemap.rle"
    ; $4FB8
ATTRTILE_Combat_FlameHyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/FlameHyren.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/FlameHyren.tilemap.rle"
    ; $5086
ATTRTILE_Combat_GrawRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Graw.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Graw.tilemap.rle"
    ; $50FC
ATTRTILE_Combat_KelthetRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Kelthet.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Kelthet.tilemap.rle"
    ; $5181
ATTRTILE_Combat_Lava_AqRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Lava_Aq.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Lava_Aq.tilemap.rle"
    ; $51D5
ATTRTILE_Combat_LavaArbollRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/LavaArboll.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/LavaArboll.tilemap.rle"
    ; $525B
ATTRTILE_Combat_LavaBalmntRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/LavaBalmnt.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/LavaBalmnt.tilemap.rle"
    ; $531C
ATTRTILE_Combat_MagmaHyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/MagmaHyren.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/MagmaHyren.tilemap.rle"
    ; $53C8
ATTRTILE_Combat_QuorRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Quor.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Quor.tilemap.rle"
    ; $5404
ATTRTILE_Combat_RaxisRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Raxis.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Raxis.tilemap.rle"
    ; $546D
ATTRTILE_Combat_SabrebackRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sabreback.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sabreback.tilemap.rle"
    ; $54E6
ATTRTILE_Combat_AlabanRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Alaban.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Alaban.tilemap.rle"
    ; $554A
ATTRTILE_Combat_AyebawRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Ayebaw.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Ayebaw.tilemap.rle"
    ; $55B4
ATTRTILE_Combat_EpikRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Epik.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Epik.tilemap.rle"
    ; $560E
ATTRTILE_Combat_Bolt_HyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Bolt_Hyren.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Bolt_Hyren.tilemap.rle"
    ; $56A4
ATTRTILE_Combat_Orathan_FRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Orathan_F.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Orathan_F.tilemap.rle"
    ; $5788
ATTRTILE_Combat_OrishRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Orish.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Orish.tilemap.rle"
    ; $5839
ATTRTILE_Combat_ThundrHyrnRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ThundrHyrn.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ThundrHyrn.tilemap.rle"
    ; $5912
ATTRTILE_Combat_VashpRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vashp.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vashp.tilemap.rle"
    ; $5968
ATTRTILE_Combat_VellupRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vellup.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vellup.tilemap.rle"
    ; $5994
ATTRTILE_Combat_XyxRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Xyx.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Xyx.tilemap.rle"
    ; $59E2
ATTRTILE_Combat_BlackAgovoRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/BlackAgovo.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/BlackAgovo.tilemap.rle"
    ; $5A27
ATTRTILE_Combat_Chaos_JileRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Chaos_Jile.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Chaos_Jile.tilemap.rle"
    ; $5A9B
ATTRTILE_Combat_Core_GragRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Core_Grag.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Core_Grag.tilemap.rle"
    ; $5AEE
ATTRTILE_Combat_Core_HyrenRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Core_Hyren.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Core_Hyren.tilemap.rle"
    ; $5BDE
ATTRTILE_Combat_DarkAyebawRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/DarkAyebaw.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/DarkAyebaw.tilemap.rle"
    ; $5C2E
ATTRTILE_Combat_DarkVellupRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/DarkVellup.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/DarkVellup.tilemap.rle"
    ; $5C8E
ATTRTILE_Combat_DryteFiendRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/DryteFiend.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/DryteFiend.tilemap.rle"
    ; $5D24
ATTRTILE_Combat_GraxRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Grax.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Grax.tilemap.rle"
    ; $5D6E
ATTRTILE_Combat_Hook_WingRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Hook_Wing.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Hook_Wing.tilemap.rle"
    ; $5D84
ATTRTILE_Combat_JingjackRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Jingjack.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Jingjack.tilemap.rle"
    ; $5E00
ATTRTILE_Combat_KazorRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Kazor.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Kazor.tilemap.rle"
    ; $5E9C
ATTRTILE_Combat_KletchRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Kletch.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Kletch.tilemap.rle"
    ; $5EBD
ATTRTILE_Combat_KoilRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Koil.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Koil.tilemap.rle"
    ; $5F31
ATTRTILE_Combat_SarbilRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sarbil.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Sarbil.tilemap.rle"
    ; $5FBE
ATTRTILE_Combat_ShadwKarakRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadwKarak.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadwKarak.tilemap.rle"
    ; $6021
ATTRTILE_Combat_ShadwVinocRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadwVinoc.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadwVinoc.tilemap.rle"
    ; $606D
ATTRTILE_Combat_ShryqueRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Shryque.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Shryque.tilemap.rle"
    ; $60AA
ATTRTILE_Combat_SpindleRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Spindle.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Spindle.tilemap.rle"
    ; $611E
ATTRTILE_Combat_Vile_YoguRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vile_Yogu.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Vile_Yogu.tilemap.rle"
    ; $6186
ATTRTILE_Combat_YvohcnaRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Yvohcna.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Yvohcna.tilemap.rle"
    ; $620C
ATTRTILE_Combat_BorgorRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Borgor.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Borgor.tilemap.rle"
    ; $62A5
ATTRTILE_Combat_TonyRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Tony.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Tony.tilemap.rle"
    ; $62D3
ATTRTILE_Combat_TogothRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Togoth.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Togoth.tilemap.rle"
    ; $6305
ATTRTILE_Combat_OgarRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Ogar.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Ogar.tilemap.rle"
    ; $6339
ATTRTILE_Combat_KorremarRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Korremar.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Korremar.tilemap.rle"
    ; $6370
ATTRTILE_Combat_WarradaRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Warrada.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Warrada.tilemap.rle"
    ; $63AC
ATTRTILE_Combat_KorgRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Korg.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Korg.tilemap.rle"
    ; $63E3
ATTRTILE_Combat_ZetRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Zet.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Zet.tilemap.rle"
    ; $640F
ATTRTILE_Combat_MoragRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Morag.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Morag.tilemap.rle"
    ; $6443
ATTRTILE_Combat_Agram1RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agram1.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agram1.tilemap.rle"
    ; $64B3
ATTRTILE_Combat_Agram2RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agram2.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agram2.tilemap.rle"
    ; $64BB
ATTRTILE_Combat_Agram3RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agram3.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Agram3.tilemap.rle"
    ; $64C3
ATTRTILE_Combat_ShadowMagi1RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi1.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi1.tilemap.rle"
    ; $64ED
ATTRTILE_Combat_ShadowMagi2RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi2.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi2.tilemap.rle"
    ; $651C
ATTRTILE_Combat_ShadowMagi3RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi3.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi3.tilemap.rle"
    ; $6551
ATTRTILE_Combat_ShadowMagi4RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi4.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi4.tilemap.rle"
    ; $657F
ATTRTILE_Combat_ShadowMagi5RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi5.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi5.tilemap.rle"
    ; $65B1
ATTRTILE_Combat_ShadowMagi6RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi6.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi6.tilemap.rle"
    ; $65DE
ATTRTILE_Combat_ShadowMagi7RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi7.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi7.tilemap.rle"
    ; $660B
ATTRTILE_Combat_ShadowMagi8RLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi8.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/ShadowMagi8.tilemap.rle"
    ; $6639
ATTRTILE_Combat_SalafyRLE::
    INCBIN "autogenerated/assets/dreamcreatures/combat/Salafy.attrmap.rle"
    INCBIN "autogenerated/assets/dreamcreatures/combat/Salafy.tilemap.rle"
    ; $666D