    db 35        ; wTilemap_Width
    dw $02BC     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/tunnels/entrance/Cald_Tunnels_Entrance.collision.tilemap.rle"