    db 16        ; wTilemap_Width
    dw $0090     ; wTilemap_YMapPad
    db 5         ;
    db 20        ; wTilemap_VStop
    dw $01E0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/verticalpipe_unused/Arderial_Geyser_VerticalPipe_Unused.metatile.tilemap.rle"