    db 30        ;wTilemap_Width
    dw $0384     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/geyser/altar/Underneath_Geyser_Altar.collision.tilemap.rle"