    db 40        ; wTilemap_Width
    dw $0320     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/deep_intersection/Naroom_Forest_Deep_Intersection.collision.tilemap.rle"