    db 36        ;wTilemap_Width
    dw $0144     ;wTilemap_YMapPad
    db 25        ;
    db 26        ;wTilemap_VStop
    dw $0510     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/north/northwestexit/Arderial_North_NorthwestExit.metatile.tilemap.rle"