    db 36        ; wTilemap_Width
    dw $0510     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/north/northwestexit/Arderial_North_NorthwestExit.collision.tilemap.rle"