    db 20        ;wTilemap_Width
    dw $01E0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/geyser/doorway/Naroom_Geyser_Doorway.collision.tilemap.rle"