    db 18        ;wTilemap_Width
    dw $0120     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/historian/upstairsroom/Arderial_Historian_UpstairsRoom.collision.tilemap.rle"