    db 18        ; wTilemap_Width
    dw $00A2     ; wTilemap_YMapPad
    db 7         ;
    db 6         ; wTilemap_VStop
    dw $0120     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/historian/upstairsroom/Arderial_Historian_UpstairsRoom.metatile.tilemap.rle"