    db 30        ; wTilemap_Width
    dw $03FC     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/pipes2_pipeanalysis/Arderial_Geyser_Pipes2_PipeAnalysis_Mask.collision.tilemap.rle"