    db 30        ;wTilemap_Width
    dw $010E     ;wTilemap_YMapPad
    db 19        ;
    db 24        ;wTilemap_VStop
    dw $03FC     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/pipes2_pipeanalysis/Arderial_Geyser_Pipes2_PipeAnalysis.metatile.tilemap.rle"