    db 24        ; wTilemap_Width
    dw $0240     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/end_caldcache/Arderial_Geyser_End_CaldCache.collision.tilemap.rle"