all: clean game.gbc

game.o: source/game.asm source/banks/*.asm source/includes/*.asm source/macros/*.asm source/ram/*.asm musyx/*.asm source/test/*.asm source/engine/*.asm autogenerated/assets/* autogenerated/musyx/*
	rgbasm -h -L -o game.o source/game.asm

game.gbc: game.o
	rgblink -n game.sym -m game.map -o $@ -p 0 $<
	rgbfix -v -p 0 $@
	md5sum $@

clean:
	rm game.o game.gbc game.sym game.map -f
	$(info Also do "make delextras" to delete other extra files. To remake extras, do "make extras")

delextras: delassets delmusyx delmgi delautopack

extras: assets musyx mgi autopack

assets: delassets
	python python\\make\\assets_make.py

delassets:
	python python\\make\\assets_unmake.py

musyx: delmusyx
	python python\\make\\musyx_make.py

delmusyx:
	python python\\make\\musyx_unmake.py

mgi: delmgi
	python python\\make\\magiscript_make.py

delmgi:
	python python\\make\\magiscript_unmake.py
	
autopack: delautopack
	python python\\make\\autopack_make.py
	
delautopack:
	python python\\make\\autopack_unmake.py
	
preview:
	python python\\make\\preview_make.py

tests:
	python -m unittest python\\projutils\\tests\\test_asm.py
	python -m unittest python\\projutils\\tests\\test_autopack.py
	python -m unittest python\\projutils\\tests\\test_battle.py
	python -m unittest python\\projutils\\tests\\test_collision.py
	python -m unittest python\\projutils\\tests\\test_color.py
	python -m unittest python\\projutils\\tests\\test_encoding.py
	python -m unittest python\\projutils\\tests\\test_fileregistry.py
	python -m unittest python\\projutils\\tests\\test_hotspot.py
	python -m unittest python\\projutils\\tests\\test_lbm.py
	python -m unittest python\\projutils\\tests\\test_magireader.py
	python -m unittest python\\projutils\\tests\\test_pattern.py
	python -m unittest python\\projutils\\tests\\test_preview.py
	python -m unittest python\\projutils\\tests\\test_rle.py
	python -m unittest python\\projutils\\tests\\test_sprite.py
	python -m unittest python\\projutils\\tests\\test_textreplace.py
	python -m unittest python\\projutils\\tests\\test_tilemap.py
	python -m unittest python\\projutils\\tests\\test_tileset.py
	python -m unittest python\\projutils\\tests\\test_utils.py
	python -m unittest python\\magiparser\\tests\\test_magiparser.py

help:
	$(info -> generate game files)
	$(info clean -> delete game files)
	$(info )
	$(info preview -> generate scene previews (python/out/preview/))
	$(info )
	$(info extras -> generate assets, musyx, mgi, autopack)
	$(info delextras -> delete assets, musyx, mgi, autopack)
	$(info )
	$(info assets -> compile files (e.g. image, map files))
	$(info delassets -> delete assets)
	$(info )
	$(info musyx -> compile music files (MusyX project))
	$(info delassets -> delete music files)
	$(info )
	$(info mgi -> compile script files (.mgi))
	$(info delmgi -> delete script files)
	$(info )
	$(info autopack -> pack autosorted assets into ROM space from autopack.config)
	$(info delautopack -> delete autopack file)
	$(info )
	