    db 60        ;wTilemap_Width
    dw $021C     ;wTilemap_YMapPad
    db 49        ;
    db 40        ;wTilemap_VStop
    dw $0BB8     ;Uncompressed file size (excluding header)
    ;The imported file size was actually $0BBF because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/east/Underneath_Mushroom_East.metatile.tilemap.rle"