    db 40        ;wTilemap_Width
    dw $0708     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/detour_end/Cald_Caverns_Detour_End.collision.tilemap.rle"