    db 55        ;wTilemap_Width
    dw $01EF     ;wTilemap_YMapPad
    db 44        ;
    db 29        ;wTilemap_VStop
    dw $0861     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_cells/Core_Shadowhold_Deep_Cells.metatile.tilemap.rle"