    db 55        ;wTilemap_Width
    dw $0861     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_cells/Core_Shadowhold_Deep_Cells.collision.tilemap.rle"