SECTION "ROM Bank $042", ROMX[$4000], BANK[$42]

    ; $4000
    INCLUDE "source/game/cardscene/cardscene_cardtileattrmaps.asm"


    ; $4140
ATTRTILE_Fightscene_Arena_ArderialTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Arderial/ArderialTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Arderial/ArderialTop.tilemap.rle"

    ; $41CF
ATTRTILE_Fightscene_Arena_ArderialBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Arderial/ArderialBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Arderial/ArderialBottom.tilemap.rle"

    ; $423E
ATTRTILE_Fightscene_Arena_CoreTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Core/CoreTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Core/CoreTop.tilemap.rle"

    ; $42EA
ATTRTILE_Fightscene_Arena_CoreBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Core/CoreBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Core/CoreBottom.tilemap.rle"

    ; $4359
ATTRTILE_Fightscene_Arena_CaldTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Cald/CaldTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Cald/CaldTop.tilemap.rle"

    ; $43EF
ATTRTILE_Fightscene_Arena_CaldBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Cald/CaldBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Cald/CaldBottom.tilemap.rle"

    ; $4484
ATTRTILE_Fightscene_Arena_UnderneathTunnelsTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/UnderneathTunnels/UnderneathTunnelsTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/UnderneathTunnels/UnderneathTunnelsTop.tilemap.rle"

    ; $44ED
ATTRTILE_Fightscene_Arena_UnderneathTunnelsBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/UnderneathTunnels/UnderneathTunnelsBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/UnderneathTunnels/UnderneathTunnelsBottom.tilemap.rle"

    ; $4562
ATTRTILE_Fightscene_Arena_CaldGeyserTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/CaldGeyser/CaldGeyserTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/CaldGeyser/CaldGeyserTop.tilemap.rle"

    ; $45E4
ATTRTILE_Fightscene_Arena_CaldGeyserBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/CaldGeyser/CaldGeyserBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/CaldGeyser/CaldGeyserBottom.tilemap.rle"

    ; $4654
ATTRTILE_Fightscene_Arena_NaroomGeyserTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/NaroomGeyser/NaroomGeyserTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/NaroomGeyser/NaroomGeyserTop.tilemap.rle"

    ; $46EB
ATTRTILE_Fightscene_Arena_NaroomGeyserBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/NaroomGeyser/NaroomGeyserBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/NaroomGeyser/NaroomGeyserBottom.tilemap.rle"

    ; $4762
ATTRTILE_Fightscene_Arena_NaroomTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Naroom/NaroomTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Naroom/NaroomTop.tilemap.rle"

    ; $47FE
ATTRTILE_Fightscene_Arena_NaroomBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Naroom/NaroomBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Naroom/NaroomBottom.tilemap.rle"

    ; $48B5
ATTRTILE_Fightscene_Arena_UnderneathGeyserTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/UnderneathGeyser/UnderneathGeyserTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/UnderneathGeyser/UnderneathGeyserTop.tilemap.rle"

    ; $4956
ATTRTILE_Fightscene_Arena_UnderneathGeyserBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/UnderneathGeyser/UnderneathGeyserBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/UnderneathGeyser/UnderneathGeyserBottom.tilemap.rle"

    ; $4A08
ATTRTILE_Fightscene_Arena_OrotheStarfishTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheStarfish/OrotheStarfishTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/OrotheStarfish/OrotheStarfishTop.tilemap.rle"

    ; $4A9C
ATTRTILE_Fightscene_Arena_OrotheStarfishBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheStarfish/OrotheStarfishBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/OrotheStarfish/OrotheStarfishBottom.tilemap.rle"

    ; $4B0C
ATTRTILE_Fightscene_Arena_OrotheGeyserTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheGeyser/OrotheGeyserTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/OrotheGeyser/OrotheGeyserTop.tilemap.rle"

    ; $4B7B
ATTRTILE_Fightscene_Arena_OrotheGeyserBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheGeyser/OrotheGeyserBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/OrotheGeyser/OrotheGeyserBottom.tilemap.rle"

    ; $4BF3
ATTRTILE_Fightscene_Arena_OrotheTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Orothe/OrotheTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Orothe/OrotheTop.tilemap.rle"

    ; $4C65
ATTRTILE_Fightscene_Arena_OrotheBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Orothe/OrotheBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Orothe/OrotheBottom.tilemap.rle"

    ; $4CDF
ATTRTILE_Fightscene_Arena_OrotheTunnelsTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheTunnels/OrotheTunnelsTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/OrotheTunnels/OrotheTunnelsTop.tilemap.rle"

    ; $4D66
ATTRTILE_Fightscene_Arena_OrotheTunnelsBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheTunnels/OrotheTunnelsBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/OrotheTunnels/OrotheTunnelsBottom.tilemap.rle"

    ; $4DD7
ATTRTILE_Fightscene_Arena_ShadowholdTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Shadowhold/ShadowholdTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Shadowhold/ShadowholdTop.tilemap.rle"

    ; $4E51
ATTRTILE_Fightscene_Arena_ShadowholdBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Shadowhold/ShadowholdBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Shadowhold/ShadowholdBottom.tilemap.rle"

    ; $4ED7
ATTRTILE_Fightscene_Arena_UnderneathTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Underneath/UnderneathTop.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Underneath/UnderneathTop.tilemap.rle"

    ; $4F52
ATTRTILE_Fightscene_Arena_UnderneathBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Underneath/UnderneathBottom.attrmap.rle"
    INCBIN "autogenerated/assets/fightscene/arena/Underneath/UnderneathBottom.tilemap.rle"

    ; $4FF0