    db 36        ; wTilemap_Width
    dw $0144     ; wTilemap_YMapPad
    db 25        ;
    db 20        ; wTilemap_VStop
    dw $0438     ; Uncompressed file size (excluding header)
    ; The imported file size was actually $043F because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/core/end/pathway/Core_End_Pathway.metatile.tilemap.rle"