    db 16        ; wTilemap_Width
    dw $0100     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/puzzle_unsolved/Naroom_Forest_Puzzle_Unsolved.collision.tilemap.rle"