
    ; Tilesets for combat sprites of dream creatures.
    ; Only a small amount of space remaining but these sprites can be placed anywhere

    ; $4000
BITMAP_Combat_EebitRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Eebit.tileset.rle"
    ; $40AE
BITMAP_Combat_WeeboRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Weebo.tileset.rle"
    ; $4141
BITMAP_Combat_BrubRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Brub.tileset.rle"
    ; $41C9
BITMAP_Combat_Gum_GumRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Gum_Gum.tileset.rle"
    ; $425C
BITMAP_Combat_Orathan_FRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Orathan_F.tileset.rle"
    ; $4810
BITMAP_Combat_MegathanRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Megathan.tileset.rle"
    ; $4D5E
BITMAP_Combat_Core_HyrenRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Core_Hyren.tileset.rle"
    ; $546A
BITMAP_Combat_CoralHyrenRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/CoralHyren.tileset.rle"
    ; $5873
BITMAP_Combat_DryteFiendRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/DryteFiend.tileset.rle"
    ; $5CC7
BITMAP_Combat_FurokRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Furok.tileset.rle"
    ; $60EE
BITMAP_Combat_TimberHyrnRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/TimberHyrn.tileset.rle"
    ; $65E8
BITMAP_Combat_Leaf_HyrenRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Leaf_Hyren.tileset.rle"
    ; $69A9
BITMAP_Combat_ThundrHyrnRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ThundrHyrn.tileset.rle"
    ; $6F0B
BITMAP_Combat_KarakRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Karak.tileset.rle"

    ; $72DA