
    ; Tilesets for combat sprites of dream creatures.
    ; Only a small amount of space remaining but these sprites can be placed anywhere
    ; Also (accidentally) contains an unused uncompressed copy of Abaquist's tileset

    ; $4000
BITMAP_Combat_VulborRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Vulbor.tileset.rle"
    ; $41D3
BITMAP_Combat_AyebawRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Ayebaw.tileset.rle"
    ; $446D
BITMAP_Combat_DioborRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Diobor.tileset.rle"
    ; $46B5
BITMAP_Combat_GiantKoritRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/GiantKorit.tileset.rle"
    ; $48FD
BITMAP_Combat_Lava_AqRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Lava_Aq.tileset.rle"
    ; $4AE2
BITMAP_Combat_XyxRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Xyx.tileset.rle"
    ; $4D1B
BITMAP_Combat_LavaArbollRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/LavaArboll.tileset.rle"
    ; $5034
BITMAP_Combat_Mush_HyrenRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Mush_Hyren.tileset.rle"
    ; $52CC
BITMAP_Combat_Core_GragRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Core_Grag.tileset.rle"
    ; $54E4
BITMAP_Combat_DrakanRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Drakan.tileset.rle"
    ; $575F
BITMAP_Combat_RaxisRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Raxis.tileset.rle"
    ; $59AD
BITMAP_Combat_EpikRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Epik.tileset.rle"
    ; $5C35
BITMAP_Combat_BlackAgovoRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/BlackAgovo.tileset.rle"
    ; $5E06
BITMAP_Combat_BwillRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Bwill.tileset.rle"
    ; $608C
BITMAP_Combat_ShryqueRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Shryque.tileset.rle"
    ; $6294
BITMAP_Combat_ShadwVinocRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ShadwVinoc.tileset.rle"
    ; $64CE
BITMAP_Combat_AbaquistRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Abaquist.tileset.rle"
    ; $668B
BITMAP_Combat_AbaquistUncompressed_Unused::
    ; Duplicate copy of BITMAP_Combat_AbaquistRLE, except in uncompressed form.
    ; Seems to have been accidentally added
    INCBIN "autogenerated/assets/fightscene/creatures/Abaquist_UNUSED.tileset"
    ; $688B
BITMAP_Combat_QuorRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Quor.tileset.rle"
    ; $6A67
BITMAP_Combat_GraxRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Grax.tileset.rle"
    ; $6C83
BITMAP_Combat_VinocRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Vinoc.tileset.rle"
    ; $6F8D
BITMAP_Combat_TonyRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Tony.tileset.rle"
    ; $70DA
BITMAP_Combat_TogothRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Togoth.tileset.rle"
    ; $71C6
BITMAP_Combat_OgarRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Ogar.tileset.rle"
    ; $72FA
BITMAP_Combat_KorremarRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Korremar.tileset.rle"
    ; $7505
BITMAP_Combat_WarradaRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Warrada.tileset.rle"
    ; $768E
BITMAP_Combat_KorgRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Korg.tileset.rle"
    ; $77FD
BITMAP_Combat_ZetRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Zet.tileset.rle"
    ; $7929
BITMAP_Combat_MoragRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Morag.tileset.rle"
    ; $7AD9