
    ; Tilesets for combat sprites of dream creatures.
    ; Only a small amount of space remaining but these sprites can be placed anywhere

    ; $4000
BITMAP_Fightscene_Creature_BorgorRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Borgor.tileset.rle"
    ; $43B8
BITMAP_Fightscene_Creature_OrishRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Orish.tileset.rle"
    ; $47D3
BITMAP_Fightscene_Creature_KelthetRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Kelthet.tileset.rle"
    ; $4C75
BITMAP_Fightscene_Creature_VashpRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Vashp.tileset.rle"
    ; $4F43
BITMAP_Fightscene_Creature_YvohcnaRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Yvohcna.tileset.rle"
    ; $527B
BITMAP_Fightscene_Creature_LavaBalmntRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/LavaBalmnt.tileset.rle"
    ; $5766
BITMAP_Fightscene_Creature_PlatheusRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Platheus.tileset.rle"
    ; $5A9B
BITMAP_Fightscene_Creature_ParalitRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Paralit.tileset.rle"
    ; $5DC5
BITMAP_Fightscene_Creature_Chaos_JileRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Chaos_Jile.tileset.rle"
    ; $6187
BITMAP_Fightscene_Creature_AlabanRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Alaban.tileset.rle"
    ; $64B0
BITMAP_Fightscene_Creature_KoilRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Koil.tileset.rle"
    ; $6784
BITMAP_Fightscene_Creature_AgovoRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Agovo.tileset.rle"
    ; $6898
BITMAP_Fightscene_Creature_CaveRudwotRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/CaveRudwot.tileset.rle"
    ; $6A51
BITMAP_Fightscene_Creature_VellupRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Vellup.tileset.rle"
    ; $6B8F
BITMAP_Fightscene_Creature_ArbollRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Arboll.tileset.rle"
    ; $6CAE
BITMAP_Fightscene_Creature_BisiwogRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Bisiwog.tileset.rle"
    ; $6DD6
BITMAP_Fightscene_Creature_RudwotRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Rudwot.tileset.rle"
    ; $6F31
BITMAP_Fightscene_Creature_TweeRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Twee.tileset.rle"
    ; $707D
BITMAP_Fightscene_Creature_SphorRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Sphor.tileset.rle"
    ; $740A