
    ; Tilesets for combat sprites of dream creatures.
    ; Only a small amount of space remaining but these sprites can be placed anywhere

    ; $4000
BITMAP_Combat_BorgorRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Borgor.tileset.rle"
    ; $43B8
BITMAP_Combat_OrishRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Orish.tileset.rle"
    ; $47D3
BITMAP_Combat_KelthetRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Kelthet.tileset.rle"
    ; $4C75
BITMAP_Combat_VashpRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Vashp.tileset.rle"
    ; $4F43
BITMAP_Combat_YvohcnaRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Yvohcna.tileset.rle"
    ; $527B
BITMAP_Combat_LavaBalmntRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/LavaBalmnt.tileset.rle"
    ; $5766
BITMAP_Combat_PlatheusRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Platheus.tileset.rle"
    ; $5A9B
BITMAP_Combat_ParalitRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Paralit.tileset.rle"
    ; $5DC5
BITMAP_Combat_Chaos_JileRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Chaos_Jile.tileset.rle"
    ; $6187
BITMAP_Combat_AlabanRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Alaban.tileset.rle"
    ; $64B0
BITMAP_Combat_KoilRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Koil.tileset.rle"
    ; $6784
BITMAP_Combat_AgovoRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Agovo.tileset.rle"
    ; $6898
BITMAP_Combat_CaveRudwotRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/CaveRudwot.tileset.rle"
    ; $6A51
BITMAP_Combat_VellupRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Vellup.tileset.rle"
    ; $6B8F
BITMAP_Combat_ArbollRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Arboll.tileset.rle"
    ; $6CAE
BITMAP_Combat_BisiwogRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Bisiwog.tileset.rle"
    ; $6DD6
BITMAP_Combat_RudwotRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Rudwot.tileset.rle"
    ; $6F31
BITMAP_Combat_TweeRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Twee.tileset.rle"
    ; $707D
BITMAP_Combat_SphorRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Sphor.tileset.rle"
    ; $740A