
    ; Tilesets for combat sprites of dream creatures.
    ; Only a small amount of space remaining but these sprites can be placed anywhere

    ; $4000
BITMAP_Fightscene_Creature_DarkAyebawRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/DarkAyebaw.tileset.rle"
    ; $42EB
BITMAP_Fightscene_Creature_DarkVellupRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/DarkVellup.tileset.rle"
    ; $4513
BITMAP_Fightscene_Creature_Hook_WingRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Hook_Wing.tileset.rle"
    ; $45E7
BITMAP_Fightscene_Creature_JingjackRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Jingjack.tileset.rle"
    ; $49A8
BITMAP_Fightscene_Creature_KazorRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Kazor.tileset.rle"
    ; $4E14
BITMAP_Fightscene_Creature_KletchRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Kletch.tileset.rle"
    ; $4F2A
BITMAP_Fightscene_Creature_SarbilRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Sarbil.tileset.rle"
    ; $52AB
BITMAP_Fightscene_Creature_SpindleRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Spindle.tileset.rle"
    ; $5512
BITMAP_Fightscene_Creature_Vile_YoguRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Vile_Yogu.tileset.rle"
    ; $5816
BITMAP_Fightscene_Creature_GhostBwispRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/GhostBwisp.tileset.rle"
    ; $59B9
BITMAP_Fightscene_Creature_PorkuslimeRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Porkuslime.tileset.rle"
    ; $5ADC
BITMAP_Fightscene_Creature_Tusk_BwispRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Tusk_Bwisp.tileset.rle"
    ; $5DA3
BITMAP_Fightscene_Creature_WeebatRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Weebat.tileset.rle"
    ; $5F62
BITMAP_Fightscene_Creature_GrawRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Graw.tileset.rle"
    ; $62B7
BITMAP_Fightscene_Creature_SabrebackRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Sabreback.tileset.rle"
    ; $6646
BITMAP_Fightscene_Creature_Leaf_ChogoRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Leaf_Chogo.tileset.rle"
    ; $6A8F
BITMAP_Fightscene_Creature_RabbageRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Rabbage.tileset.rle"
    ; $6BEF
BITMAP_Fightscene_Creature_TreebitRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Treebit.tileset.rle"
    ; $6CE2
BITMAP_Fightscene_Creature_WasperineRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Wasperine.tileset.rle"
    ; $6EC6
BITMAP_Fightscene_Creature_Sea_JileRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Sea_Jile.tileset.rle"
    ; $7281
BITMAP_Fightscene_Creature_SharblootRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Sharbloot.tileset.rle"
    ; $7341