
    ; Tilesets for combat sprites of dream creatures.
    ; Only a small amount of space remaining but these sprites can be placed anywhere

    ; $4000
BITMAP_Fightscene_Creature_Agram1RLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Agram1.tileset.rle"
    ; $43B2
BITMAP_Fightscene_Creature_Agram2RLE::
    ; Single empty tile
    INCBIN "autogenerated/assets/fightscene/creatures/Agram2.tileset.rle"
    ; $43B5
BITMAP_Fightscene_Creature_Agram3RLE::
    ; Single empty tile
    INCBIN "autogenerated/assets/fightscene/creatures/Agram3.tileset.rle"
    ; $43B8
BITMAP_Fightscene_Creature_ShadowMagi1RLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ShadowMagi1.tileset.rle"
    ; $44DB
BITMAP_Fightscene_Creature_ShadowMagi2RLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ShadowMagi2.tileset.rle"
    ; $45E6
BITMAP_Fightscene_Creature_ShadowMagi3RLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ShadowMagi3.tileset.rle"
    ; $4783
BITMAP_Fightscene_Creature_ShadowMagi4RLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ShadowMagi4.tileset.rle"
    ; $4899
BITMAP_Fightscene_Creature_ShadowMagi5RLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ShadowMagi5.tileset.rle"
    ; $4998
BITMAP_Fightscene_Creature_ShadowMagi6RLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ShadowMagi6.tileset.rle"
    ; $4A98
BITMAP_Fightscene_Creature_ShadowMagi7RLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ShadowMagi7.tileset.rle"
    ; $4BE8
BITMAP_Fightscene_Creature_ShadowMagi8RLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ShadowMagi8.tileset.rle"
    ; $4D1D
BITMAP_Fightscene_Creature_SalafyRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Salafy.tileset.rle"
    ; $4E25
BITMAP_Fightscene_Creature_ArbolitRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Arbolit.tileset.rle"
    ; $4F40
BITMAP_Fightscene_Creature_OrpusRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Orpus.tileset.rle"
    ; $50B4
BITMAP_Fightscene_Creature_PlithRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Plith.tileset.rle"
    ; $51CA
BITMAP_Fightscene_Creature_ParmalagRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Parmalag.tileset.rle"
    ; $52D6
BITMAP_Fightscene_Creature_FlameHyrenRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/FlameHyren.tileset.rle"
    ; $57C5
BITMAP_Fightscene_Creature_OrmagonRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Ormagon.tileset.rle"
    ; $5E55
BITMAP_Fightscene_Creature_Cave_HyrenRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Cave_Hyren.tileset.rle"
    ; $63A1
BITMAP_Fightscene_Creature_Deep_HyrenRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Deep_Hyren.tileset.rle"
    ; $6A86
BITMAP_Fightscene_Creature_MagmaHyrenRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/MagmaHyren.tileset.rle"
    ; $6F96
BITMAP_Fightscene_Creature_BhatarRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Bhatar.tileset.rle"
    ; $71C5
BITMAP_Fightscene_Creature_Bolt_HyrenRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/Bolt_Hyren.tileset.rle"
    ; $755F
BITMAP_Fightscene_Creature_ShadwKarakRLE::
    INCBIN "autogenerated/assets/fightscene/creatures/ShadwKarak.tileset.rle"
    ; $77DC