; Unused Fightscene palettes
; At one point, you could change a creature or arena's palette into one of theses palettes
; But the function was removed
; For some strange reason, some of these palettes have the alpha set as 1

PAL_Fightscene_Effect_White_UNUSED::
    INCBIN "autogenerated/assets/fightscene/effects/White.pal"

PAL_Fightscene_Effect_Black_UNUSED::
    INCBIN "autogenerated/assets/fightscene/effects/Black.pal"

PAL_Fightscene_Effect_Fire_UNUSED::
    INCBIN "autogenerated/assets/fightscene/effects/Fire.pal"

PAL_Fightscene_Effect_Ice_UNUSED::
    INCBIN "autogenerated/assets/fightscene/effects/Ice.pal"


Fightscene_EffectPalette_Table_UNUSED::
    dw PAL_Fightscene_Effect_White
    dw PAL_Fightscene_Effect_Black
    dw PAL_Fightscene_Effect_Fire
    dw PAL_Fightscene_Effect_Ice