    db 42        ; wTilemap_Width
    dw $017A     ; wTilemap_YMapPad
    db 31        ;
    db 30        ; wTilemap_VStop
    dw $0690     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/north/southeastentrance/Arderial_North_SoutheastEntrance.metatile.tilemap.rle"