    db 42        ; wTilemap_Width
    dw $0690     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/north/southeastentrance/Arderial_North_SoutheastEntrance.collision.tilemap.rle"