    db 30        ;wTilemap_Width
    dw $010E     ;wTilemap_YMapPad
    db 19        ;
    db 30        ;wTilemap_VStop
    dw $04B0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/seers/hyren_seacave/Naroom_Seers_Hyren_SeaCave.metatile.tilemap.rle"