    db 30        ;wTilemap_Width
    dw $04B0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/seers/hyren_seacave/Naroom_Seers_Hyren_SeaCave.collision.tilemap.rle"