    db 24        ; wTilemap_Width
    dw $0240     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/geyser/northeast/Naroom_Geyser_Northeast.collision.tilemap.rle"