    db 11        ; wTilemap_Width
    dw $00C6     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/north_roomb/Naroom_Vash_North_RoomB.collision.tilemap.rle"