    db 26        ;wTilemap_Width
    dw $00EA     ;wTilemap_YMapPad
    db 15        ;
    db 10        ;wTilemap_VStop
    dw $0208     ;Uncompressed file size (excluding header)
    ;The imported file size was actually $020F because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/naroom/geyser/west/Naroom_Geyser_West.metatile.tilemap.rle"