    db 26        ;wTilemap_Width
    dw $0208     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/geyser/west/Naroom_Geyser_West.collision.tilemap.rle"