    db 64        ;wTilemap_Width
    dw $1000     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/geyser/puzzlesa/Cald_Geyser_PuzzlesA.collision.tilemap.rle"