    db 15        ;wTilemap_Width
    dw $0087     ;wTilemap_YMapPad
    db 4         ;
    db 10        ;wTilemap_VStop
    dw $012C     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/fortconnectioncacheroom/Underneath_Tunnels_FortConnectionCacheRoom.metatile.tilemap.rle"