    db 15        ; wTilemap_Width
    dw $012C     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/fortconnectioncacheroom/Underneath_Tunnels_FortConnectionCacheRoom.collision.tilemap.rle"