    db 30        ; wTilemap_Width
    dw $0258     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/deep_cache/Naroom_Forest_Deep_Cache.collision.tilemap.rle"