    db 32        ;wTilemap_Width
    dw $0320     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/geyser/east/Orothe_Geyser_East.collision.tilemap.rle"