    db 32        ; wTilemap_Width
    dw $0120     ; wTilemap_YMapPad
    db 21        ;
    db 15        ; wTilemap_VStop
    dw $0320     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/geyser/east/Orothe_Geyser_East.metatile.tilemap.rle"