    db 24        ;wTilemap_Width
    dw $0240     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/geyser/southwest/Naroom_Geyser_Southwest.collision.tilemap.rle"