    db 10        ; wTilemap_Width
    dw $0064     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/bogrom/ulkroom/Underneath_Bogrom_UlkRoom.collision.tilemap.rle"