    ; $4000
    BITMAP_Fightscene_Arena_UnderneathGeyserTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/UnderneathGeyser/UnderneathGeyserTop.tileset.rle"

    ; $42C6
BITMAP_Fightscene_Arena_UnderneathGeyserBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/UnderneathGeyser/UnderneathGeyserBottom.tileset.rle"

    ; $454F
BITMAP_Fightscene_Arena_OrotheStarfishTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheStarfish/OrotheStarfishTop.tileset.rle"

    ; $47EF
BITMAP_Fightscene_Arena_OrotheStarfishBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheStarfish/OrotheStarfishBottom.tileset.rle"

    ; $4AFB
BITMAP_Fightscene_Arena_OrotheGeyserTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheGeyser/OrotheGeyserTop.tileset.rle"

    ; $4D9B
BITMAP_Fightscene_Arena_OrotheGeyserBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheGeyser/OrotheGeyserBottom.tileset.rle"

    ; $4F86
BITMAP_Fightscene_Arena_OrotheTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Orothe/OrotheTop.tileset.rle"

    ; $51BD
BITMAP_Fightscene_Arena_OrotheBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Orothe/OrotheBottom.tileset.rle"

    ; $53C8
BITMAP_Fightscene_Arena_OrotheTunnelsTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheTunnels/OrotheTunnelsTop.tileset.rle"

    ; $5592
BITMAP_Fightscene_Arena_OrotheTunnelsBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/OrotheTunnels/OrotheTunnelsBottom.tileset.rle"

    ; $582B
BITMAP_Fightscene_Arena_ShadowholdTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Shadowhold/ShadowholdTop.tileset.rle"

    ; $5AD0
BITMAP_Fightscene_Arena_ShadowholdBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Shadowhold/ShadowholdBottom.tileset.rle"

    ; $5D0F
BITMAP_Fightscene_Arena_UnderneathTopRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Underneath/UnderneathTop.tileset.rle"

    ; $5F9B
BITMAP_Fightscene_Arena_UnderneathBottomRLE::
    INCBIN "autogenerated/assets/fightscene/arena/Underneath/UnderneathBottom.tileset.rle"