    db 50        ;wTilemap_Width
    dw $07D0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/north/Underneath_Mushroom_North.collision.tilemap.rle"