    db 30        ; wTilemap_Width
    dw $010E     ; wTilemap_YMapPad
    db 19        ;
    db 6         ; wTilemap_VStop
    dw $01E0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/dock/western_ferry/Orothe_Dock_Western_Ferry.metatile.tilemap.rle"