    db 30        ; wTilemap_Width
    dw $01E0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/dock/western_ferry/Orothe_Dock_Western_Ferry.collision.tilemap.rle"