    db 35        ; wTilemap_Width
    dw $013B     ; wTilemap_YMapPad
    db 24        ;
    db 32        ; wTilemap_VStop
    dw $05BE     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/overworld/arderial/Overworld_Arderial.metatile.tilemap.rle"