    db 32        ;wTilemap_Width
    dw $0400     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/geyser/west/Orothe_Geyser_West.collision.tilemap.rle"