    db 40        ;wTilemap_Width
    dw $04B0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/tunnels/intersectionexit/Cald_Tunnels_IntersectionExit.collision.tilemap.rle"