    db 60        ;wTilemap_Width
    dw $0BB8     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/bogrom/destroyed/Underneath_Bogrom_Destroyed.collision.tilemap.rle"