    db 40        ; wTilemap_Width
    dw $04B0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/tunnels/intersectionnorth/Cald_Tunnels_IntersectionNorth.collision.tilemap.rle"