    db 40        ;wTilemap_Width
    dw $0168     ;wTilemap_YMapPad
    db 29        ;
    db 20        ;wTilemap_VStop
    dw $04B0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/tunnels/intersectionnorth/Cald_Tunnels_IntersectionNorth.metatile.tilemap.rle"