import os, re


#This module deletes all the final assets used in the assembly of the ROM
#It will keep the original tileset.png, pal.png and RLEx.extension files

#It deletes
#   .tileset (2bpp)
#   .pal (list of Colors)
#   .extension.rle (run-length-encoded file)
#   .2bpp, .tmp

folders = ["autogenerated/assets",
#	"python/out/" #For tests
	]
    
    
    
delete_extensions = ["pal","tileset","rle","2bpp","tmp"]

#All regex is case-sensitive

for folder in folders:
    for header,dirs,files in os.walk(folder):
        for file in files:
            relpath = os.path.join(header,file)
            for exte in delete_extensions:
                if(re.match(r"^.*\.{}$".format(exte),file)):
                    os.remove(relpath)
                    print(relpath)
