    db 20        ; wTilemap_Width
    dw $0320     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/loop_pathwayloopwestcacheintersections/Underneath_Tunnels_Loop_PathwayLoopWestCacheIntersections.collision.tilemap.rle"