    db 15        ; wTilemap_Width
    dw $0087     ; wTilemap_YMapPad
    db 4         ;
    db 4         ; wTilemap_VStop
    dw $00D2     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/misc/teleport/unused3/Misc_Teleport_UNUSED3.metatile.tilemap.rle"