    db 30        ;wTilemap_Width
    dw $041A     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/weave/river/Naroom_Weave_River.collision.tilemap.rle"