    db 60        ;wTilemap_Width
    dw $0438     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/brokenbridge/Cald_Vents_BrokenBridge.collision.tilemap.rle"