    db 60        ;wTilemap_Width
    dw $021C     ;wTilemap_YMapPad
    db 49        ;
    db 8         ;wTilemap_VStop
    dw $0438     ;Uncompressed file size (excluding header)
    ;The imported file size was actually $043F because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/brokenbridge/Cald_Vents_BrokenBridge.metatile.tilemap.rle"