    db 64        ; wTilemap_Width
    dw $0500     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/middle/pathwayhouse/Arderial_Middle_PathwayHouse.collision.tilemap.rle"