    db 11        ; wTilemap_Width
    dw $00F2     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/palace/throneroom/Arderial_Palace_Throneroom.collision.tilemap.rle"