    db 18        ; wTilemap_Width
    dw $0120     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/glade/geyser/Naroom_Glade_Geyser.collision.tilemap.rle"