    db 18        ;wTilemap_Width
    dw $0384     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/grove/river/Naroom_Grove_River.collision.tilemap.rle"