    db 20        ; wTilemap_Width
    dw $03E8     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/exit/Cald_Caverns_Exit.collision.tilemap.rle"