    db 12        ; wTilemap_Width
    dw $0090     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/pathwayu_cacheroom_unused1/Cald_Caverns_PathwayU_CacheRoom_UNUSED1.collision.tilemap.rle"