    db 25        ;wTilemap_Width
    dw $0271     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/volcano_hyren/Cald_Volcano_Hyren.collision.tilemap.rle"