    db 24        ;wTilemap_Width
    dw $0240     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/remix_cald_west/Arderial_Geyser_Remix_Cald_West.collision.tilemap.rle"