    db 48        ;wTilemap_Width
    dw $01B0     ;wTilemap_YMapPad
    db 37        ;
    db 22        ;wTilemap_VStop
    dw $0600     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/middle/house/Arderial_Middle_House.metatile.tilemap.rle"