    db 48        ; wTilemap_Width
    dw $0600     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/middle/house/Arderial_Middle_House.collision.tilemap.rle"