    db 30        ;wTilemap_Width
    dw $0546     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/pathwayfort/Underneath_Tunnels_PathwayFort.collision.tilemap.rle"