    db 15        ;wTilemap_Width
    dw $01EF     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/topstairs/Naroom_Vash_TopStairs.collision.tilemap.rle"