    db 30        ; wTilemap_Width
    dw $010E     ; wTilemap_YMapPad
    db 19        ;
    db 15        ; wTilemap_VStop
    dw $02EE     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/house/Underneath_Mushroom_House.metatile.tilemap.rle"