    db 30        ;wTilemap_Width
    dw $02EE     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/house/Underneath_Mushroom_House.collision.tilemap.rle"