    db 25        ;wTilemap_Width
    dw $0271     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/garage/house/Underneath_Garage_House.collision.tilemap.rle"