    db 20        ;wTilemap_Width
    dw $00C8     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/northwest_historianroom/Naroom_Vash_Northwest_HistorianRoom.collision.tilemap.rle"