    db 32        ; wTilemap_Width
    dw $05E0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/geyser/northeast/Underneath_Geyser_Northeast.collision.tilemap.rle"