    db 20        ;wTilemap_Width
    dw $0320     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/coral/pathwayvertical/Orothe_Coral_PathwayVertical.collision.tilemap.rle"