    db 20        ; wTilemap_Width
    dw $0190     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/fort/groundfloorroom/Underneath_Fort_GroundFloorRoom.collision.tilemap.rle"