    db 20        ; wTilemap_Width
    dw $0190     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/shop/outside/Arderial_Shop_Outside.collision.tilemap.rle"