    db 40        ;wTilemap_Width
    dw $0320     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/loop_loopintersection/Underneath_Tunnels_Loop_LoopIntersection.collision.tilemap.rle"