    db 30        ;wTilemap_Width
    dw $0384     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/glade/guardentrance/Naroom_Glade_GuardEntrance.collision.tilemap.rle"