    db 60        ;wTilemap_Width
    dw $04B0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/north/northeast/Arderial_North_Northeast.collision.tilemap.rle"