    db 20        ; wTilemap_Width
    dw $00B4     ; wTilemap_YMapPad
    db 9         ;
    db 0         ; wTilemap_VStop
    dw $00C8     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/top_orwinroom_entrance/Naroom_Vash_Top_OrwinRoom_Entrance.metatile.tilemap.rle"