    db 16        ;wTilemap_Width
    dw $0090     ;wTilemap_YMapPad
    db 5         ;
    db 2         ;wTilemap_VStop
    dw $00C0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/windmill/room/Naroom_Windmill_Room.metatile.tilemap.rle"