    db 16        ; wTilemap_Width
    dw $00C0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/windmill/room/Naroom_Windmill_Room.collision.tilemap.rle"