    db 30        ; wTilemap_Width
    dw $0384     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/glade/ringroad/Naroom_Glade_RingRoad.collision.tilemap.rle"