    db 16        ;wTilemap_Width
    dw $0300     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/geyser/entrance/Orothe_Geyser_Entrance.collision.tilemap.rle"