    db 16        ;wTilemap_Width
    dw $0090     ;wTilemap_YMapPad
    db 5         ;
    db 38        ;wTilemap_VStop
    dw $0300     ;Uncompressed file size (excluding header)
    ;The imported file size was actually $0307 because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/orothe/geyser/entrance/Orothe_Geyser_Entrance.metatile.tilemap.rle"