    db 50        ;wTilemap_Width
    dw $01C2     ;wTilemap_YMapPad
    db 39        ;
    db 8         ;wTilemap_VStop
    dw $0384     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/pathwayentrancehorizontal/Cald_Caverns_PathwayEntranceHorizontal.metatile.tilemap.rle"