    db 50        ; wTilemap_Width
    dw $0384     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/pathwayentrancehorizontal/Cald_Caverns_PathwayEntranceHorizontal.collision.tilemap.rle"