    db 64        ; wTilemap_Width
    dw $0240     ; wTilemap_YMapPad
    db 53        ;
    db 6         ; wTilemap_VStop
    dw $0400     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/horizontalpipe_unused/Arderial_Geyser_HorizontalPipe_Unused.metatile.tilemap.rle"