    db 20        ;wTilemap_Width
    dw $0168     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/southeast_room/Naroom_Vash_Southeast_Room.collision.tilemap.rle"