    db 20        ; wTilemap_Width
    dw $012C     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/garage/room/Underneath_Garage_Room.collision.tilemap.rle"