    db 20        ; wTilemap_Width
    dw $00B4     ; wTilemap_YMapPad
    db 9         ;
    db 5         ; wTilemap_VStop
    dw $012C     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/garage/room/Underneath_Garage_Room.metatile.tilemap.rle"