    db 25        ; wTilemap_Width
    dw $0271     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/labyrinth_entrance/Core_Shadowhold_Labyrinth_Entrance.collision.tilemap.rle"