    db 50        ;wTilemap_Width
    dw $0A8C     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/middle/end/Arderial_Middle_End.collision.tilemap.rle"