    db 30        ; wTilemap_Width
    dw $0708     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/south/south/Arderial_South_South.collision.tilemap.rle"