    db 64        ;wTilemap_Width
    dw $0240     ;wTilemap_YMapPad
    db 53        ;
    db 30        ;wTilemap_VStop
    dw $0A00     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/palace/outside/Arderial_Palace_Outside.metatile.tilemap.rle"