    db 12        ;wTilemap_Width
    dw $0090     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/center_historianroom/Cald_Ashyn_Center_HistorianRoom.collision.tilemap.rle"