    db 64        ;wTilemap_Width
    dw $1000     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/south/north/Arderial_South_North.collision.tilemap.rle"