    db 24        ;wTilemap_Width
    dw $0210     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/geyser/northwest/Naroom_Geyser_Northwest.collision.tilemap.rle"