    db 24        ; wTilemap_Width
    dw $00D8     ; wTilemap_YMapPad
    db 13        ;
    db 12        ; wTilemap_VStop
    dw $0210     ; Uncompressed file size (excluding header)
    ; The imported file size was actually $0217 because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/naroom/geyser/northwest/Naroom_Geyser_Northwest.metatile.tilemap.rle"