
    ; Uncompressed card tilesets
    ; 51/51 used. No room for more but can be placed in any other bank.

    ; $4000
BITMAP_Card_TimberHyrn::
    INCBIN "autogenerated/assets/dreamcreatures/cards/TimberHyrn.tileset"
    ; $4140
BITMAP_Card_Cyclone_Vashp_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Cyclone_Vashp.tileset"
    ; $4280
BITMAP_Card_Vashp::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Vashp.tileset"
    ; $43C0
BITMAP_Card_Shryque::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Shryque.tileset"
    ; $4500
BITMAP_Card_ShadwVinoc::
    INCBIN "autogenerated/assets/dreamcreatures/cards/ShadwVinoc.tileset"
    ; $4640
BITMAP_Card_ThundrHyrn::
    INCBIN "autogenerated/assets/dreamcreatures/cards/ThundrHyrn.tileset"
    ; $4780
BITMAP_Card_Sphor::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Sphor.tileset"
    ; $48C0
BITMAP_Card_Stagadan_Variant_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Stagadan_Variant.tileset"
    ; $4A00
BITMAP_Card_Wudge_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Wudge.tileset"
    ; $4B40
BITMAP_Card_Wellisk_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Wellisk.tileset"
    ; $4C80
BITMAP_Card_Yvohcna::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Yvohcna.tileset"
    ; $4DC0
BITMAP_Card_Xyx::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Xyx.tileset"
    ; $4F00
BITMAP_Card_Vinoc::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Vinoc.tileset"
    ; $5040
BITMAP_Card_Vellup::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Vellup.tileset"
    ; $5180
BITMAP_Card_Weebo::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Weebo.tileset"
    ; $52C0
BITMAP_Card_Vrill_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Vrill.tileset"
    ; $5400
BITMAP_Card_Vulbor::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Vulbor.tileset"
    ; $5540
BITMAP_Card_Orish::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Orish.tileset"
    ; $5680
BITMAP_Card_Orathan_F::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Orathan_F.tileset"
    ; $57C0
BITMAP_Card_Orpus::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Orpus.tileset"
    ; $5900
BITMAP_Card_Ormagon::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Ormagon.tileset"
    ; $5A40
BITMAP_Card_Leaf_Hyren::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Leaf_Hyren.tileset"
    ; $5B80
BITMAP_Card_LavaBalmnt::
    INCBIN "autogenerated/assets/dreamcreatures/cards/LavaBalmnt.tileset"
    ; $5CC0
BITMAP_Card_Mush_Hyren::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Mush_Hyren.tileset"
    ; $5E00
BITMAP_Card_MagmaHyren::
    INCBIN "autogenerated/assets/dreamcreatures/cards/MagmaHyren.tileset"
    ; $5F40
BITMAP_Card_Megathan::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Megathan.tileset"
    ; $6080
BITMAP_Card_Raxis::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Raxis.tileset"
    ; $61C0
BITMAP_Card_Quor::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Quor.tileset"
    ; $6300
BITMAP_Card_ShadwKarak::
    INCBIN "autogenerated/assets/dreamcreatures/cards/ShadwKarak.tileset"
    ; $6440
BITMAP_Card_Rudwot::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Rudwot.tileset"
    ; $6580
BITMAP_Card_Sea_Barl_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Sea_Barl.tileset"
    ; $66C0
BITMAP_Card_Paralit::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Paralit.tileset"
    ; $6800
BITMAP_Card_Pack_Korrit_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Pack_Korrit.tileset"
    ; $6940
BITMAP_Card_Plith::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Plith.tileset"
    ; $6A80
BITMAP_Card_Parmalag::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Parmalag.tileset"
    ; $6BC0
BITMAP_Card_Platheus::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Platheus.tileset"
    ; $6D00
BITMAP_Card_Agovo::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Agovo.tileset"
    ; $6E40
BITMAP_Card_Carillion_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Carillion.tileset"
    ; $6F80
BITMAP_Card_Arbolit::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Arbolit.tileset"
    ; $70C0
BITMAP_Card_Alaban::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Alaban.tileset"
    ; $7200
BITMAP_Card_Fire_Chogo_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Fire_Chogo.tileset"
    ; $7340
BITMAP_Card_Yarothis_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Yarothis.tileset"
    ; $7480
BITMAP_Card_Cave_Hyren::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Cave_Hyren.tileset"
    ; $75C0
BITMAP_Card_Chaos_Jile::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Chaos_Jile.tileset"
    ; $7700
BITMAP_Card_CaveRudwot::
    INCBIN "autogenerated/assets/dreamcreatures/cards/CaveRudwot.tileset"
    ; $7840
BITMAP_Card_Bhatar::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Bhatar.tileset"
    ; $7980
BITMAP_Card_Bisiwog::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Bisiwog.tileset"
    ; $7AC0
BITMAP_Card_Arboll_Stalker_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Arboll_Stalker.tileset"
    ; $7C00
BITMAP_Card_Balamant_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Balamant.tileset"
    ; $7D40
BITMAP_Card_Ayebaw::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Ayebaw.tileset"
    ; $7E80
BITMAP_Card_Bwill::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Bwill.tileset"
    ; $7FC0