
    ; Uncompressed card tilesets
    ; 51/51 used. No room for more but can be placed in any other bank.

    ; $4000
BITMAP_Cardscene_LavaArboll::
    INCBIN "autogenerated/assets/dreamcreatures/cards/LavaArboll.tileset"
    ; $4140
BITMAP_Cardscene_Malevolent_Corf_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Malevolent_Corf.tileset"
    ; $4280
BITMAP_Cardscene_Lava_Aq::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Lava_Aq.tileset"
    ; $43C0
BITMAP_Cardscene_Fire_Grag_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Fire_Grag.tileset"
    ; $4500
BITMAP_Cardscene_Grax::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Grax.tileset"
    ; $4640
BITMAP_Cardscene_GiantKorit::
    INCBIN "autogenerated/assets/dreamcreatures/cards/GiantKorit.tileset"
    ; $4780
BITMAP_Cardscene_Husp_Unused::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Husp.tileset"
    ; $48C0
BITMAP_Cardscene_Koil::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Koil.tileset"
    ; $4A00
BITMAP_Cardscene_Gum_Gum::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Gum_Gum.tileset"
    ; $4B40
BITMAP_Cardscene_Kelthet::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Kelthet.tileset"
    ; $4C80
BITMAP_Cardscene_Karak::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Karak.tileset"
    ; $4DC0
BITMAP_Cardscene_Twee::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Twee.tileset"
    ; $4F00
BITMAP_Cardscene_Arboll::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Arboll.tileset"
    ; $5040
BITMAP_Cardscene_BlackAgovo::
    INCBIN "autogenerated/assets/dreamcreatures/cards/BlackAgovo.tileset"
    ; $5180
BITMAP_Cardscene_Brub::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Brub.tileset"
    ; $52C0
BITMAP_Cardscene_Bolt_Hyren::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Bolt_Hyren.tileset"
    ; $5400
BITMAP_Cardscene_DryteFiend::
    INCBIN "autogenerated/assets/dreamcreatures/cards/DryteFiend.tileset"
    ; $5540
BITMAP_Cardscene_Eebit::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Eebit.tileset"
    ; $5680
BITMAP_Cardscene_Drakan::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Drakan.tileset"
    ; $57C0
BITMAP_Cardscene_FlameHyren::
    INCBIN "autogenerated/assets/dreamcreatures/cards/FlameHyren.tileset"
    ; $5900
BITMAP_Cardscene_Furok::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Furok.tileset"
    ; $5A40
BITMAP_Cardscene_Epik::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Epik.tileset"
    ; $5B80
BITMAP_Cardscene_Empty::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Empty.tileset"
    ; $5CC0
BITMAP_Cardscene_Core_Hyren::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Core_Hyren.tileset"
    ; $5E00
BITMAP_Cardscene_Deep_Hyren::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Deep_Hyren.tileset"
    ; $5F40
BITMAP_Cardscene_CoralHyren::
    INCBIN "autogenerated/assets/dreamcreatures/cards/CoralHyren.tileset"
    ; $6080
BITMAP_Cardscene_Core_Grag::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Core_Grag.tileset"
    ; $61C0
BITMAP_Cardscene_Diobor::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Diobor.tileset"
    ; $6300
BITMAP_Cardscene_Abaquist::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Abaquist.tileset"
    ; $6440
BITMAP_Cardscene_DarkVellup::
    INCBIN "autogenerated/assets/dreamcreatures/cards/DarkVellup.tileset"
    ; $6580
BITMAP_Cardscene_Jingjack::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Jingjack.tileset"
    ; $66C0
BITMAP_Cardscene_Kazor::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Kazor.tileset"
    ; $6800
BITMAP_Cardscene_Kletch::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Kletch.tileset"
    ; $6940
BITMAP_Cardscene_Spindle::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Spindle.tileset"
    ; $6A80
BITMAP_Cardscene_Vile_Yogu::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Vile_Yogu.tileset"
    ; $6BC0
BITMAP_Cardscene_GhostBwisp::
    INCBIN "autogenerated/assets/dreamcreatures/cards/GhostBwisp.tileset"
    ; $6D00
BITMAP_Cardscene_Porkuslime::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Porkuslime.tileset"
    ; $6E40
BITMAP_Cardscene_Tusk_Bwisp::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Tusk_Bwisp.tileset"
    ; $6F80
BITMAP_Cardscene_Weebat::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Weebat.tileset"
    ; $70C0
BITMAP_Cardscene_Graw::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Graw.tileset"
    ; $7200
BITMAP_Cardscene_Sabreback::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Sabreback.tileset"
    ; $7340
BITMAP_Cardscene_Leaf_Chogo::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Leaf_Chogo.tileset"
    ; $7480
BITMAP_Cardscene_Rabbage::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Rabbage.tileset"
    ; $75C0
BITMAP_Cardscene_Treebit::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Treebit.tileset"
    ; $7700
BITMAP_Cardscene_Wasperine::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Wasperine.tileset"
    ; $7840
BITMAP_Cardscene_DarkAyebaw::
    INCBIN "autogenerated/assets/dreamcreatures/cards/DarkAyebaw.tileset"
    ; $7980
BITMAP_Cardscene_Sea_Jile::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Sea_Jile.tileset"
    ; $7AC0
BITMAP_Cardscene_Sharbloot::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Sharbloot.tileset"
    ; $7C00
BITMAP_Cardscene_Sarbil::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Sarbil.tileset"
    ; $7D40
BITMAP_Cardscene_Hook_Wing::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Hook_Wing.tileset"
    ; $7E80
BITMAP_Cardscene_Borgor::
    INCBIN "autogenerated/assets/dreamcreatures/cards/Borgor.tileset"
    ; $7FC0