    db 45        ; wTilemap_Width
    dw $0195     ; wTilemap_YMapPad
    db 34        ;
    db 40        ; wTilemap_VStop
    dw $08CA     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/pathwayhyrenfortintersections/Underneath_Tunnels_PathwayHyrenFortIntersections.metatile.tilemap.rle"