    db 45        ;wTilemap_Width
    dw $0465     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/entrance/Cald_Caverns_Entrance.collision.tilemap.rle"