    db 20        ;wTilemap_Width
    dw $00B4     ;wTilemap_YMapPad
    db 9         ;
    db 1         ;wTilemap_VStop
    dw $00DC     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/southwest/Naroom_Vash_Southwest.metatile.tilemap.rle"