    db 30        ; wTilemap_Width
    dw $010E     ; wTilemap_YMapPad
    db 19        ;
    db 50        ; wTilemap_VStop
    dw $0708     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/weave/ponds/Naroom_Weave_Ponds.metatile.tilemap.rle"