    db 30        ; wTilemap_Width
    dw $0708     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/weave/ponds/Naroom_Weave_Ponds.collision.tilemap.rle"