    db 20        ;wTilemap_Width
    dw $0320     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/tunnels/pathwayeast/Cald_Tunnels_PathwayEast.collision.tilemap.rle"