    db 16        ;wTilemap_Width
    dw $0090     ;wTilemap_YMapPad
    db 5         ;
    db 2         ;wTilemap_VStop
    dw $00C0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/center_erynroom/Cald_Ashyn_Center_ErynRoom.metatile.tilemap.rle"