    db 20        ;wTilemap_Width
    dw $0320     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/mouth/Underneath_Tunnels_Mouth.collision.tilemap.rle"