    db 12        ;wTilemap_Width
    dw $0090     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/puzzle_cacheroom/Naroom_Forest_Puzzle_CacheRoom.collision.tilemap.rle"