    db 16        ; wTilemap_Width
    dw $0090     ; wTilemap_YMapPad
    db 5         ;
    db 6         ; wTilemap_VStop
    dw $0100     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/center_ashgarroom/Cald_Ashyn_Center_AshgarRoom.metatile.tilemap.rle"