    db 64        ; wTilemap_Width
    dw $0C00     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/geyser/puzzlesb/Cald_Geyser_PuzzlesB.collision.tilemap.rle"