    db 20        ;wTilemap_Width
    dw $0258     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/misc/tavel/entrance/Misc_Tavel_Entrance.collision.tilemap.rle"