    db 12        ; wTilemap_Width
    dw $0090     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/easttunnel/intersection_blastroom/Underneath_EastTunnel_Intersection_BlastRoom.collision.tilemap.rle"