    db 40        ;wTilemap_Width
    dw $04B0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/weave/keymaze/Naroom_Weave_KeyMaze.collision.tilemap.rle"