    db 24        ;wTilemap_Width
    dw $00D8     ;wTilemap_YMapPad
    db 13        ;
    db 30        ;wTilemap_VStop
    dw $03C0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/middle_eastpathway_bigpuzzle/Core_Shadowhold_Middle_EastPathway_BigPuzzle.metatile.tilemap.rle"