    db 15        ;wTilemap_Width
    dw $00E1     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/hyren_intersectioncald/Underneath_Tunnels_Hyren_IntersectionCald.collision.tilemap.rle"