    db 24        ; wTilemap_Width
    dw $0240     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/palace/entranceroom/Arderial_Palace_EntranceRoom.collision.tilemap.rle"