    db 20        ;wTilemap_Width
    dw $0258     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/marina_start/Core_Shadowhold_Marina_Start.collision.tilemap.rle"