    db 40        ;wTilemap_Width
    dw $02D0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/pathwayexithorizontal/Cald_Caverns_PathwayExitHorizontal.collision.tilemap.rle"