    db 32        ; wTilemap_Width
    dw $0400     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/middle/entrance/Arderial_Middle_Entrance.collision.tilemap.rle"