    db 32        ; wTilemap_Width
    dw $0120     ; wTilemap_YMapPad
    db 21        ;
    db 22        ; wTilemap_VStop
    dw $0400     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/middle/entrance/Arderial_Middle_Entrance.metatile.tilemap.rle"