    db 12        ; wTilemap_Width
    dw $0090     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/puzzle_cacheroom_blastroom/Naroom_Forest_Puzzle_CacheRoom_BlastRoom.collision.tilemap.rle"