    db 16        ;wTilemap_Width
    dw $00E0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/east_rescueroom/Underneath_Mushroom_East_RescueRoom.collision.tilemap.rle"