    db 16        ; wTilemap_Width
    dw $0090     ; wTilemap_YMapPad
    db 5         ;
    db 4         ; wTilemap_VStop
    dw $00E0     ; Uncompressed file size (excluding header)
    ; The imported file size was actually $00E7 because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/east_rescueroom/Underneath_Mushroom_East_RescueRoom.metatile.tilemap.rle"