    db 14        ;wTilemap_Width
    dw $0348     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/bottomstairs/Naroom_Vash_BottomStairs.collision.tilemap.rle"