    db 15        ; wTilemap_Width
    dw $00D2     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/fort/teleportnaroom/Naroom_Vash_Sky_TeleportArderialRoom.collision.tilemap.rle"