    db 24        ; wTilemap_Width
    dw $0240     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/alcove/Orothe_Tunnels_Alcove.collision.tilemap.rle"