    db 30        ; wTilemap_Width
    dw $02EE     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/weave/entrance/Naroom_Weave_Entrance.collision.tilemap.rle"