    db 13        ;wTilemap_Width
    dw $00A9     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/west_smithroom/Cald_Ashyn_West_SmithRoom.collision.tilemap.rle"