    db 13        ; wTilemap_Width
    dw $0075     ; wTilemap_YMapPad
    db 2         ;
    db 3         ; wTilemap_VStop
    dw $00A9     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/west_smithroom/Cald_Ashyn_West_SmithRoom.metatile.tilemap.rle"