    db 20        ;wTilemap_Width
    dw $0258     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/loop_pathwayloopendeastcacheintersections/Underneath_Tunnels_Loop_PathwayLoopEndEastCacheIntersections.collision.tilemap.rle"