    db 16        ; wTilemap_Width
    dw $00A0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/north_rooma/Naroom_Vash_North_RoomA.collision.tilemap.rle"