    db 16        ; wTilemap_Width
    dw $0090     ; wTilemap_YMapPad
    db 5         ;
    db 0         ; wTilemap_VStop
    dw $00A0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/north_rooma/Naroom_Vash_North_RoomA.metatile.tilemap.rle"