ATTRTILE_Credits01RLE::
    INCBIN "autogenerated/assets/credits/Credits01.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits01.tilemap.rle"

    ; I'm not sure why the last two bytes from certain ATTRTILEmaps are duplicated - perhaps another compression bug? In any case, they aren't used
    IF GHOST_DATA == 1
        db $7E, $00
    ENDC

ATTRTILE_Credits02RLE::
    INCBIN "autogenerated/assets/credits/Credits02.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits02.tilemap.rle"

ATTRTILE_Credits03RLE::
    INCBIN "autogenerated/assets/credits/Credits03.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits03.tilemap.rle"

ATTRTILE_Credits04RLE::
    INCBIN "autogenerated/assets/credits/Credits04.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits04.tilemap.rle"

ATTRTILE_Credits05RLE::
    INCBIN "autogenerated/assets/credits/Credits05.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits05.tilemap.rle"

ATTRTILE_Credits06RLE::
    INCBIN "autogenerated/assets/credits/Credits06.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits06.tilemap.rle"

ATTRTILE_Credits07RLE::
    INCBIN "autogenerated/assets/credits/Credits07.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits07.tilemap.rle"

ATTRTILE_Credits08RLE::
    INCBIN "autogenerated/assets/credits/Credits08.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits08.tilemap.rle"

ATTRTILE_Credits09RLE::
    INCBIN "autogenerated/assets/credits/Credits09.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits09.tilemap.rle"

ATTRTILE_Credits10RLE::
    INCBIN "autogenerated/assets/credits/Credits10.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits10.tilemap.rle"

ATTRTILE_Credits11RLE::
    INCBIN "autogenerated/assets/credits/Credits11.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits11.tilemap.rle"

ATTRTILE_Credits12RLE::
    INCBIN "autogenerated/assets/credits/Credits12.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits12.tilemap.rle"

ATTRTILE_Credits13RLE::
    INCBIN "autogenerated/assets/credits/Credits13.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits13.tilemap.rle"

ATTRTILE_Credits14RLE::
    INCBIN "autogenerated/assets/credits/Credits14.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits14.tilemap.rle"

    ; I'm not sure why the last two bytes from certain ATTRTILEmaps are duplicated - perhaps another compression bug? In any case, they aren't used
    IF GHOST_DATA == 1
        db $7E, $00
    ENDC

ATTRTILE_Credits15RLE::
    INCBIN "autogenerated/assets/credits/Credits15.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits15.tilemap.rle"

ATTRTILE_Credits16RLE::
    INCBIN "autogenerated/assets/credits/Credits16.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits16.tilemap.rle"

ATTRTILE_Credits17RLE::
    INCBIN "autogenerated/assets/credits/Credits17.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits17.tilemap.rle"

ATTRTILE_Credits18RLE::
    INCBIN "autogenerated/assets/credits/Credits18.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits18.tilemap.rle"

    ; I'm not sure why the last two bytes from certain ATTRTILEmaps are duplicated - perhaps another compression bug? In any case, they aren't used
    IF GHOST_DATA == 1
        db $7E, $00
    ENDC

ATTRTILE_Credits19RLE::
    INCBIN "autogenerated/assets/credits/Credits19.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits19.tilemap.rle"

ATTRTILE_Credits20RLE::
    INCBIN "autogenerated/assets/credits/Credits20.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits20.tilemap.rle"

ATTRTILE_Credits21RLE::
    INCBIN "autogenerated/assets/credits/Credits21.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits21.tilemap.rle"

ATTRTILE_Credits22RLE::
    INCBIN "autogenerated/assets/credits/Credits22.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits22.tilemap.rle"

ATTRTILE_Credits23RLE::
    INCBIN "autogenerated/assets/credits/Credits23.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits23.tilemap.rle"

ATTRTILE_Credits24RLE::
    INCBIN "autogenerated/assets/credits/Credits24.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits24.tilemap.rle"

ATTRTILE_Credits25RLE::
    INCBIN "autogenerated/assets/credits/Credits25.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits25.tilemap.rle"

ATTRTILE_Credits26RLE::
    INCBIN "autogenerated/assets/credits/Credits26.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits26.tilemap.rle"

ATTRTILE_Credits27RLE::
    INCBIN "autogenerated/assets/credits/Credits27.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits27.tilemap.rle"

ATTRTILE_Credits28RLE::
    INCBIN "autogenerated/assets/credits/Credits28.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits28.tilemap.rle"

ATTRTILE_Credits29RLE::
    INCBIN "autogenerated/assets/credits/Credits29.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits29.tilemap.rle"

ATTRTILE_Credits30RLE::
    INCBIN "autogenerated/assets/credits/Credits30.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits30.tilemap.rle"

ATTRTILE_Credits31RLE::
    INCBIN "autogenerated/assets/credits/Credits31.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits31.tilemap.rle"

ATTRTILE_Credits32RLE::
    INCBIN "autogenerated/assets/credits/Credits32.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits32.tilemap.rle"

ATTRTILE_Credits33RLE::
    INCBIN "autogenerated/assets/credits/Credits33.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits33.tilemap.rle"

ATTRTILE_Credits34RLE::
    INCBIN "autogenerated/assets/credits/Credits34.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits34.tilemap.rle"

ATTRTILE_Credits35RLE::
    INCBIN "autogenerated/assets/credits/Credits35.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits35.tilemap.rle"

ATTRTILE_Credits36RLE::
    INCBIN "autogenerated/assets/credits/Credits36.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits36.tilemap.rle"

ATTRTILE_Credits37RLE::
    INCBIN "autogenerated/assets/credits/Credits37.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits37.tilemap.rle"

ATTRTILE_Credits38RLE::
    INCBIN "autogenerated/assets/credits/Credits38.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits38.tilemap.rle"

ATTRTILE_Credits39RLE::
    INCBIN "autogenerated/assets/credits/Credits39.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits39.tilemap.rle"

ATTRTILE_Credits40RLE::
    INCBIN "autogenerated/assets/credits/Credits40.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits40.tilemap.rle"

ATTRTILE_Credits41RLE::
    INCBIN "autogenerated/assets/credits/Credits41.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits41.tilemap.rle"

ATTRTILE_Credits42RLE::
    INCBIN "autogenerated/assets/credits/Credits42.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits42.tilemap.rle"

ATTRTILE_Credits43RLE::
    INCBIN "autogenerated/assets/credits/Credits43.attrmap.rle"
    INCBIN "autogenerated/assets/credits/Credits43.tilemap.rle"

BITSET_Credits::
    INCLUDE "assets/credits/Credits.bitmapset.asm"

PAL_Credits::
    INCBIN "autogenerated/assets/credits/Credits.pal"