
CARDSCENE_BLANKCARD EQU $F0

; Palettes $00 - $03 -> Card palettes
; $04 ?
CARDSCENE_PALETTE_BLANKCARD EQU $05
CARDSCENE_PALETTE_BACKGROUND EQU $06
CARDSCENE_PALETTE_TEXTBOX EQU $07


; VRAM tilemap positions of topleft corner of card

; Hero's cards
CARDSCENE_TILEMAP_CARD0 EQU BACKGROUND_COORD_07_00
CARDSCENE_TILEMAP_CARD1 EQU BACKGROUND_COORD_06_05
CARDSCENE_TILEMAP_CARD2 EQU BACKGROUND_COORD_06_0B
CARDSCENE_TILEMAP_CARD3 EQU BACKGROUND_COORD_07_10
; Enemy's cards
CARDSCENE_TILEMAP_CARD4 EQU BACKGROUND_COORD_00_00
CARDSCENE_TILEMAP_CARD5 EQU BACKGROUND_COORD_00_05
CARDSCENE_TILEMAP_CARD6 EQU BACKGROUND_COORD_00_0B
CARDSCENE_TILEMAP_CARD7 EQU BACKGROUND_COORD_00_10

    ; Bank 0
    VRAM_TILEID_SPRITE
    ; Tiles $00 - $FF defined in battle_equ.asm
    VRAM_TILEID_BG
    VRAM_TILEID CARDSCENE, ARENABACKGROUND, $00
    VRAM_TILEID CARDSCENE, CARD0, $30
    VRAM_TILEID CARDSCENE, CARD1, $44
    VRAM_TILEID CARDSCENE, CARD2, $58
    VRAM_TILEID CARDSCENE, CARD3, $6C
    ; Bank 1
    VRAM_TILEID_SPRITE
    ; Tiles $00 - $3F defined in battle_equ.asm
    ; Tiles $40 - $7F are undefined
    VRAM_TILEID_BG
    ; Tiles $80 - $85 defined in textbox
    ; Tiles $86 - $C6 defined in battle_equ.asm
    ; Tiles $C7 - $05 are undefined
    ; Tiles $06 - $0D defined in battle_equ.asm
    ; Tiles $0E - $2F are undefined
    VRAM_TILEID CARDSCENE, CARD4, $30
    VRAM_TILEID CARDSCENE, CARD5, $44
    VRAM_TILEID CARDSCENE, CARD6, $58
    VRAM_TILEID CARDSCENE, CARD7, $6C

CARDSCENE_BACKGROUND_ARENA EQU BACKGROUND_COORD_00_00
CARDSCENE_BACKGROUND_ARENA_END EQU BACKGROUND_COORD_0D_00
CARDSCENE_BACKGROUND_MENU EQU BACKGROUND_COORD_0D_00
CARDSCENE_BACKGROUND_MENU_END EQU BACKGROUND_COORD_12_00
CARDSCENE_WINDOW_MENU EQU WINDOW_COORD_00_00
CARDSCENE_WINDOW_MENU_END EQU WINDOW_COORD_05_00
