    db 64        ; wTilemap_Width
    dw $1000     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/end_glassmaze/Arderial_Geyser_End_GlassMaze.collision.tilemap.rle"