    db 50        ;wTilemap_Width
    dw $09C4     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/deep_heart/Naroom_Forest_Deep_Heart.collision.tilemap.rle"