    db 50        ;wTilemap_Width
    dw $09C4     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/ruins/blurry/Orothe_Ruins_Blurry.collision.tilemap.rle"