    db 24        ;wTilemap_Width
    dw $01E0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/whirlpool/Orothe_Tunnels_Whirlpool.collision.tilemap.rle"