    db 60        ; wTilemap_Width
    dw $04B0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/south/Underneath_Mushroom_South.collision.tilemap.rle"