    db 12        ; wTilemap_Width
    dw $0090     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/east_room/Cald_Ashyn_East_Room.collision.tilemap.rle"