    db 13        ;wTilemap_Width
    dw $015F     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/geyser/Underneath_Mushroom_Geyser.collision.tilemap.rle"