    db 24        ; wTilemap_Width
    dw $01E0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/inn/room/Arderial_Inn_Room.collision.tilemap.rle"