    db 14        ; wTilemap_Width
    dw $007E     ; wTilemap_YMapPad
    db 3         ;
    db 4         ; wTilemap_VStop
    dw $00C4     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/southeast_smithroom/Naroom_Vash_Southeast_SmithRoom.metatile.tilemap.rle"