    db 14        ;wTilemap_Width
    dw $00C4     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/southeast_smithroom/Naroom_Vash_Southeast_SmithRoom.collision.tilemap.rle"