    db 30        ; wTilemap_Width
    dw $05DC     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/intersectionhyren/Underneath_Tunnels_IntersectionHyren.collision.tilemap.rle"