    db 30        ; wTilemap_Width
    dw $0258     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/geyser/cavedin/Underneath_Geyser_CavedIn.collision.tilemap.rle"