    db 40        ; wTilemap_Width
    dw $04B0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/eastcache/Underneath_Tunnels_EastCache.collision.tilemap.rle"