    db 20        ; wTilemap_Width
    dw $0190     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/grukroom/Underneath_Mushroom_GrukRoom.collision.tilemap.rle"