    db 30        ; wTilemap_Width
    dw $0384     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/geyser/corestone_unused/Cald_Geyser_CoreStone.collision.tilemap.rle"