    db 19        ; wTilemap_Width
    dw $00AB     ; wTilemap_YMapPad
    db 8         ;
    db 10        ; wTilemap_VStop
    dw $017C     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/end/agram/Core_End_Agram.metatile.tilemap.rle"