    db 12        ; wTilemap_Width
    dw $00F0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/glade/pathway/Naroom_Glade_Pathway.collision.tilemap.rle"