    db 12        ; wTilemap_Width
    dw $006C     ; wTilemap_YMapPad
    db 1         ;
    db 10        ; wTilemap_VStop
    dw $00F0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/glade/pathway/Naroom_Glade_Pathway.metatile.tilemap.rle"