    db 20        ;wTilemap_Width
    dw $04B0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/entrance/Cald_Vents_Entrance.collision.tilemap.rle"