    db 12        ; wTilemap_Width
    dw $0078     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/misc/tavel/outside/Misc_Tavel_Outside.collision.tilemap.rle"