    db 12        ;wTilemap_Width
    dw $0090     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/cacheroomb/Cald_Vents_CacheRoomB.collision.tilemap.rle"