    db 50        ; wTilemap_Width
    dw $01C2     ; wTilemap_YMapPad
    db 39        ;
    db 15        ; wTilemap_VStop
    dw $04E2     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/labyrinth_north/Core_Shadowhold_Labyrinth_North.metatile.tilemap.rle"