    db 50        ; wTilemap_Width
    dw $04E2     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/labyrinth_north/Core_Shadowhold_Labyrinth_North.collision.tilemap.rle"