    db 25        ;wTilemap_Width
    dw $036B     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_firstpuzzle/Core_Shadowhold_Deep_FirstPuzzle.collision.tilemap.rle"