    db 25        ; wTilemap_Width
    dw $00E1     ; wTilemap_YMapPad
    db 14        ;
    db 25        ; wTilemap_VStop
    dw $036B     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_firstpuzzle/Core_Shadowhold_Deep_FirstPuzzle.metatile.tilemap.rle"