    db 30        ;wTilemap_Width
    dw $0384     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/westentrance/Underneath_Mushroom_WestEntrance.collision.tilemap.rle"