    db 70        ; wTilemap_Width
    dw $0276     ; wTilemap_YMapPad
    db 59        ;
    db 40        ; wTilemap_VStop
    dw $0DAC     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/coral/end/Orothe_Coral_End.metatile.tilemap.rle"