    db 54        ; wTilemap_Width
    dw $0546     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/glade/cave_entrance/Naroom_Glade_Cave_Entrance.collision.tilemap.rle"