    db 15        ;wTilemap_Width
    dw $02EE     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/grove/entrance/Naroom_Grove_Entrance.collision.tilemap.rle"