; Assets don't actually exist


SECTION "DUMMYPACKED", ROMX[$4000], BANK[$FF]

    ; $4000
COLLMAP_Arderial_Fort_UNUSED_DUMMY::
    INCLUDE "autogenerated/assets/scenes/scenes/arderial/fort/unused/_dummy.collision.asm"
