; These scenes are not actually used in the game, but are included here for preview purposes
; Contains mask metamaps, or unused assets
SCENE_Arderial_Buildings_Outside_BITSETPREVIEW::
    INCLUDE "autogenerated/assets/scenes/scenes/arderial/_unused_python_preview/_python_bitset_preview.scene.asm"
SCENE_Arderial_Fort_UNUSED::
    INCLUDE "autogenerated/assets/scenes/scenes/arderial/fort/unused/_python_metamap_preview.scene.asm"
SCENE_Arderial_Geyser_Pipes2_Entrance_Mask::
    INCLUDE "autogenerated/assets/scenes/scenes/arderial/geyser/pipes2_entrance/_python_mask_preview.scene.asm"
SCENE_Arderial_Geyser_Pipes2_PipeAnalysis_Mask::
    INCLUDE "autogenerated/assets/scenes/scenes/arderial/geyser/pipes2_pipeanalysis/_python_mask_preview.scene.asm"
SCENE_Cald_Ashyn_NorthGeyser_Mask::
    INCLUDE "autogenerated/assets/scenes/scenes/cald/ashyn/northgeyser/_python_mask_preview.scene.asm"
SCENE_Cald_Geyser_PuzzlesA_Mask::
    INCLUDE "autogenerated/assets/scenes/scenes/cald/geyser/puzzlesa/_python_mask_preview.scene.asm"
SCENE_Cald_Geyser_PuzzlesB_Mask::
    INCLUDE "autogenerated/assets/scenes/scenes/cald/geyser/puzzlesb/_python_mask_preview.scene.asm"
SCENE_Cald_Geyser_CoreStone_Mask::
    INCLUDE "autogenerated/assets/scenes/scenes/cald/geyser/corestone/_python_mask_preview.scene.asm"
SCENE_Misc_StartScreen_Main_Mask::
    INCLUDE "autogenerated/assets/scenes/scenes/misc/startscreen/main/_python_mask_preview.scene.asm"
SCENE_Naroom_Vash_Top_OrwinRoom_Observatory_PATTERNPREVIEW::
    INCLUDE "autogenerated/assets/scenes/scenes/naroom/vash/top_orwinroom_observatory/_python_unusedpattern_preview.scene.asm"
SCENE_Naroom_Forest_Exit_UNUSED1::
    INCLUDE "autogenerated/assets/scenes/scenes/naroom/forest/exit_unused1/_python_metatilemap_preview.scene.asm"
SCENE_Naroom_Forest_Exit_UNUSED2::
    INCLUDE "autogenerated/assets/scenes/scenes/naroom/forest/exit_unused2/_python_metatilemap_preview.scene.asm"