    db 24        ;wTilemap_Width
    dw $00D8     ;wTilemap_YMapPad
    db 13        ;
    db 7         ;wTilemap_VStop
    dw $0198     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/INDIRECT_Naroom_Vash_South_AgovoDoorMask.metatile.tilemap.rle"