    db 20        ; wTilemap_Width
    dw $00B4     ; wTilemap_YMapPad
    db 9         ;
    db 2         ; wTilemap_VStop
    dw $00F0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/INDIRECT_Naroom_Vash_Southeast_CurioDoorMask.metatile.tilemap.rle"