    db 30        ;wTilemap_Width
    dw $010E     ;wTilemap_YMapPad
    db 19        ;
    db 26        ;wTilemap_VStop
    dw $0438     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/INDIRECT_UNKNOWN_SUSPECTED_Arderial_Geyser_Pipes2_Entrance_Mask.metatile.tilemap.rle"