    db 17        ; wTilemap_Width
    dw $0099     ; wTilemap_YMapPad
    db 6         ;
    db 8         ; wTilemap_VStop
    dw $0132     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/southeast_curioroom/Naroom_Vash_Southeast_CurioRoom.metatile.tilemap.rle"