    db 17        ;wTilemap_Width
    dw $0132     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/southeast_curioroom/Naroom_Vash_Southeast_CurioRoom.collision.tilemap.rle"