    db 35        ;wTilemap_Width
    dw $041A     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_northpathway/Core_Shadowhold_Deep_NorthPathway.collision.tilemap.rle"