    db 35        ; wTilemap_Width
    dw $013B     ; wTilemap_YMapPad
    db 24        ;
    db 20        ; wTilemap_VStop
    dw $041A     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_northpathway/Core_Shadowhold_Deep_NorthPathway.metatile.tilemap.rle"