    db 80        ;wTilemap_Width
    dw $02D0     ;wTilemap_YMapPad
    db 69        ;
    db 6         ;wTilemap_VStop
    dw $0500     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/pathwayfortloopintersections_b_unused/Underneath_Tunnels_PathwayFortLoopIntersections_B_Unused.metatile.tilemap.rle"