    db 80        ; wTilemap_Width
    dw $0500     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/pathwayfortloopintersections_b_unused/Underneath_Tunnels_PathwayFortLoopIntersections_B_Unused.collision.tilemap.rle"