    db 28        ; wTilemap_Width
    dw $00FC     ;wTilemap_YMapPad
    db 17        ;
    db 30        ;wTilemap_VStop
    dw $0460     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/cache/Orothe_Tunnels_Cache.metatile.tilemap.rle"