    db 28        ;wTilemap_Width
    dw $0460     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/cache/Orothe_Tunnels_Cache.collision.tilemap.rle"