    db 30        ;wTilemap_Width
    dw $0438     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/pipes2_entrance/Arderial_Geyser_Pipes2_Entrance.collision.tilemap.rle"