    db 24        ; wTilemap_Width
    dw $0240     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/exit_cacheroom/Underneath_Tunnels_Exit_CacheRoom.collision.tilemap.rle"