    db 50        ;wTilemap_Width
    dw $05DC     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/pathwayisland/Cald_Vents_PathwayIsland.collision.tilemap.rle"