    db 50        ; wTilemap_Width
    dw $01C2     ; wTilemap_YMapPad
    db 39        ;
    db 20        ; wTilemap_VStop
    dw $05DC     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/pathwayisland/Cald_Vents_PathwayIsland.metatile.tilemap.rle"