    db 11        ; wTilemap_Width
    dw $00C6     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/northwest_trynroom/Naroom_Vash_Northwest_TrynRoom.collision.tilemap.rle"