    db 40        ; wTilemap_Width
    dw $0640     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/windmill/outside/Naroom_Windmill_Outside.collision.tilemap.rle"