    db 36        ; wTilemap_Width
    dw $0510     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/historian/outside/Arderial_Historian_Outside.collision.tilemap.rle"