    db 25        ; wTilemap_Width
    dw $02EE     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_intersection/Core_Shadowhold_Deep_Intersection.collision.tilemap.rle"