    db 14        ; wTilemap_Width
    dw $01F8     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/seers/pathway/Naroom_Seers_Pathway.collision.tilemap.rle"