    db 39        ;wTilemap_Width
    dw $046B     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/overworld/underneath/Overworld_Underneath.collision.tilemap.rle"