    db 10        ;wTilemap_Width
    dw $0096     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/bogrom/gogorroom/Underneath_Bogrom_GogorRoom.collision.tilemap.rle"