    db 60        ; wTilemap_Width
    dw $0708     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/pathwayb/Cald_Vents_PathwayB.collision.tilemap.rle"