    db 60        ; wTilemap_Width
    dw $021C     ; wTilemap_YMapPad
    db 49        ;
    db 20        ; wTilemap_VStop
    dw $0708     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/pathwayb/Cald_Vents_PathwayB.metatile.tilemap.rle"