    AddressBank PAL_Misc_StoneWalls
    AddressBank BITSET_Misc_StoneWalls
    AddressBank PATTERN_Misc_StoneWallsRLE
    AddressBank METAMAP_Underneath_Tunnels_Loop_PathwayLoopEndEastCacheIntersections_BlastRoom
    AddressBank COLLMAP_Underneath_Tunnels_Loop_PathwayLoopEndEastCacheIntersections_BlastRoom