    db 64        ;wTilemap_Width
    dw $1000     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/north/center/Arderial_North_Center.collision.tilemap.rle"