    db 24        ; wTilemap_Width
    dw $00D8     ; wTilemap_YMapPad
    db 13        ;
    db 40        ; wTilemap_VStop
    dw $04B0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/pathwayu_cacheroom/Cald_Caverns_PathwayU_CacheRoom.metatile.tilemap.rle"