    db 24        ;wTilemap_Width
    dw $04B0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/pathwayu_cacheroom/Cald_Caverns_PathwayU_CacheRoom.collision.tilemap.rle"