    db 14        ; wTilemap_Width
    dw $00E0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/top_orwinroom_observatory/Naroom_Vash_Top_OrwinRoom_Observatory.collision.tilemap.rle"