    db 20        ;wTilemap_Width
    dw $00B4     ;wTilemap_YMapPad
    db 9         ;
    db 34        ;wTilemap_VStop
    dw $0370     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_end/Core_Shadowhold_Deep_End.metatile.tilemap.rle"