    db 17        ;wTilemap_Width
    dw $01FE     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/grukroom_teleportcore/Underneath_Mushroom_GrukRoom_TeleportCore.collision.tilemap.rle"