    db 28        ;wTilemap_Width
    dw $0690     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/intersectioncache/Orothe_Tunnels_IntersectionCache.collision.tilemap.rle"