    db 28        ; wTilemap_Width
    dw $00FC     ;wTilemap_YMapPad
    db 17        ;
    db 50        ;wTilemap_VStop
    dw $0690     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/intersectioncache/Orothe_Tunnels_IntersectionCache.metatile.tilemap.rle"