    db 40        ;wTilemap_Width
    dw $0168     ;wTilemap_YMapPad
    db 29        ;
    db 30        ;wTilemap_VStop
    dw $0640     ;Uncompressed file size (excluding header)
    ;The imported file size was actually $0647 because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/underneath/geyser/corestone/Underneath_Geyser_CoreStone.metatile.tilemap.rle"