    db 40        ;wTilemap_Width
    dw $0640     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/geyser/corestone/Underneath_Geyser_CoreStone.collision.tilemap.rle"