    db 25        ;wTilemap_Width
    dw $02EE     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/training/Naroom_Vash_Training.collision.tilemap.rle"