    db 30        ;wTilemap_Width
    dw $0384     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/geyser/antechamber/Cald_Geyser_Antechamber.collision.tilemap.rle"