    db 20        ;wTilemap_Width
    dw $0190     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/bogrom/innroom/Underneath_Bogrom_InnRoom.collision.tilemap.rle"