    db 48        ; wTilemap_Width
    dw $0900     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/pipes2_glassfield/Arderial_Geyser_Pipes2_GlassField.collision.tilemap.rle"