    db 15        ;wTilemap_Width
    dw $0087     ;wTilemap_YMapPad
    db 4         ;
    db 20        ;wTilemap_VStop
    dw $01C2     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/smith/teleportunderneath/Core_Smith_TeleportUnderneath.metatile.tilemap.rle"