    db 15        ;wTilemap_Width
    dw $01C2     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/smith/teleportunderneath/Core_Smith_TeleportUnderneath.collision.tilemap.rle"