    db 27        ;wTilemap_Width
    dw $02D9     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/pipes1_entrance/Arderial_Geyser_Pipes1_Entrance.collision.tilemap.rle"