    db 20        ;wTilemap_Width
    dw $0320     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/tunnels/pathwaywest/Cald_Tunnels_PathwayWest.collision.tilemap.rle"