    db 20        ; wTilemap_Width
    dw $0190     ; Uncompressed file size (excluding header)
    ; The imported file size was actually $0193 because 3 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/orothe/geyser/southwest/Orothe_Geyser_Southwest_Mask.collision.tilemap.rle"