    db 24        ; wTilemap_Width
    dw $0240     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/remix_cald_east/Arderial_Geyser_Remix_Cald_East.collision.tilemap.rle"