    db 48        ; wTilemap_Width
    dw $01B0     ;wTilemap_YMapPad
    db 37        ;
    db 42        ;wTilemap_VStop
    dw $09C0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/pathwaymarb/Orothe_Tunnels_PathwayMarB.metatile.tilemap.rle"