SECTION "Sprites $0E", ROMX[$4000], BANK[$0E]

INCLUDE "autogenerated/assets/sprites/agram/agram.mgi.asm"
INCLUDE "autogenerated/assets/sprites/blu/blu.mgi.asm"
INCLUDE "autogenerated/assets/sprites/bluswim/bluswim.mgi.asm"
INCLUDE "autogenerated/assets/sprites/eidon/eidon.mgi.asm"
INCLUDE "autogenerated/assets/sprites/evu/evu.mgi.asm"
INCLUDE "autogenerated/assets/sprites/fossik/fossik.mgi.asm"
INCLUDE "autogenerated/assets/sprites/gia/gia.mgi.asm"
INCLUDE "autogenerated/assets/sprites/gogor/gogor.mgi.asm"
INCLUDE "autogenerated/assets/sprites/gruk/gruk.mgi.asm"
INCLUDE "autogenerated/assets/sprites/josh/josh.mgi.asm"    ; Kid01
INCLUDE "autogenerated/assets/sprites/sly/sly.mgi.asm"      ; Kid02
INCLUDE "autogenerated/assets/sprites/benny/benny.mgi.asm"  ; Kid03
INCLUDE "autogenerated/assets/sprites/korg/korg.mgi.asm"
INCLUDE "autogenerated/assets/sprites/korremar/korremar.mgi.asm"
INCLUDE "autogenerated/assets/sprites/logan/logan.mgi.asm"
INCLUDE "autogenerated/assets/sprites/zet/zet.mgi.asm"

SECTION "Sprites $0F", ROMX[$4000], BANK[$0F]

INCLUDE "autogenerated/assets/sprites/mobis/mobis.mgi.asm"
INCLUDE "autogenerated/assets/sprites/morag/morag.mgi.asm"
INCLUDE "autogenerated/assets/sprites/ogar/ogar.mgi.asm"
INCLUDE "autogenerated/assets/sprites/orlon/orlon.mgi.asm"
INCLUDE "autogenerated/assets/sprites/orwin/orwin.mgi.asm"
INCLUDE "autogenerated/assets/sprites/poad/poad.mgi.asm"
INCLUDE "autogenerated/assets/sprites/pruitt/pruitt.mgi.asm"
INCLUDE "autogenerated/assets/sprites/salafy/salafy.mgi.asm"
INCLUDE "autogenerated/assets/sprites/shimmer/shimmer.mgi.asm"
INCLUDE "autogenerated/assets/sprites/siradam/siradam.mgi.asm"
INCLUDE "autogenerated/assets/sprites/tryn/tryn.mgi.asm"
INCLUDE "autogenerated/assets/sprites/ulk/ulk.mgi.asm"
INCLUDE "autogenerated/assets/sprites/valkan/valkan.mgi.asm"
INCLUDE "autogenerated/assets/sprites/warrada/warrada.mgi.asm"
INCLUDE "autogenerated/assets/sprites/wence/wence.mgi.asm"
INCLUDE "autogenerated/assets/sprites/jaela/jaela.mgi.asm" ; Wyloce
INCLUDE "autogenerated/assets/sprites/yaki/yaki.mgi.asm"
INCLUDE "autogenerated/assets/sprites/youngman/youngman.mgi.asm"
INCLUDE "autogenerated/assets/sprites/bolt/bolt.mgi.asm"
INCLUDE "autogenerated/assets/sprites/bomb/bomb.mgi.asm"

SECTION "Sprites $10", ROMX[$4000], BANK[$10]

INCLUDE "autogenerated/assets/sprites/shadowmagi4/shadowmagi4.mgi.asm"
INCLUDE "autogenerated/assets/sprites/shadowmagi5/shadowmagi5.mgi.asm"
INCLUDE "autogenerated/assets/sprites/shadowmagi6/shadowmagi6.mgi.asm"
INCLUDE "autogenerated/assets/sprites/shadowmagi7/shadowmagi7.mgi.asm"
INCLUDE "autogenerated/assets/sprites/shadowmagi8/shadowmagi8.mgi.asm"
INCLUDE "autogenerated/assets/sprites/girl1/girl1.mgi.asm"
INCLUDE "autogenerated/assets/sprites/guard/guard.mgi.asm"
INCLUDE "autogenerated/assets/sprites/jellybeans/jellybeans.mgi.asm"
INCLUDE "autogenerated/assets/sprites/oldlady1/oldlady1.mgi.asm"
INCLUDE "autogenerated/assets/sprites/oldman1/oldman1.mgi.asm"
INCLUDE "autogenerated/assets/sprites/rock/rock.mgi.asm"
INCLUDE "autogenerated/assets/sprites/spark/spark.mgi.asm"
INCLUDE "autogenerated/assets/sprites/splash/splash.mgi.asm"
INCLUDE "autogenerated/assets/sprites/woman/woman.mgi.asm"
INCLUDE "autogenerated/assets/sprites/worveline/worveline.mgi.asm"
INCLUDE "autogenerated/assets/sprites/boy1/boy1.mgi.asm"
INCLUDE "autogenerated/assets/sprites/boy2/boy2.mgi.asm"
INCLUDE "autogenerated/assets/sprites/boy3/boy3.mgi.asm"
INCLUDE "autogenerated/assets/sprites/boy4/boy4.mgi.asm"
INCLUDE "autogenerated/assets/sprites/girl2/girl2.mgi.asm"
INCLUDE "autogenerated/assets/sprites/kaeryn/kaeryn.mgi.asm"
INCLUDE "autogenerated/assets/sprites/girl4/girl4.mgi.asm"
INCLUDE "autogenerated/assets/sprites/girl5/girl5.mgi.asm"
INCLUDE "autogenerated/assets/sprites/oldlady2/oldlady2.mgi.asm"
INCLUDE "autogenerated/assets/sprites/oldlady3/oldlady3.mgi.asm"
INCLUDE "autogenerated/assets/sprites/oldlady4/oldlady4.mgi.asm"
INCLUDE "autogenerated/assets/sprites/oldlady5/oldlady5.mgi.asm"

SECTION "Sprites $11", ROMX[$4000], BANK[$11]

INCLUDE "autogenerated/assets/sprites/lasadaring/lasadaring.mgi.asm"
INCLUDE "autogenerated/assets/sprites/magamring/magamring.mgi.asm"
INCLUDE "autogenerated/assets/sprites/man2/man2.mgi.asm"
INCLUDE "autogenerated/assets/sprites/man3/man3.mgi.asm"
INCLUDE "autogenerated/assets/sprites/man4/man4.mgi.asm"
INCLUDE "autogenerated/assets/sprites/man5/man5.mgi.asm"
INCLUDE "autogenerated/assets/sprites/objects/objects.mgi.asm"
INCLUDE "autogenerated/assets/sprites/effects/effects.mgi.asm"

SECTION "Sprites $20", ROMX[$4000], BANK[$20]

INCLUDE "autogenerated/assets/sprites/tony/tony.mgi.asm"
INCLUDE "autogenerated/assets/sprites/arderialguard/arderialguard.mgi.asm"
INCLUDE "autogenerated/assets/sprites/ora/ora.mgi.asm"
INCLUDE "autogenerated/assets/sprites/shadowmagi1/shadowmagi1.mgi.asm"
INCLUDE "autogenerated/assets/sprites/shadowmagi2/shadowmagi2.mgi.asm"
INCLUDE "autogenerated/assets/sprites/shadowmagi3/shadowmagi3.mgi.asm"
INCLUDE "autogenerated/assets/sprites/togoth/togoth.mgi.asm"

SECTION "Sprites $25", ROMX[$4000], BANK[$25]

INCLUDE "autogenerated/assets/sprites/blackagovo/blackagovo.mgi.asm"
INCLUDE "autogenerated/assets/sprites/furok/furok.mgi.asm"
INCLUDE "autogenerated/assets/sprites/lavaarboll/lavaarboll.mgi.asm"
INCLUDE "autogenerated/assets/sprites/seer/seer.mgi.asm"
INCLUDE "autogenerated/assets/sprites/oldman2/oldman2.mgi.asm"
INCLUDE "autogenerated/assets/sprites/oldman3/oldman3.mgi.asm"
INCLUDE "autogenerated/assets/sprites/oldman4/oldman4.mgi.asm"
INCLUDE "autogenerated/assets/sprites/oldman5/oldman5.mgi.asm"
INCLUDE "autogenerated/assets/sprites/arderialman1/arderialman1.mgi.asm"
INCLUDE "autogenerated/assets/sprites/arderialman2/arderialman2.mgi.asm"
INCLUDE "autogenerated/assets/sprites/arderialgirl/arderialgirl.mgi.asm"
; The second half of Bank $25 is unrelated assets

SECTION "Sprites $40", ROMX, BANK[$40]
; First $400 bytes has tilesets
INCLUDE "autogenerated/assets/sprites/battlefx/battlefx.mgi.asm"

SECTION "Sprites $41", ROMX, BANK[$41]
; First $900 bytes has tilesets
INCLUDE "autogenerated/assets/sprites/cardscenefx/cardscenefx.mgi.asm"
; A bit under $1000 of empty space here
