    db 20        ; wTilemap_Width
    dw $0258     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/exit/Naroom_Forest_Exit.collision.tilemap.rle"