import projutils.utils as utils
import projutils.color as color
import projutils.filereference as filereference
import projutils.config as config

rom = utils.Rom()
sym = utils.SymFile()
TABLE = utils.BankAddress(0x04, 0x40E8)

targets = [utils.BankAddress(0x04, rom.getWord(TABLE + i*2)) for i in range(4)]
sizes = [
    targets[1] - targets[0],
    targets[2] - targets[1],
    targets[3] - targets[2],
    TABLE - targets[3],
]
names = [
    'White',
    'Black',
    'Fire',
    'Ice',
]


references = [filereference.FileReference.create_from_address('PAL', rom, target, sym) for target in targets]

for reference, size, name in zip(references, sizes, names):
    reference.processed_path = 'autogenerated/assets/fightscene/effects/{}.pal'.format(name)
    reference.original_path = 'assets/fightscene/effects/{}.pal.png'.format(name)
    reference.label_name = 'PAL_Fightscene_Effect_' + name
    reference.load_contents_from_rom(size//2)
    reference.replace_rom_text()
    reference.contents.save_original_file(config.outdir + name + '.pal.png', True)
    print('    dw '+reference.label_name)

for reference in references:
    print(reference.label_name)
    for i in range(4):
        print(color.Color(*reference.contents.palette[i]))