import projutils.color as color
import projutils.tileset as tileset

FILES = [
    'Arderial',
    'Cald',
    'CaldGeyser',
    'Core',
    'Naroom',
    'NaroomGeyser',
    'Orothe',
    'OrotheGeyser',
    'OrotheStarfish',
    'OrotheTunnels',
    'Shadowhold',
    'Underneath',
    'UnderneathGeyser',
    'UnderneathTunnels',
]

AUTOGENERATED = 'autogenerated/'
BASEPATH = 'assets/fightscene/arena/'
PAL = '.pal'

for file in FILES:
    palette_top = color.Palette.init_from_processed_file(AUTOGENERATED + BASEPATH + file + '/' + file + PAL)
    palette_bot = color.Palette.init_from_processed_file(AUTOGENERATED + BASEPATH + file + '/' + file + PAL)
    palette_top.palette = palette_top.palette[0:4]
    palette_bot.palette = palette_bot.palette[4:8]
    bitmap_top = tileset.Bitmap.init_from_processed_file(AUTOGENERATED + BASEPATH + file + '/' + file + 'Top.tileset.rle', 0x10, 0x4)
    bitmap_bottom = tileset.Bitmap.init_from_processed_file(AUTOGENERATED + BASEPATH + file + '/' + file + 'Bottom.tileset.rle', 0x10, 0x4)
    bitmap_top.palette = palette_top
    bitmap_bottom.palette = palette_bot
    bitmap_top.save_original_file(BASEPATH + file + '/' + file +'Top.tileset.png')
    bitmap_bottom.save_original_file(BASEPATH + file + '/' + file +'Bottom.tileset.png')