import os
import projutils.colorize as colorize
import projutils.tileset as tileset
import projutils.color as color
import projutils.utils as u
import projutils.replace_rom_text as replace
import io 



files = [0x5F95, 0x5F95+0x104]
width = 0x14
height = 0x0D

rom = u.Rom()
for file in files:
    data = rom.getRawSection(u.BankAddress(0x43,file),width*height)
    with open("python/out/{:04X}.tilemap".format(file),"wb") as f:
        f.write(data)
    #replace.reset_files([0x03])
    #replace.replace_rom_text(u.BankAddress(0x03,file),u.BankAddress(0x03,file+width*height),"TILEMAP_Menu_{:04X}::".format(file),"    INCBIN \"autogenerated/assets/menu/tilemaps/{:04X}.tilemap\"".format(file))