
from dataclasses import dataclass
from projutils.utils import BankAddress, Rom, SymFile
import projutils.magireader as magireader
import projutils.config as config


rom = Rom()
sym = SymFile()


class MagiTable:

    ANIM_NAMES = [
        "Idle",
        "Taunt", # Tony just has a duplicate Focus animation it seems
        "Summon",
        "Victory",
        "Defeat",
        "Focus", # Tony exclusive
        "Choose", # Tony exclusive
    ]

    def __init__(self, row):
        self.animcount = 7 if row.row == 0 else 5  # Tony has 7 anims exceptionally
        self.name = row.name
        self.address: BankAddress = row.data

        if row.row == 9 or row.row == 10:
            # Skip Agram2 and Agram3
            return

        self.anims = [rom.getBankAddress(self.address + i*3, getobj=True) for i in range(self.animcount)]
        self.symbols = [self.getSymbol(i) for i in range(self.animcount)]
        self.updateSymFile()

        assert(self.anims[0] == min(self.anims))

    def __eq__(self, other):
        return self.address == other.address

    def __hash__(self):
        return self.address.getPos()

    def getOutput(self):
        return '    ; ${:04X}\nBattle_MagiAnim_{}::\n{}'.format(
                self.address.getAddress(),
                self.name,
                '\n'.join(['    dw ' + symbol for symbol in self.symbols])
            )

    def getSymbol(self, anim_i):
        return 'SCRIPT_ANIM_{}Battle_{}'.format(self.name, MagiTable.ANIM_NAMES[anim_i])

    def getAddress(self, anim_i):
        return self.anims[anim_i]

    def updateSymFile(self):
        # Don't run this twice
        for data in zip(self.anims, self.symbols):
            sym.addSymbol(data[0].getBank(), data[0].getAddress(), data[1])

    def __repr__(self):
        return self.getOutput()


class MainTable:

    @dataclass
    class Row:
        def __init__(self, i):
            self.row = i
            self.address = MainTable.TABLE_LOCATION + i*2
            self.data = BankAddress(MainTable.TABLE_LOCATION.getBank(), rom.getWord(self.address))
            self.name = rom.getString(MainTable.MAGI_NAMES_LOCATION + i*10, 10).strip()
            #if 8 <= i <= 10:  # Agram
            #    self.name += str(i - 7)
            if 11 <= i <= 18:  # ShadowMagi
                self.name += str(i - 10)

        def getOutput(self):
            return '    dw Battle_MagiAnim_' + self.name

    TABLE_LENGTH = 0x14
    TABLE_LOCATION = BankAddress(0x05, 0x5CF1)
    MAGI_NAMES_LOCATION = BankAddress(0x19E16)

    def __init__(self, rom):
        self.rows = [self.Row(i) for i in range(MainTable.TABLE_LENGTH)]

        self.magitables = set()
        for row in self.rows:
            self.magitables.add(MagiTable(row))
        self.magitables = sorted(self.magitables, key=lambda x : x.address)

    def getOutput(self):
        return (
            '    ; ${:04X}\nBattle_MagiAnim_Table::\n{}\n\n'.format(MainTable.TABLE_LOCATION.getAddress(), '\n'.join([row.getOutput() for row in self.rows])) +
            '\n\n'.join([magitable.getOutput() for magitable in self.magitables])
        )


sprite_anim_params = {}
sprite_anim_params[0x0E] = {
    'START': 0x4000,
    'END': 0x7FEF,
    'SPRITE': [
        (0x4000, 'Agram_FaceUNKNOWNDIAGONAL2'),
        (0x403D, 'Agram_FaceUNKNOWNDIAGONAL1'),
        (0x407A, 'Agram_WalkDown1'),
        (0x40B7, 'Agram_FaceDown'),
        (0x40F4, 'Agram_WalkDown2'),
        (0x4131, 'Agram_WalkUp1'),
        (0x416E, 'Agram_FaceUp'),
        (0x41AB, 'Agram_WalkUp2'),
        (0x41E8, 'Agram_WalkRight1'),
        (0x4211, 'Agram_FaceRight'),
        (0x423A, 'Agram_WalkRight2'),
        (0x4263, 'Agram_WalkLeft1'),
        (0x428C, 'Agram_FaceLeft'),
        (0x42B5, 'Agram_WalkLeft2'),
        (0x42DE, 'AgramBattle_Idle'),
        (0x431B, 'AgramBattle_Taunt1'),
        (0x4368, 'AgramBattle_Taunt2'),
        (0x43BD, 'AgramBattle_Taunt3'),
        (0x441A, 'AgramBattle_Taunt4'),
        (0x4477, 'AgramBattle_Taunt5'),
        (0x44D4, 'AgramBattle_Taunt6'),
        (0x4531, 'AgramBattle_Taunt7'),
        (0x458E, 'AgramBattle_HandsUp1'),
        (0x45DB, 'AgramBattle_HandsUp2'),
        (0x4628, 'AgramBattle_Victory'),
        (0x4675, 'AgramBattle_Defeat'),
        (0x46AA, 'AgramBattle_Summon1'),
        (0x46EF, 'AgramBattle_Summon2'),
        (0x4738, 'AgramBattle_Summon3'),

        (0x497D, 'Blu_FaceDownRight'),
        (0x4996, 'Blu_FaceDownLeft'),
        (0x49AF, 'Blu_FaceUpRight'),
        (0x49C8, 'Blu_FaceUpLeft'),
        (0x49E1, 'Blu_WalkDown1'),
        (0x49F6, 'Blu_FaceDown'),
        (0x4A0F, 'Blu_WalkDown2'),
        (0x4A24, 'Blu_WalkUp1'),
        (0x4A3D, 'Blu_FaceUp'),
        (0x4A56, 'Blu_WalkUp2'),
        (0x4A6F, 'Blu_WalkRight1'),
        (0x4A88, 'Blu_FaceRight'),
        (0x4AA1, 'Blu_WalkRight2'),
        (0x4ABA, 'Blu_WalkLeft1'),
        (0x4AD3, 'Blu_FaceLeft'),
        (0x4AEC, 'Blu_WalkLeft2'),

        (0x4C08, 'BluSwim_SwimDown1'),
        (0x4C19, 'BluSwim_SwimDown2'),
        (0x4C2A, 'BluSwim_SwimUp1'),
        (0x4C3B, 'BluSwim_SwimUp2'),
        (0x4C54, 'BluSwim_SwimRight1'),
        (0x4C65, 'BluSwim_SwimRight2'),
        (0x4C76, 'BluSwim_SwimLeft1'),
        (0x4C87, 'BluSwim_SwimLeft2'),
        (0x4C98, 'BluSwim_UNKNOWN1_1'),
        (0x4CB5, 'BluSwim_UNKNOWN1_2'),
        (0x4CD2, 'BluSwim_UNKNOWN1_3'),
        (0x4CEF, 'BluSwim_UNKNOWN2_1'),
        (0x4D0C, 'BluSwim_UNKNOWN2_2'),
        (0x4D29, 'BluSwim_UNKNOWN2_3'),
        (0x4D46, 'BluSwim_UNKNOWNDown_1'),
        (0x4D67, 'BluSwim_UNKNOWNDown_2'),
        (0x4D88, 'BluSwim_UNKNOWNDown_3'),
        
        (0x500D, 'Eidon_FaceDownRight'),
        (0x5026, 'Eidon_FaceDownLeft'),
        (0x503F, 'Eidon_FaceUpRight'),
        (0x5058, 'Eidon_FaceUpLeft'),
        (0x5071, 'Eidon_WalkDown1'),
        (0x5086, 'Eidon_FaceDown'),
        (0x509F, 'Eidon_WalkDown2'),
        (0x50B4, 'Eidon_WalkUp1'),
        (0x50CD, 'Eidon_FaceUp'),
        (0x50E6, 'Eidon_WalkUp2'),
        (0x50FF, 'Eidon_WalkRight1'),
        (0x5118, 'Eidon_FaceRight'),
        (0x5131, 'Eidon_WalkRight2'),
        (0x514A, 'Eidon_WalkLeft1'),
        (0x5163, 'Eidon_FaceLeft'),
        (0x517C, 'Eidon_WalkLeft2'),
        (0x5195, 'Eidon_Wave'),
        (0x51AE, 'Eidon_UNKNOWN'),

        (0x51BF, 'EidonWork_ChopRight1'),
        (0x51DC, 'EidonWork_ChopRight2'),
        (0x51FD, 'EidonWork_ChopRight3'),
        (0x521E, 'EidonWork_ChopLeft1'),
        (0x523B, 'EidonWork_ChopLeft2'),
        (0x525C, 'EidonWork_ChopLeft3'),
        (0x527D, 'EidonWork_UNKNOWN2_1'),
        (0x529A, 'EidonWork_UNKNOWN2_2'),
        (0x52B7, 'EidonWork_UNKNOWN1_1'),
        (0x52D4, 'EidonWork_UNKNOWN1_2'),
        (0x52F1, 'EidonWork_UNKNOWNDown_1'),
        (0x531A, 'EidonWork_UNKNOWNDown_2_FACEMAYBE'),
        (0x5347, 'EidonWork_UNKNOWNDown_3'),

        (0x5568, 'Evu_FaceDownRight'),
        (0x5581, 'Evu_FaceDownLeft'),
        (0x559A, 'Evu_FaceUpRight'),
        (0x55B3, 'Evu_FaceUpLeft'),
        (0x55CC, 'Evu_WalkDown1'),
        (0x55E5, 'Evu_FaceDown'),
        (0x55FE, 'Evu_WalkDown2'),
        (0x5617, 'Evu_WalkUp1'),
        (0x5630, 'Evu_FaceUp'),
        (0x5649, 'Evu_WalkUp2'),
        (0x5662, 'Evu_WalkRight'),
        (0x567B, 'Evu_FaceRight'),
        (0x5694, 'Evu_WalkLeft'),
        (0x56AD, 'Evu_FaceLeft'),
        
        (0x597D, 'Fossik_FaceDownRight'),
        (0x5996, 'Fossik_FaceDownLeft'),
        (0x59AF, 'Fossik_FaceUpRight'),
        (0x59C8, 'Fossik_FaceUpLeft'),
        (0x59E1, 'Fossik_WalkDown1'),
        (0x59FA, 'Fossik_FaceDown'),
        (0x5A13, 'Fossik_WalkDown2'),
        (0x5A2C, 'Fossik_WalkUp1'),
        (0x5A45, 'Fossik_FaceUp'),
        (0x5A5E, 'Fossik_WalkUp2'),
        (0x5A77, 'Fossik_WalkRight1'),
        (0x5A90, 'Fossik_FaceRight'),
        (0x5AA9, 'Fossik_WalkRight2'),
        (0x5AC2, 'Fossik_WalkLeft1'),
        (0x5ADB, 'Fossik_FaceLeft'),
        (0x5AF4, 'Fossik_WalkLeft2'),
        (0x5B0D, 'FossikRing_01'),
        (0x5B3E, 'FossikRing_02'),
        (0x5B6F, 'FossikRing_03'),
        (0x5BA0, 'FossikRing_04'),
        (0x5BD1, 'FossikRing_05'),
        (0x5C02, 'FossikRing_06'),
        (0x5C33, 'FossikRing_07'),
        (0x5C64, 'FossikRing_08'),
        (0x5C95, 'FossikRing_09'),
        (0x5CBE, 'FossikRing_10'),
        (0x5CE7, 'FossikRing_11'),
        (0x5D18, 'FossikRing_Idle'),
        
        (0x5EE6, 'Gia_FaceDownRight'),
        (0x5EFF, 'Gia_FaceDownLeft'),
        (0x5F18, 'Gia_FaceUpRight'),
        (0x5F29, 'Gia_FaceUpLeft'),
        (0x5F3A, 'Gia_WalkDown1'),
        (0x5F4F, 'Gia_FaceDown'),
        (0x5F68, 'Gia_WalkDown2'),
        (0x5F7D, 'Gia_WalkUp1'),
        (0x5F92, 'Gia_FaceUp'),
        (0x5FAB, 'Gia_WalkUp2'),
        (0x5FC0, 'Gia_WalkRight1'),
        (0x5FD5, 'Gia_FaceRight'),
        (0x5FEA, 'Gia_WalkRight2'),
        (0x5FFF, 'Gia_WalkLeft1'),
        (0x6014, 'Gia_FaceLeft'),
        (0x6029, 'Gia_WalkLeft2'),
        (0x603E, 'Gia_UNKNOWN'),
        
        (0x615C, 'Gogor_FaceDownRight'),
        (0x6175, 'Gogor_FaceDownLeft'),
        (0x618E, 'Gogor_FaceUpRight'),
        (0x61A7, 'Gogor_FaceUpLeft'),
        (0x61C0, 'Gogor_WalkDown1'),
        (0x61D9, 'Gogor_FaceDown'),
        (0x61F2, 'Gogor_WalkDown2'),
        (0x620B, 'Gogor_WalkUp1'),
        (0x6224, 'Gogor_FaceUp'),
        (0x623D, 'Gogor_WalkUp2'),
        (0x6256, 'Gogor_WalkRight1'),
        (0x626F, 'Gogor_FaceRight'),
        (0x6288, 'Gogor_WalkRight2'),
        (0x62A1, 'Gogor_WalkLeft1'),
        (0x62BA, 'Gogor_FaceLeft'),
        (0x62D3, 'Gogor_WalkLeft2'),
        (0x62EC, 'Gogor_PoseDownRight'),
        (0x6305, 'Gogor_PoseDownLeft'),
        (0x631E, 'Gogor_PoseUpRight'),
        (0x6337, 'Gogor_PoseUpLeft'),
        
        (0x647B, 'Gruk_FaceDownRight'),
        (0x6494, 'Gruk_FaceDownLeft'),
        (0x64AD, 'Gruk_FaceUpRight'),
        (0x64BE, 'Gruk_FaceUpLeft'),
        (0x64CF, 'Gruk_WalkDown1'),
        (0x64E4, 'Gruk_FaceDown'),
        (0x64FD, 'Gruk_WalkDown2'),
        (0x6512, 'Gruk_WalkUp1'),
        (0x652B, 'Gruk_FaceUp'),
        (0x6544, 'Gruk_WalkUp2'),
        (0x655D, 'Gruk_WalkRight1'),
        (0x6576, 'Gruk_FaceRight'),
        (0x6587, 'Gruk_WalkRight2'),
        (0x65A0, 'Gruk_WalkLeft1'),
        (0x65B9, 'Gruk_FaceLeft'),
        (0x65CA, 'Gruk_WalkLeft2'),
        
        (0x66E6, 'Josh_FaceDownRight'),
        (0x66FF, 'Josh_FaceDownLeft'),
        (0x6718, 'Josh_FaceUpRight'),
        (0x6731, 'Josh_FaceUpLeft'),
        (0x674A, 'Josh_WalkDown1'),
        (0x675F, 'Josh_FaceDown'),
        (0x6778, 'Josh_WalkDown2'),
        (0x678D, 'Josh_WalkUp1'),
        (0x67A6, 'Josh_FaceUp'),
        (0x67BF, 'Josh_WalkUp2'),
        (0x67D8, 'Josh_WalkRight1'),
        (0x67F1, 'Josh_FaceRight'),
        (0x6806, 'Josh_WalkRight2'),
        (0x681F, 'Josh_WalkLeft1'),
        (0x6838, 'Josh_FaceLeft'),
        (0x684D, 'Josh_WalkLeft2'),
        
        (0x6978, 'Sly_FaceDownRight'),
        (0x6991, 'Sly_FaceDownLeft'),
        (0x69AA, 'Sly_FaceUpRight'),
        (0x69C3, 'Sly_FaceUpLeft'),
        (0x69DC, 'Sly_WalkDown1'),
        (0x69F1, 'Sly_FaceDown'),
        (0x6A0A, 'Sly_WalkDown2'),
        (0x6A1F, 'Sly_WalkUp1'),
        (0x6A38, 'Sly_FaceUp'),
        (0x6A51, 'Sly_WalkUp2'),
        (0x6A6A, 'Sly_WalkRight1'),
        (0x6A83, 'Sly_FaceRight'),
        (0x6A98, 'Sly_WalkRight2'),
        (0x6AB1, 'Sly_WalkLeft1'),
        (0x6ACA, 'Sly_FaceLeft'),
        (0x6ADF, 'Sly_WalkLeft2'),
        
        (0x6C0A, 'Benny_FaceDownRight'),
        (0x6C23, 'Benny_FaceDownLeft'),
        (0x6C3C, 'Benny_FaceUpRight'),
        (0x6C55, 'Benny_FaceUpLeft'),
        (0x6C6E, 'Benny_WalkDown1'),
        (0x6C87, 'Benny_FaceDown'),
        (0x6CA0, 'Benny_WalkDown2'),
        (0x6CB9, 'Benny_WalkUp1'),
        (0x6CD2, 'Benny_FaceUp'),
        (0x6CEB, 'Benny_WalkUp2'),
        (0x6D04, 'Benny_WalkRight1'),
        (0x6D1D, 'Benny_FaceRight'),
        (0x6D36, 'Benny_WalkRight2'),
        (0x6D4F, 'Benny_WalkLeft1'),
        (0x6D68, 'Benny_FaceLeft'),
        (0x6D81, 'Benny_WalkLeft2'),
        
        (0x6E9D, 'Korg_FaceDownRight'),
        (0x6EB6, 'Korg_FaceDownLeft'),
        (0x6ECF, 'Korg_FaceUpRight'),
        (0x6EE8, 'Korg_FaceUpLeft'),
        (0x6F01, 'Korg_WalkDown1'),
        (0x6F16, 'Korg_FaceDown'),
        (0x6F2F, 'Korg_WalkDown2'),
        (0x6F44, 'Korg_WalkUp1'),
        (0x6F5D, 'Korg_FaceUp'),
        (0x6F76, 'Korg_WalkUp2'),
        (0x6F8F, 'Korg_WalkRight1'),
        (0x6FA8, 'Korg_FaceRight'),
        (0x6FBD, 'Korg_WalkRight2'),
        (0x6FD6, 'Korg_WalkLeft1'),
        (0x6FEF, 'Korg_FaceLeft'),
        (0x7004, 'Korg_WalkLeft2'),
        (0x701D, 'Korg_OuchRight'),
        (0x702E, 'Korg_OuchLeft'),
        (0x703F, 'KorgSwim_FloatRight1'),
        (0x7050, 'KorgSwim_FloatRight2'),
        (0x7061, 'KorgSwim_FloatLeft1'),
        (0x7072, 'KorgSwim_FloatLeft2'),
        (0x7083, 'KorgBattle_IdleDownRight'),
        (0x709C, 'KorgBattle_IdleDownLeft'),
        (0x70B5, 'KorgBattle_Victory'),
        (0x70CE, 'KorgBattle_Defeat'),
        (0x70E7, 'KorgBattle_Taunt1'),
        (0x7100, 'KorgBattle_Taunt4'),
        (0x713A, 'KorgBattle_Taunt2'),
        (0x711D, 'KorgBattle_Taunt3'),
        (0x7157, 'KorgBattle_Summon1'),
        (0x7170, 'KorgBattle_Summon2'),
        (0x718D, 'KorgBattle_Summon3'),
        (0x71AA, 'KorgBattle_IdleDown'),
        
        (0x738B, 'Korremar_FaceDownRight'),
        (0x73A4, 'Korremar_FaceDownLeft'),
        (0x73BD, 'Korremar_FaceUpRight'),
        (0x73D6, 'Korremar_FaceUpLeft'),
        (0x73EF, 'Korremar_WalkDown1'),
        (0x7404, 'Korremar_FaceDown'),
        (0x741D, 'Korremar_WalkDown2'),
        (0x7432, 'Korremar_WalkUp1'),
        (0x744B, 'Korremar_FaceUp'),
        (0x7464, 'Korremar_WalkUp2'),
        (0x747D, 'Korremar_WalkRight1'),
        (0x7496, 'Korremar_FaceRight'),
        (0x74AF, 'Korremar_WalkRight2'),
        (0x74C8, 'Korremar_WalkLeft1'),
        (0x74E1, 'Korremar_FaceLeft'),
        (0x74FA, 'Korremar_WalkLeft2'),
        (0x7513, 'KorremarBattle_IdleDownRight'),
        (0x752C, 'KorremarBattle_IdleDownLeft'),
        (0x7545, 'KorremarBattle_IdleDown'),
        (0x755E, 'KorremarBattle_Taunt1'),
        (0x7577, 'KorremarBattle_Taunt2'),
        (0x7590, 'KorremarBattle_Taunt3'),
        (0x75B1, 'KorremarBattle_Victory'),
        (0x75CA, 'KorremarBattle_Defeat'),
        (0x75EB, 'KorremarBattle_Summon1'),
        (0x7604, 'KorremarBattle_Summon2'),
        (0x7621, 'KorremarBattle_Summon3'),
        
        (0x77AD, 'Logan_FaceDownRight'),
        (0x77C6, 'Logan_FaceDownLeft'),
        (0x77DF, 'Logan_FaceUpRight'),
        (0x77F8, 'Logan_FaceUpLeft'),
        (0x7811, 'Logan_WalkDown1'),
        (0x782A, 'Logan_FaceDown'),
        (0x7843, 'Logan_WalkDown2'),
        (0x785C, 'Logan_WalkUp1'),
        (0x7875, 'Logan_FaceUp'),
        (0x788E, 'Logan_WalkUp2'),
        (0x78A7, 'Logan_WalkRight1'),
        (0x78C0, 'Logan_FaceRight'),
        (0x78D9, 'Logan_WalkRight2'),
        (0x78F2, 'Logan_WalkLeft1'),
        (0x790B, 'Logan_FaceLeft'),
        (0x7924, 'Logan_WalkLeft2'),
        
        (0x7A40, 'Zet_FaceDownRight'),
        (0x7A59, 'Zet_FaceDownLeft'),
        (0x7A72, 'Zet_FaceUpRight'),
        (0x7A8B, 'Zet_FaceUpLeft'),
        (0x7AA4, 'Zet_WalkDown1'),
        (0x7ABD, 'Zet_FaceDown'),
        (0x7AD6, 'Zet_WalkDown2'),
        (0x7AEF, 'Zet_WalkUp1'),
        (0x7B04, 'Zet_FaceUp'),
        (0x7B1D, 'Zet_WalkUp2'),
        (0x7B32, 'Zet_WalkRight1'),
        (0x7B4B, 'Zet_FaceRight'),
        (0x7B64, 'Zet_WalkRight2'),
        (0x7B7D, 'Zet_WalkLeft1'),
        (0x7B96, 'Zet_FaceLeft'),
        (0x7BAF, 'Zet_WalkLeft2'),
        (0x7BC8, 'Zet_BeatRight1'),
        (0x7BE9, 'Zet_BeatRight2'),
        (0x7C0A, 'Zet_BeatRight3'),
        (0x7C2B, 'Zet_BeatLeft1'),
        (0x7C4C, 'Zet_BeatLeft2'),
        (0x7C6D, 'Zet_BeatLeft3'),
        (0x7C8E, 'Zet_OuchLeft'),
        (0x7CA7, 'Zet_OuchRight'),
        (0x7CBC, 'ZetSwim_FloatRight1'),
        (0x7CCD, 'ZetSwim_FloatRight2'),
        (0x7CDE, 'ZetSwim_FloatLeft1'),
        (0x7CEF, 'ZetSwim_FloatLeft2'),
        (0x7D00, 'ZetBattle_IdleDown'),
        (0x7D19, 'ZetBattle_Taunt1'),
        (0x7D32, 'ZetBattle_Taunt2'),
        (0x7D4B, 'ZetBattle_IdleDownLeft'),
        (0x7D64, 'ZetBattle_IdleDownRight'),
        (0x7D7D, 'ZetBattle_Victory'),
        (0x7D96, 'ZetBattle_Defeat'),
        (0x7DAF, 'ZetBattle_Summon1'),
        (0x7DC8, 'ZetBattle_Summon2'),
        (0x7DE5, 'ZetBattle_Summon3'),
    ],
    'SCRIPT': [
        (0x4781, 'SCRIPT_ANIM_Agram_FaceDown'),
        (0x478B, 'SCRIPT_ANIM_Agram_FaceUp'),
        (0x4795, 'SCRIPT_ANIM_Agram_FaceLeft'),
        (0x479F, 'SCRIPT_ANIM_Agram_FaceRight'),
        (0x47A9, 'SCRIPT_ANIM_Agram_FaceUNKNOWNDIAGONAL1'),
        (0x47B3, 'SCRIPT_ANIM_Agram_FaceUNKNOWNDIAGONAL2'),
        (0x47BD, 'SCRIPT_ANIM_Agram_WalkUp'),
        (0x47CD, 'SCRIPT_ANIM_Agram_WalkDown'),
        (0x47DD, 'SCRIPT_ANIM_Agram_WalkRight'),
        (0x47ED, 'SCRIPT_ANIM_Agram_WalkLeft'),
        (0x481D, '.Loop'),
        (0x4868, '.Loop'),
        (0x487E, 'SCRIPT_ANIM_AgramBattle_Anguish'),
        (0x488A, '.Loop'),
        (0x4894, 'SCRIPT_ANIM_AgramBattle_FadeOut'),
        
        (0x4B05, 'SCRIPT_ANIM_Blu_WalkUp'),
        (0x4B15, 'SCRIPT_ANIM_Blu_WalkDown'),
        (0x4B25, 'SCRIPT_ANIM_Blu_WalkLeft'),
        (0x4B35, 'SCRIPT_ANIM_Blu_WalkRight'),
        (0x4B45, 'SCRIPT_ANIM_Blu_RunUp'),
        (0x4B55, 'SCRIPT_ANIM_Blu_RunDown'),
        (0x4B65, 'SCRIPT_ANIM_Blu_RunLeft'),
        (0x4B75, 'SCRIPT_ANIM_Blu_RunRight'),
        (0x4B85, 'SCRIPT_ANIM_Blu_FaceUp'),
        (0x4B8F, 'SCRIPT_ANIM_Blu_FaceDown'),
        (0x4B99, 'SCRIPT_ANIM_Blu_FaceLeft'),
        (0x4BA3, 'SCRIPT_ANIM_Blu_FaceRight'),
        (0x4BAD, 'SCRIPT_ANIM_Blu_FaceUpLeft'),
        (0x4BB7, 'SCRIPT_ANIM_Blu_FaceUpRight'),
        (0x4BC1, 'SCRIPT_ANIM_Blu_FaceDownLeft'),
        (0x4BCB, 'SCRIPT_ANIM_Blu_FaceDownRight'),
        (0x4BD5, 'SCRIPT_ANIM_Blu_FaceHero'),
        (0x4BEC, '.FaceUp'),
        (0x4BF3, '.FaceDown'),
        (0x4BFA, '.FaceLeft'),
        (0x4C01, '.FaceRight'),

        (0x4DA9, 'SCRIPT_ANIM_BluSwim_FloatUp'),
        (0x4DB5, 'SCRIPT_ANIM_BluSwim_FloatDown'),
        (0x4DC1, 'SCRIPT_ANIM_BluSwim_FloatRight'),
        (0x4DCD, 'SCRIPT_ANIM_BluSwim_FloatLeft'),
        (0x4DD9, 'SCRIPT_ANIM_BluSwim_SwimUp'),
        (0x4E56, 'SCRIPT_ANIM_BluSwim_SwimDown'),
        (0x4ED3, 'SCRIPT_ANIM_BluSwim_SwimLeft'),
        (0x4F50, 'SCRIPT_ANIM_BluSwim_SwimRight'),
        (0x4FCD, 'SCRIPT_ANIM_BluSwim_UNKNOWNLeft'),
        (0x4FD5, 'SCRIPT_ANIM_BluSwim_UNKNOWNRight'),
        (0x4FDD, 'SCRIPT_ANIM_BluSwim_UNKNOWN1'),
        (0x4FED, 'SCRIPT_ANIM_BluSwim_UNKNOWN2'),
        (0x4FFD, 'SCRIPT_ANIM_BluSwim_UNKNOWNDown'),
        
        (0x5370, 'SCRIPT_ANIM_Eidon_WalkUp'),
        (0x5380, 'SCRIPT_ANIM_Eidon_WalkDown'),
        (0x5390, 'SCRIPT_ANIM_Eidon_WalkLeft'),
        (0x53A0, 'SCRIPT_ANIM_Eidon_WalkRight'),
        (0x53B0, 'SCRIPT_ANIM_Eidon_RunUp'),
        (0x53C0, 'SCRIPT_ANIM_Eidon_RunDown'),
        (0x53D0, 'SCRIPT_ANIM_Eidon_RunLeft'),
        (0x53E0, 'SCRIPT_ANIM_Eidon_RunRight'),
        (0x53F0, 'SCRIPT_ANIM_Eidon_FaceUp'),
        (0x53FA, 'SCRIPT_ANIM_Eidon_FaceDown'),
        (0x5404, 'SCRIPT_ANIM_Eidon_FaceLeft'),
        (0x540E, 'SCRIPT_ANIM_Eidon_FaceRight'),
        (0x5418, 'SCRIPT_ANIM_Eidon_FaceUpLeft'),
        (0x5422, 'SCRIPT_ANIM_Eidon_FaceUpRight'),
        (0x542C, 'SCRIPT_ANIM_Eidon_FaceDownLeft'),
        (0x5436, 'SCRIPT_ANIM_Eidon_FaceDownRight'),
        (0x5440, 'SCRIPT_ANIM_Eidon_UNKNOWN'),
        (0x544A, 'SCRIPT_ANIM_Eidon_Wave'),
        (0x5454, 'SCRIPT_ANIM_Eidon_Charades'),
        (0x54A9, 'SCRIPT_ANIM_EidonWork_ChopRight'),
        (0x54BD, 'SCRIPT_ANIM_EidonWork_ChopLeft'),
        (0x54D1, 'SCRIPT_ANIM_EidonWork_UNKNOWNChopLeft'),
        (0x54DB, 'SCRIPT_ANIM_EidonWork_ChopChopRight'),
        (0x54EA, 'SCRIPT_ANIM_EidonWork_ChopChopLeft'),
        (0x54F9, 'SCRIPT_ANIM_EidonWork_UNKNOWN1'),
        (0x5500, '.Loop'),
        (0x550A, 'SCRIPT_ANIM_EidonWork_UNKNOWN2'),
        (0x5511, '.Loop'),
        (0x551B, 'SCRIPT_ANIM_EidonWork_UNKNOWNDown1'),
        (0x552B, 'SCRIPT_ANIM_EidonWork_UNKNOWNDown2'),
        (0x5535, 'SCRIPT_ANIM_Eidon_FaceHero'),
        (0x554C, '.FaceUp'),
        (0x5553, '.FaceDown'),
        (0x555A, '.FaceLeft'),
        (0x5561, '.FaceRight'),
        
        (0x56C6, 'SCRIPT_ANIM_Evu_WalkUp'),
        (0x576B, 'SCRIPT_ANIM_Evu_WalkDown'),
        (0x5810, 'SCRIPT_ANIM_Evu_WalkLeft'),
        (0x5865, 'SCRIPT_ANIM_Evu_WalkRight'),
        (0x58BA, 'SCRIPT_ANIM_Evu_RunUp'),
        (0x58CA, 'SCRIPT_ANIM_Evu_RunDown'),
        (0x58DA, 'SCRIPT_ANIM_Evu_RunLeft'),
        (0x58EA, 'SCRIPT_ANIM_Evu_RunRight'),
        (0x58FA, 'SCRIPT_ANIM_Evu_FaceUp'),
        (0x5904, 'SCRIPT_ANIM_Evu_FaceDown'),
        (0x590E, 'SCRIPT_ANIM_Evu_FaceLeft'),
        (0x5918, 'SCRIPT_ANIM_Evu_FaceRight'),
        (0x5922, 'SCRIPT_ANIM_Evu_FaceUpLeft'),
        (0x592C, 'SCRIPT_ANIM_Evu_FaceUpRight'),
        (0x5936, 'SCRIPT_ANIM_Evu_FaceDownLeft'),
        (0x5940, 'SCRIPT_ANIM_Evu_FaceDownRight'),
        (0x594A, 'SCRIPT_ANIM_Evu_FaceHero'),
        (0x5961, '.FaceUp'),
        (0x5968, '.FaceDown'),
        (0x596F, '.FaceLeft'),
        (0x5976, '.FaceRight'),
        
        (0x5D49, 'SCRIPT_ANIM_Fossik_WalkUp'),
        (0x5D59, 'SCRIPT_ANIM_Fossik_WalkDown'),
        (0x5D69, 'SCRIPT_ANIM_Fossik_WalkLeft'),
        (0x5D79, 'SCRIPT_ANIM_Fossik_WalkRight'),
        (0x5D89, 'SCRIPT_ANIM_Fossik_RunUp'),
        (0x5D99, 'SCRIPT_ANIM_Fossik_RunDown'),
        (0x5DA9, 'SCRIPT_ANIM_Fossik_RunLeft'),
        (0x5DB9, 'SCRIPT_ANIM_Fossik_RunRight'),
        (0x5DC9, 'SCRIPT_ANIM_Fossik_FaceUp'),
        (0x5DD3, 'SCRIPT_ANIM_Fossik_FaceDown'),
        (0x5DDD, 'SCRIPT_ANIM_Fossik_FaceLeft'),
        (0x5DE7, 'SCRIPT_ANIM_Fossik_FaceRight'),
        (0x5DF1, 'SCRIPT_ANIM_Fossik_FaceUpLeft'),
        (0x5DFB, 'SCRIPT_ANIM_Fossik_FaceUpRight'),
        (0x5E05, 'SCRIPT_ANIM_Fossik_FaceDownLeft'),
        (0x5E0F, 'SCRIPT_ANIM_Fossik_FaceDownRight'),
        (0x5E19, 'SCRIPT_ANIM_FossikRing_MakeRing'),
        (0x5E9D, '.Loop'),
        (0x5EA8, 'SCRIPT_ANIM_FossikRing_Idle'),
        (0x5EB3, 'SCRIPT_ANIM_Fossik_FaceHero'),
        (0x5ECA, '.FaceUp'),
        (0x5ED1, '.FaceDown'),
        (0x5ED8, '.FaceLeft'),
        (0x5EDF, '.FaceRight'),
        
        (0x604F, 'SCRIPT_ANIM_Gia_WalkUp'),
        (0x605F, 'SCRIPT_ANIM_Gia_WalkDown'),
        (0x606F, 'SCRIPT_ANIM_Gia_WalkLeft'),
        (0x607F, 'SCRIPT_ANIM_Gia_WalkRight'),
        (0x608F, 'SCRIPT_ANIM_Gia_RunUp'),
        (0x609F, 'SCRIPT_ANIM_Gia_RunDown'),
        (0x60AF, 'SCRIPT_ANIM_Gia_RunLeft'),
        (0x60BF, 'SCRIPT_ANIM_Gia_RunRight'),
        (0x60CF, 'SCRIPT_ANIM_Gia_FaceUp'),
        (0x60D9, 'SCRIPT_ANIM_Gia_FaceDown'),
        (0x60E3, 'SCRIPT_ANIM_Gia_FaceLeft'),
        (0x60ED, 'SCRIPT_ANIM_Gia_FaceRight'),
        (0x60F7, 'SCRIPT_ANIM_Gia_FaceUpLeft'),
        (0x6101, 'SCRIPT_ANIM_Gia_FaceUpRight'),
        (0x610B, 'SCRIPT_ANIM_Gia_FaceDownLeft'),
        (0x6115, 'SCRIPT_ANIM_Gia_FaceDownRight'),
        (0x611F, 'SCRIPT_ANIM_Gia_UNKNOWN'),
        (0x6129, 'SCRIPT_ANIM_Gia_FaceHero'),
        (0x6140, '.FaceUp'),
        (0x6147, '.FaceDown'),
        (0x614E, '.FaceLeft'),
        (0x6155, '.FaceRight'),
        
        (0x6350, 'SCRIPT_ANIM_Gogor_WalkUp'),
        (0x6360, 'SCRIPT_ANIM_Gogor_WalkDown'),
        (0x6370, 'SCRIPT_ANIM_Gogor_WalkLeft'),
        (0x6380, 'SCRIPT_ANIM_Gogor_WalkRight'),
        (0x6390, 'SCRIPT_ANIM_Gogor_RunUp'),
        (0x63A0, 'SCRIPT_ANIM_Gogor_RunDown'),
        (0x63B0, 'SCRIPT_ANIM_Gogor_RunLeft'),
        (0x63C0, 'SCRIPT_ANIM_Gogor_RunRight'),
        (0x63D0, 'SCRIPT_ANIM_Gogor_FaceUp'),
        (0x63DA, 'SCRIPT_ANIM_Gogor_FaceDown'),
        (0x63E4, 'SCRIPT_ANIM_Gogor_FaceLeft'),
        (0x63EE, 'SCRIPT_ANIM_Gogor_FaceRight'),
        (0x63F8, 'SCRIPT_ANIM_Gogor_FaceUpLeft'),
        (0x6402, 'SCRIPT_ANIM_Gogor_FaceUpRight'),
        (0x640C, 'SCRIPT_ANIM_Gogor_FaceDownLeft'),
        (0x6416, 'SCRIPT_ANIM_Gogor_FaceDownRight'),
        (0x6420, 'SCRIPT_ANIM_Gogor_PoseUpLeft'),
        (0x642A, 'SCRIPT_ANIM_Gogor_PoseUpRight'),
        (0x6434, 'SCRIPT_ANIM_Gogor_PoseDownLeft'),
        (0x643E, 'SCRIPT_ANIM_Gogor_PoseDownRight'),
        (0x6448, 'SCRIPT_ANIM_Gogor_FaceHero'),
        (0x645F, '.FaceUp'),
        (0x6466, '.FaceDown'),
        (0x646D, '.FaceLeft'),
        (0x6474, '.FaceRight'),
        
        (0x65E3, 'SCRIPT_ANIM_Gruk_WalkUp'),
        (0x65F3, 'SCRIPT_ANIM_Gruk_WalkDown'),
        (0x6603, 'SCRIPT_ANIM_Gruk_WalkLeft'),
        (0x6613, 'SCRIPT_ANIM_Gruk_WalkRight'),
        (0x6623, 'SCRIPT_ANIM_Gruk_RunUp'),
        (0x6633, 'SCRIPT_ANIM_Gruk_RunDown'),
        (0x6643, 'SCRIPT_ANIM_Gruk_RunLeft'),
        (0x6653, 'SCRIPT_ANIM_Gruk_RunRight'),
        (0x6663, 'SCRIPT_ANIM_Gruk_FaceUp'),
        (0x666D, 'SCRIPT_ANIM_Gruk_FaceDown'),
        (0x6677, 'SCRIPT_ANIM_Gruk_FaceLeft'),
        (0x6681, 'SCRIPT_ANIM_Gruk_FaceRight'),
        (0x668B, 'SCRIPT_ANIM_Gruk_FaceUpLeft'),
        (0x6695, 'SCRIPT_ANIM_Gruk_FaceUpRight'),
        (0x669F, 'SCRIPT_ANIM_Gruk_FaceDownLeft'),
        (0x66A9, 'SCRIPT_ANIM_Gruk_FaceDownRight'),
        (0x66B3, 'SCRIPT_ANIM_Gruk_FaceHero'),
        (0x66CA, '.FaceUp'),
        (0x66D1, '.FaceDown'),
        (0x66D8, '.FaceLeft'),
        (0x66DF, '.FaceRight'),
        
        (0x6866, 'SCRIPT_ANIM_Josh_WalkUp'),
        (0x6876, 'SCRIPT_ANIM_Josh_WalkDown'),
        (0x6886, 'SCRIPT_ANIM_Josh_WalkLeft'),
        (0x6896, 'SCRIPT_ANIM_Josh_WalkRight'),
        (0x68A6, 'SCRIPT_ANIM_Josh_RunUp'),
        (0x68B6, 'SCRIPT_ANIM_Josh_RunDown'),
        (0x68C6, 'SCRIPT_ANIM_Josh_RunLeft'),
        (0x68D6, 'SCRIPT_ANIM_Josh_RunRight'),
        (0x68E6, 'SCRIPT_ANIM_Josh_FaceUp'),
        (0x68F0, 'SCRIPT_ANIM_Josh_FaceDown'),
        (0x68FA, 'SCRIPT_ANIM_Josh_FaceLeft'),
        (0x6904, 'SCRIPT_ANIM_Josh_FaceRight'),
        (0x690E, 'SCRIPT_ANIM_Josh_FaceUpLeft'),
        (0x6918, 'SCRIPT_ANIM_Josh_FaceUpRight'),
        (0x6922, 'SCRIPT_ANIM_Josh_FaceDownLeft'),
        (0x692C, 'SCRIPT_ANIM_Josh_FaceDownRight'),
        (0x6936, 'SCRIPT_ANIM_Josh_GlideBackwardsDown'),
        (0x6945, 'SCRIPT_ANIM_Josh_FaceHero'),
        (0x695C, '.FaceUp'),
        (0x6963, '.FaceDown'),
        (0x696A, '.FaceLeft'),
        (0x6971, '.FaceRight'),
        
        (0x6AF8, 'SCRIPT_ANIM_Sly_WalkUp'),
        (0x6B08, 'SCRIPT_ANIM_Sly_WalkDown'),
        (0x6B18, 'SCRIPT_ANIM_Sly_WalkLeft'),
        (0x6B28, 'SCRIPT_ANIM_Sly_WalkRight'),
        (0x6B38, 'SCRIPT_ANIM_Sly_RunUp'),
        (0x6B48, 'SCRIPT_ANIM_Sly_RunDown'),
        (0x6B58, 'SCRIPT_ANIM_Sly_RunLeft'),
        (0x6B68, 'SCRIPT_ANIM_Sly_RunRight'),
        (0x6B78, 'SCRIPT_ANIM_Sly_FaceUp'),
        (0x6B82, 'SCRIPT_ANIM_Sly_FaceDown'),
        (0x6B8C, 'SCRIPT_ANIM_Sly_FaceLeft'),
        (0x6B96, 'SCRIPT_ANIM_Sly_FaceRight'),
        (0x6BA0, 'SCRIPT_ANIM_Sly_FaceUpLeft'),
        (0x6BAA, 'SCRIPT_ANIM_Sly_FaceUpRight'),
        (0x6BB4, 'SCRIPT_ANIM_Sly_FaceDownLeft'),
        (0x6BBE, 'SCRIPT_ANIM_Sly_FaceDownRight'),
        (0x6BC8, 'SCRIPT_ANIM_Sly_GlideBackwardsDown'),
        (0x6BD7, 'SCRIPT_ANIM_Sly_FaceHero'),
        (0x6BEE, '.FaceUp'),
        (0x6BF5, '.FaceDown'),
        (0x6BFC, '.FaceLeft'),
        (0x6C03, '.FaceRight'),
        
        (0x6D9A, 'SCRIPT_ANIM_Benny_WalkUp'),
        (0x6DAA, 'SCRIPT_ANIM_Benny_WalkDown'),
        (0x6DBA, 'SCRIPT_ANIM_Benny_WalkLeft'),
        (0x6DCA, 'SCRIPT_ANIM_Benny_WalkRight'),
        (0x6DDA, 'SCRIPT_ANIM_Benny_RunUp'),
        (0x6DEA, 'SCRIPT_ANIM_Benny_RunDown'),
        (0x6DFA, 'SCRIPT_ANIM_Benny_RunLeft'),
        (0x6E0A, 'SCRIPT_ANIM_Benny_RunRight'),
        (0x6E1A, 'SCRIPT_ANIM_Benny_FaceUp'),
        (0x6E24, 'SCRIPT_ANIM_Benny_FaceDown'),
        (0x6E2E, 'SCRIPT_ANIM_Benny_FaceLeft'),
        (0x6E38, 'SCRIPT_ANIM_Benny_FaceRight'),
        (0x6E42, 'SCRIPT_ANIM_Benny_FaceUpLeft'),
        (0x6E4C, 'SCRIPT_ANIM_Benny_FaceUpRight'),
        (0x6E56, 'SCRIPT_ANIM_Benny_FaceDownLeft'),
        (0x6E60, 'SCRIPT_ANIM_Benny_FaceDownRight'),
        (0x6E6A, 'SCRIPT_ANIM_Benny_FaceHero'),
        (0x6E81, '.FaceUp'),
        (0x6E88, '.FaceDown'),
        (0x6E8F, '.FaceLeft'),
        (0x6E96, '.FaceRight'),
        
        (0x71C3, 'SCRIPT_ANIM_Korg_WalkUp'),
        (0x71D3, 'SCRIPT_ANIM_Korg_WalkDown'),
        (0x71E3, 'SCRIPT_ANIM_Korg_WalkLeft'),
        (0x71F3, 'SCRIPT_ANIM_Korg_WalkRight'),
        (0x7203, 'SCRIPT_ANIM_Korg_RunUp'),
        (0x7213, 'SCRIPT_ANIM_Korg_RunDown'),
        (0x7223, 'SCRIPT_ANIM_Korg_RunLeft'),
        (0x7233, 'SCRIPT_ANIM_Korg_RunRight'),
        (0x7243, 'SCRIPT_ANIM_Korg_FaceUp'),
        (0x724D, 'SCRIPT_ANIM_Korg_FaceDown'),
        (0x7257, 'SCRIPT_ANIM_Korg_FaceLeft'),
        (0x7261, 'SCRIPT_ANIM_Korg_FaceRight'),
        (0x726B, 'SCRIPT_ANIM_Korg_FaceUpLeft'),
        (0x7275, 'SCRIPT_ANIM_Korg_FaceUpRight'),
        (0x727F, 'SCRIPT_ANIM_Korg_FaceDownLeft'),
        (0x7289, 'SCRIPT_ANIM_Korg_FaceDownRight'),
        (0x7293, 'SCRIPT_ANIM_Korg_BeatLeft'),
        (0x729D, 'SCRIPT_ANIM_Korg_BeatRight'),
        (0x72A7, 'SCRIPT_ANIM_Korg_FlyAway'),
        (0x72B3, 'SCRIPT_ANIM_Korg_FallDown'),
        (0x72BF, 'SCRIPT_ANIM_KorgSwim_FloatLeft'),
        (0x72CB, 'SCRIPT_ANIM_KorgSwim_FloatRight'),
        (0x72FC, '.Loop'),
        (0x7358, 'SCRIPT_ANIM_Korg_FaceHero'),
        (0x736F, '.FaceUp'),
        (0x7376, '.FaceDown'),
        (0x737D, '.FaceLeft'),
        (0x7384, '.FaceRight'),
        
        (0x763E, 'SCRIPT_ANIM_Korremar_WalkUp'),
        (0x764E, 'SCRIPT_ANIM_Korremar_WalkDown'),
        (0x765E, 'SCRIPT_ANIM_Korremar_WalkLeft'),
        (0x766E, 'SCRIPT_ANIM_Korremar_WalkRight'),
        (0x767E, 'SCRIPT_ANIM_Korremar_RunUp'),
        (0x768E, 'SCRIPT_ANIM_Korremar_RunDown'),
        (0x769E, 'SCRIPT_ANIM_Korremar_RunLeft'),
        (0x76AE, 'SCRIPT_ANIM_Korremar_RunRight'),
        (0x76BE, 'SCRIPT_ANIM_Korremar_FaceUp'),
        (0x76C8, 'SCRIPT_ANIM_Korremar_FaceDown'),
        (0x76D2, 'SCRIPT_ANIM_Korremar_FaceLeft'),
        (0x76DC, 'SCRIPT_ANIM_Korremar_FaceRight'),
        (0x76E6, 'SCRIPT_ANIM_Korremar_FaceUpLeft'),
        (0x76F0, 'SCRIPT_ANIM_Korremar_FaceUpRight'),
        (0x76FA, 'SCRIPT_ANIM_Korremar_FaceDownLeft'),
        (0x7704, 'SCRIPT_ANIM_Korremar_FaceDownRight'),
        (0x777A, 'SCRIPT_ANIM_Korremar_FaceHero'),
        (0x7791, '.FaceUp'),
        (0x7798, '.FaceDown'),
        (0x779F, '.FaceLeft'),
        (0x77A6, '.FaceRight'),
        
        (0x793D, 'SCRIPT_ANIM_Logan_WalkUp'),
        (0x794D, 'SCRIPT_ANIM_Logan_WalkDown'),
        (0x795D, 'SCRIPT_ANIM_Logan_WalkLeft'),
        (0x796D, 'SCRIPT_ANIM_Logan_WalkRight'),
        (0x797D, 'SCRIPT_ANIM_Logan_RunUp'),
        (0x798D, 'SCRIPT_ANIM_Logan_RunDown'),
        (0x799D, 'SCRIPT_ANIM_Logan_RunLeft'),
        (0x79AD, 'SCRIPT_ANIM_Logan_RunRight'),
        (0x79BD, 'SCRIPT_ANIM_Logan_FaceUp'),
        (0x79C7, 'SCRIPT_ANIM_Logan_FaceDown'),
        (0x79D1, 'SCRIPT_ANIM_Logan_FaceLeft'),
        (0x79DB, 'SCRIPT_ANIM_Logan_FaceRight'),
        (0x79E5, 'SCRIPT_ANIM_Logan_FaceUpLeft'),
        (0x79EF, 'SCRIPT_ANIM_Logan_FaceUpRight'),
        (0x79F9, 'SCRIPT_ANIM_Logan_FaceDownLeft'),
        (0x7A03, 'SCRIPT_ANIM_Logan_FaceDownRight'),
        (0x7A0D, 'SCRIPT_ANIM_Logan_FaceHero'),
        (0x7A24, '.FaceUp'),
        (0x7A2B, '.FaceDown'),
        (0x7A32, '.FaceLeft'),
        (0x7A39, '.FaceRight'),
        
        (0x7E02, 'SCRIPT_ANIM_Zet_WalkUp'),
        (0x7E12, 'SCRIPT_ANIM_Zet_WalkDown'),
        (0x7E22, 'SCRIPT_ANIM_Zet_WalkLeft'),
        (0x7E32, 'SCRIPT_ANIM_Zet_WalkRight'),
        (0x7E42, 'SCRIPT_ANIM_Zet_RunUp'),
        (0x7E52, 'SCRIPT_ANIM_Zet_RunDown'),
        (0x7E62, 'SCRIPT_ANIM_Zet_RunLeft'),
        (0x7E72, 'SCRIPT_ANIM_Zet_RunRight'),
        (0x7E82, 'SCRIPT_ANIM_Zet_FaceUp'),
        (0x7E8C, 'SCRIPT_ANIM_Zet_FaceDown'),
        (0x7E96, 'SCRIPT_ANIM_Zet_FaceLeft'),
        (0x7EA0, 'SCRIPT_ANIM_Zet_FaceRight'),
        (0x7EAA, 'SCRIPT_ANIM_Zet_FaceUpLeft'),
        (0x7EB4, 'SCRIPT_ANIM_Zet_FaceUpRight'),
        (0x7EBE, 'SCRIPT_ANIM_Zet_FaceDownLeft'),
        (0x7EC8, 'SCRIPT_ANIM_Zet_FaceDownRight'),
        (0x7ED2, 'SCRIPT_ANIM_Zet_BeatLeft'),
        (0x7EE0, 'SCRIPT_ANIM_Zet_BeatRight'),
        (0x7EEE, 'SCRIPT_ANIM_Zet_FlyAway'),
        (0x7EFA, 'SCRIPT_ANIM_Zet_FallDown'),
        (0x7F06, 'SCRIPT_ANIM_Zet_Spin'),
        (0x7F16, 'SCRIPT_ANIM_Zet_KnockedRight'),
        (0x7F20, 'SCRIPT_ANIM_Zet_KnockedLeft'),
        (0x7F2A, 'SCRIPT_ANIM_ZetSwim_FloatLeft'),
        (0x7F36, 'SCRIPT_ANIM_ZetSwim_FloatRight'),
        (0x7F62, '.Loop'),
        (0x7FB1, 'SCRIPT_ANIM_ZetBattle_FadeOut'),
        (0x7FBC, 'SCRIPT_ANIM_Zet_FaceHero'),
        (0x7FD3, '.FaceUp'),
        (0x7FDA, '.FaceDown'),
        (0x7FE1, '.FaceLeft'),
        (0x7FE8, '.FaceRight'),
    ],
    'DELETELABELS': [
        0x5768
    ]
}

sprite_anim_params[0x0F] = {
    'START': 0x4000,
    'END': 0x7F2C,
    'SPRITE': [
        (0x4000, 'Mobis_FaceDownRight'),
        (0x4019, 'Mobis_FaceDownLeft'),
        (0x4032, 'Mobis_FaceUpRight'),
        (0x404B, 'Mobis_FaceUpLeft'),
        (0x4064, 'Mobis_WalkDown1'),
        (0x407D, 'Mobis_FaceDown'),
        (0x4096, 'Mobis_WalkDown2'),
        (0x40AF, 'Mobis_WalkUp1'),
        (0x40C8, 'Mobis_FaceUp'),
        (0x40E1, 'Mobis_WalkUp2'),
        (0x40FA, 'Mobis_WalkRight1'),
        (0x4113, 'Mobis_FaceRight'),
        (0x412C, 'Mobis_WalkRight2'),
        (0x4145, 'Mobis_WalkLeft1'),
        (0x415E, 'Mobis_FaceLeft'),
        (0x4177, 'Mobis_WalkLeft2'),

        (0x4293, 'Morag_FloatDown1'),
        (0x42B4, 'Morag_FloatDown2'),
        (0x42D5, 'Morag_FloatDown3'),
        (0x42F6, 'Morag_FloatRight1'),
        (0x4317, 'Morag_FloatRight2'),
        (0x4338, 'Morag_FloatRight3'),
        (0x4359, 'Morag_FloatLeft1'),
        (0x437A, 'Morag_FloatLeft2'),
        (0x439B, 'Morag_FloatLeft3'),
        (0x43BC, 'Morag_FloatUpRight1'),
        (0x43DD, 'Morag_FloatUpRight2'),
        (0x43FE, 'Morag_FloatUpRight3'),
        (0x441F, 'Morag_FloatUpLeft1'),
        (0x4440, 'Morag_FloatUpLeft2'),
        (0x4461, 'Morag_FloatUpLeft3'),
        (0x4482, 'Morag_FloatUp1'),
        (0x44A3, 'Morag_FloatUp2'),
        (0x44C4, 'Morag_FloatUp3'),
        (0x44E5, 'MoragThrow_Throw1_1'),
        (0x4506, 'MoragThrow_Throw1_2'),
        (0x4527, 'MoragThrow_Throw1_3'),
        (0x4548, 'MoragThrow_Throw2_1'),
        (0x4569, 'MoragThrow_Throw2_2'),
        (0x458A, 'MoragThrow_Throw2_3'),
        (0x45AB, 'MoragThrow_Throw3'),
        (0x45CC, 'MoragHurt_HurtRight'),
        (0x45ED, 'MoragHurt_HurtLeft'),
        (0x460E, 'MoragBattle_IdleDown1'),
        (0x462F, 'MoragBattle_Taunt1'),
        (0x4650, 'MoragBattle_Taunt2'),
        (0x4671, 'MoragBattle_Taunt3'),
        (0x4692, 'MoragBattle_Defeat'),
        (0x46A7, 'MoragBattle_IdleDownLEFTORRIGHT_2_1'),
        (0x46C8, 'MoragBattle_IdleDownLEFTORRIGHT_2_2'),
        (0x46E9, 'MoragBattle_IdleDownLEFTORRIGHT_2_3'),
        (0x470A, 'MoragBattle_IdleDownLEFTORRIGHT_1_1'),
        (0x472B, 'MoragBattle_IdleDownLEFTORRIGHT_1_2'),
        (0x474C, 'MoragBattle_IdleDownLEFTORRIGHT_1_3'),
        (0x476D, 'MoragBattle_Summon1'),
        (0x478E, 'MoragBattle_Summon2'),
        (0x47B3, 'MoragBattle_Summon3'),
        (0x47F9, 'MoragBattle_Victory1'),
        (0x47D8, 'MoragBattle_Victory2'),
        (0x481A, 'MoragBattle_Victory3'),
        (0x483B, 'MoragBattle_IdleDown2'),
        (0x485C, 'MoragBattle_IdleDown3'),

        (0x4B49, 'Ogar_FaceDownRight'),
        (0x4B62, 'Ogar_FaceDownLeft'),
        (0x4B7B, 'Ogar_FaceUpRight'),
        (0x4B90, 'Ogar_FaceUpLeft'),
        (0x4BA5, 'Ogar_WalkDown1'),
        (0x4BBA, 'Ogar_FaceDown'),
        (0x4BD3, 'Ogar_WalkDown2'),
        (0x4BE8, 'Ogar_WalkUp1'),
        (0x4BFD, 'Ogar_FaceUp'),
        (0x4C16, 'Ogar_WalkUp2'),
        (0x4C2B, 'Ogar_WalkRight1'),
        (0x4C44, 'Ogar_FaceRight'),
        (0x4C59, 'Ogar_WalkRight2'),
        (0x4C72, 'Ogar_WalkLeft1'),
        (0x4C8B, 'Ogar_FaceLeft'),
        (0x4CA0, 'Ogar_WalkLeft2'),
        (0x4CB9, 'OgarBattle_Idle1'),
        (0x4CD2, 'OgarBattle_Idle2'),
        (0x4CEB, 'OgarBattle_Victory'),
        (0x4D00, 'OgarBattle_Defeat'),
        (0x4D1D, 'OgarBattle_Taunt1'),
        (0x4D32, 'OgarBattle_Taunt2'),
        (0x4D47, 'OgarBattle_Taunt3'),
        (0x4D71, 'OgarBattle_Summon1'),
        (0x4D8A, 'OgarBattle_Summon2'),
        (0x4DA7, 'OgarBattle_Summon3'),
        (0x4D5C, 'OgarBattle_Idle3'),

        (0x4F93, 'Orlon_FaceDownRight'),
        (0x4FAC, 'Orlon_FaceDownLeft'),
        (0x4FC5, 'Orlon_FaceUpRight'),
        (0x4FDE, 'Orlon_FaceUpLeft'),
        (0x4FF7, 'Orlon_WalkDown1'),
        (0x500C, 'Orlon_FaceDown'),
        (0x5025, 'Orlon_WalkDown2'),
        (0x503A, 'Orlon_WalkUp1'),
        (0x5053, 'Orlon_FaceUp'),
        (0x506C, 'Orlon_WalkUp2'),
        (0x5085, 'Orlon_WalkRight1'),
        (0x509E, 'Orlon_FaceRight'),
        (0x50B7, 'Orlon_WalkRight2'),
        (0x50D0, 'Orlon_WalkLeft1'),
        (0x50E9, 'Orlon_FaceLeft'),
        (0x5102, 'Orlon_WalkLeft2'),
        (0x511B, 'OrlonRing_Idle'),
        (0x5134, 'OrlonRing_01'),
        (0x514D, 'OrlonRing_02'),
        (0x5166, 'OrlonRing_03'),
        (0x5183, 'OrlonRing_04'),
        (0x519C, 'OrlonRing_05'),
        (0x51B5, 'OrlonRing_06'),
        (0x51D6, 'OrlonRing_07'),
        (0x51F7, 'OrlonRing_08'),
        (0x5214, 'OrlonRing_09'),
        (0x5231, 'OrlonRing_10'),

        (0x5420, 'Orwin_FaceDownRight'),
        (0x5439, 'Orwin_FaceDownLeft'),
        (0x5452, 'Orwin_FaceUpRight'),
        (0x546B, 'Orwin_FaceUpLeft'),
        (0x5484, 'Orwin_WalkDown1'),
        (0x549D, 'Orwin_FaceDown'),
        (0x54B6, 'Orwin_WalkDown2'),
        (0x54CF, 'Orwin_WalkUp1'),
        (0x54E8, 'Orwin_FaceUp'),
        (0x5501, 'Orwin_WalkUp2'),
        (0x551A, 'Orwin_WalkRight'),
        (0x5533, 'Orwin_FaceRight'),
        (0x554C, 'Orwin_WalkLeft'),
        (0x5565, 'Orwin_FaceLeft'),
        (0x557E, 'Orwin_Bedridden1'),
        (0x5587, 'Orwin_Bedridden2'),
        (0x5590, 'Orwin_Bedridden3'),
        (0x5599, 'OrwinDie_HurtRight'),
        (0x55BA, 'OrwinDie_HurtLeft'),

        (0x574D, 'Poad_FaceDownRight'),
        (0x5766, 'Poad_FaceDownLeft'),
        (0x577F, 'Poad_FaceUpRight'),
        (0x5798, 'Poad_FaceUpLeft'),
        (0x57B1, 'Poad_WalkDown1'),
        (0x57CA, 'Poad_FaceDown'),
        (0x57E3, 'Poad_WalkDown2'),
        (0x57FC, 'Poad_WalkUp1'),
        (0x5815, 'Poad_FaceUp'),
        (0x582E, 'Poad_WalkUp2'),
        (0x5847, 'Poad_WalkRight1'),
        (0x5860, 'Poad_FaceRight'),
        (0x5875, 'Poad_WalkRight2'),
        (0x588E, 'Poad_WalkLeft1'),
        (0x58A7, 'Poad_FaceLeft'),
        (0x58BC, 'Poad_WalkLeft2'),

        (0x59D8, 'Pruitt_FaceDownRight'),
        (0x59F1, 'Pruitt_FaceDownLeft'),
        (0x5A0A, 'Pruitt_FaceUpRight'),
        (0x5A1B, 'Pruitt_FaceUpLeft'),
        (0x5A2C, 'Pruitt_WalkDown1'),
        (0x5A41, 'Pruitt_FaceDown'),
        (0x5A5A, 'Pruitt_WalkDown2'),
        (0x5A6F, 'Pruitt_WalkUp1'),
        (0x5A84, 'Pruitt_FaceUp'),
        (0x5A9D, 'Pruitt_WalkUp2'),
        (0x5AB2, 'Pruitt_WalkRight1'),
        (0x5ACB, 'Pruitt_FaceRight'),
        (0x5AE0, 'Pruitt_WalkRight2'),
        (0x5AF9, 'Pruitt_WalkLeft1'),
        (0x5B12, 'Pruitt_FaceLeft'),
        (0x5B27, 'Pruitt_WalkLeft2'),
        (0x5B40, 'PruittRing_01'),
        (0x5B59, 'PruittRing_02'),
        (0x5B72, 'PruittRing_03'),
        (0x5B8B, 'PruittRing_04'),
        (0x5BA4, 'PruittRing_05'),
        (0x5BBD, 'PruittRing_06'),
        (0x5BD6, 'PruittRing_07'),
        (0x5BF3, 'PruittRing_08'),
        (0x5C10, 'PruittRing_09'),

        (0x5E4B, 'Salafy_WalkDown1'),
        (0x5E60, 'Salafy_FaceDown'),
        (0x5E79, 'Salafy_WalkDown2'),
        (0x5E8E, 'Salafy_WalkUp1'),
        (0x5EA3, 'Salafy_FaceUp'),
        (0x5EBC, 'Salafy_WalkUp2'),
        (0x5ED1, 'Salafy_WalkRight1'),
        (0x5EEA, 'Salafy_FaceRight'),
        (0x5EFB, 'Salafy_WalkRight2'),
        (0x5F14, 'Salafy_WalkLeft1'),
        (0x5F2D, 'Salafy_FaceLeft'),
        (0x5F3E, 'Salafy_WalkLeft2'),
        (0x5E36, 'Salafy_FaceUpLeft'),
        (0x5E21, 'Salafy_FaceUpRight'),
        (0x5E08, 'Salafy_FaceDownLeft'),
        (0x5DEF, 'Salafy_FaceDownRight'),
        (0x5FD4, 'SalafyBattle_Idle'),
        (0x5F57, 'SalafyBattle_Victory'),
        (0x5F70, 'SalafyBattle_Defeat'),
        (0x5F89, 'SalafyBattle_Summon1'),
        (0x5FA2, 'SalafyBattle_Summon2'),
        (0x5FBB, 'SalafyBattle_Summon3'),
        (0x5FED, 'SalafyBattle_Taunt1'),
        (0x6006, 'SalafyBattle_Taunt2'),

        (0x6211, 'Shimmer_FloatUpRight1'),
        (0x6226, 'Shimmer_FloatUpRight2'),
        (0x623b, 'Shimmer_FloatUpRight3'),
        (0x6250, 'Shimmer_FloatUpLeft1'),
        (0x6265, 'Shimmer_FloatUpLeft2'),
        (0x627a, 'Shimmer_FloatUpLeft3'),
        (0x617B, 'Shimmer_FloatDownRight1'),
        (0x6194, 'Shimmer_FloatDownRight2'),
        (0x61AD, 'Shimmer_FloatDownRight3'),
        (0x61C6, 'Shimmer_FloatDownLeft1'),
        (0x61DF, 'Shimmer_FloatDownLeft2'),
        (0x61F8, 'Shimmer_FloatDownLeft3'),

        (0x63DE, 'SirAdam_WalkUp1'),
        (0x63F7, 'SirAdam_FaceUp'),
        (0x6410, 'SirAdam_WalkUp2'),
        (0x6393, 'SirAdam_WalkDown1'),
        (0x63AC, 'SirAdam_FaceDown'),
        (0x63C5, 'SirAdam_WalkDown2'),
        (0x6474, 'SirAdam_WalkLeft1'),
        (0x648D, 'SirAdam_FaceLeft'),
        (0x64A6, 'SirAdam_WalkLeft2'),
        (0x6429, 'SirAdam_WalkRight1'),
        (0x6442, 'SirAdam_FaceRight'),
        (0x645B, 'SirAdam_WalkRight2'),
        (0x637A, 'SirAdam_FaceUpLeft'),
        (0x6361, 'SirAdam_FaceUpRight'),
        (0x6348, 'SirAdam_FaceDownLeft'),
        (0x632F, 'SirAdam_FaceDownRight'),

        (0x6659, 'Tryn_WalkUp1'),
        (0x666E, 'Tryn_FaceUp'),
        (0x6687, 'Tryn_WalkUp2'),
        (0x6616, 'Tryn_WalkDown1'),
        (0x662B, 'Tryn_FaceDown'),
        (0x6644, 'Tryn_WalkDown2'),
        (0x66D7, 'Tryn_WalkLeft1'),
        (0x66EC, 'Tryn_FaceLeft'),
        (0x66FD, 'Tryn_WalkLeft2'),
        (0x669C, 'Tryn_WalkRight1'),
        (0x66B1, 'Tryn_FaceRight'),
        (0x66C2, 'Tryn_WalkRight2'),
        (0x6605, 'Tryn_FaceUpLeft'),
        (0x65F4, 'Tryn_FaceUpRight'),
        (0x65DB, 'Tryn_FaceDownLeft'),
        (0x65C2, 'Tryn_FaceDownRight'),

        (0x68B8, 'Tryn_WalkUp1'),
        (0x68CD, 'Tryn_FaceUp'),
        (0x68E6, 'Tryn_WalkUp2'),
        (0x6871, 'Tryn_WalkDown1'),
        (0x6886, 'Tryn_FaceDown'),
        (0x689F, 'Tryn_WalkDown2'),
        (0x6942, 'Tryn_WalkLeft1'),
        (0x695B, 'Tryn_FaceLeft'),
        (0x6970, 'Tryn_WalkLeft2'),
        (0x68FB, 'Tryn_WalkRight1'),
        (0x6914, 'Tryn_FaceRight'),
        (0x6929, 'Tryn_WalkRight2'),
        (0x685C, 'Tryn_FaceUpLeft'),
        (0x6847, 'Tryn_FaceUpRight'),
        (0x682E, 'Tryn_FaceDownLeft'),
        (0x6815, 'Tryn_FaceDownRight'),

        (0x6B3B, 'Valkan_WalkUp1'),
        (0x6B54, 'Valkan_FaceUp'),
        (0x6B6D, 'Valkan_WalkUp2'),
        (0x6AF0, 'Valkan_WalkDown1'),
        (0x6B09, 'Valkan_FaceDown'),
        (0x6B22, 'Valkan_WalkDown2'),
        (0x6BD1, 'Valkan_WalkLeft1'),
        (0x6BEA, 'Valkan_FaceLeft'),
        (0x6C03, 'Valkan_WalkLeft2'),
        (0x6B86, 'Valkan_WalkRight1'),
        (0x6B9F, 'Valkan_FaceRight'),
        (0x6BB8, 'Valkan_WalkRight2'),
        (0x6AD7, 'Valkan_FaceUpLeft'),
        (0x6ABE, 'Valkan_FaceUpRight'),
        (0x6AA5, 'Valkan_FaceDownLeft'),
        (0x6A8C, 'Valkan_FaceDownRight'),
        (0x6C56, 'ValkanSpear_SpearLeft1'),
        (0x6C73, 'ValkanSpear_SpearLeft2'),
        (0x6C1C, 'ValkanSpear_SpearRight1'),
        (0x6C39, 'ValkanSpear_SpearRight2'),

        (0x6E69, 'Warrada_WalkUp1'),
        (0x6E7E, 'Warrada_FaceUp'),
        (0x6E97, 'Warrada_WalkUp2'),
        (0x6E26, 'Warrada_WalkDown1'),
        (0x6E3B, 'Warrada_FaceDown'),
        (0x6E54, 'Warrada_WalkDown2'),
        (0x6EF3, 'Warrada_WalkLeft1'),
        (0x6F0C, 'Warrada_FaceLeft'),
        (0x6F21, 'Warrada_WalkLeft2'),
        (0x6EAC, 'Warrada_WalkRight1'),
        (0x6EC5, 'Warrada_FaceRight'),
        (0x6EDA, 'Warrada_WalkRight2'),
        (0x6E11, 'Warrada_FaceUpLeft'),
        (0x6DFC, 'Warrada_FaceUpRight'),
        (0x6DE3, 'Warrada_FaceDownLeft'),
        (0x6DCA, 'Warrada_FaceDownRight'),
        (0x6F3A, 'WarradaBattle_Idle'),
        (0x6F96, 'WarradaBattle_Defeat'),
        (0x6FAF, 'WarradaBattle_Summon1'),
        (0x6FC8, 'WarradaBattle_Summon2'),
        (0x6FE5, 'WarradaBattle_Summon3'),
        (0x6F6C, 'WarradaBattle_Taunt1'),
        (0x6F81, 'WarradaBattle_Taunt2'),
    ],
    'SCRIPT': [
        (0x4190, 'SCRIPT_ANIM_Mobis_WalkUp'),
        (0x41A0, 'SCRIPT_ANIM_Mobis_WalkDown'),
        (0x41B0, 'SCRIPT_ANIM_Mobis_WalkLeft'),
        (0x41C0, 'SCRIPT_ANIM_Mobis_WalkRight'),
        (0x41D0, 'SCRIPT_ANIM_Mobis_RunUp'),
        (0x41E0, 'SCRIPT_ANIM_Mobis_RunDown'),
        (0x41F0, 'SCRIPT_ANIM_Mobis_RunLeft'),
        (0x4200, 'SCRIPT_ANIM_Mobis_RunRight'),
        (0x4210, 'SCRIPT_ANIM_Mobis_FaceUp'),
        (0x421A, 'SCRIPT_ANIM_Mobis_FaceDown'),
        (0x4224, 'SCRIPT_ANIM_Mobis_FaceLeft'),
        (0x422E, 'SCRIPT_ANIM_Mobis_FaceRight'),
        (0x4238, 'SCRIPT_ANIM_Mobis_FaceUpLeft'),
        (0x4242, 'SCRIPT_ANIM_Mobis_FaceUpRight'),
        (0x424C, 'SCRIPT_ANIM_Mobis_FaceDownLeft'),
        (0x4256, 'SCRIPT_ANIM_Mobis_FaceDownRight'),
        (0x4260, 'SCRIPT_ANIM_Mobis_FaceHero'),
        (0x4277, '.FaceUp'),
        (0x427E, '.FaceDown'),
        (0x4285, '.FaceLeft'),
        (0x428C, '.FaceRight'),

        (0x487D, 'SCRIPT_ANIM_Morag_FaceDown'),
        (0x488D, 'SCRIPT_ANIM_Morag_UNKNOWN_FrozenDown'),
        (0x4897, 'SCRIPT_ANIM_Morag_FaceUp'),
        (0x48A7, 'SCRIPT_ANIM_Morag_FaceDownLeft'),
        (0x48B7, 'SCRIPT_ANIM_Morag_FaceDownRight'),
        (0x48C7, 'SCRIPT_ANIM_Morag_FaceUpLeft'),
        (0x48D7, 'SCRIPT_ANIM_Morag_FaceUpRight'),
        (0x48E7, 'SCRIPT_ANIM_Morag_WalkUp'),
        (0x48F7, 'SCRIPT_ANIM_Morag_WalkDown'),
        (0x4907, 'SCRIPT_ANIM_Morag_WalkRight'),
        (0x4917, 'SCRIPT_ANIM_Morag_WalkLeft'),
        (0x4927, 'SCRIPT_ANIM_Morag_WalkDownLeft'),
        (0x4937, 'SCRIPT_ANIM_Morag_WalkDownRight'),
        (0x4947, 'SCRIPT_ANIM_Morag_WalkUpLeft'),
        (0x4957, 'SCRIPT_ANIM_Morag_WalkUpRight'),
        (0x4967, 'SCRIPT_ANIM_MoragThrow_Throw1_Still'),
        (0x4977, 'SCRIPT_ANIM_MoragThrow_Throw1_Up'),
        (0x4987, 'SCRIPT_ANIM_MoragThrow_Throw2'),
        (0x4997, 'SCRIPT_ANIM_MoragThrow_Throw2_UNKNOWN'),
        (0x49A1, 'SCRIPT_ANIM_MoragThrow_Throw3'),
        (0x49AB, 'SCRIPT_ANIM_MoragHurt_Flicker'),
        (0x49B6, 'SCRIPT_ANIM_MoragHurt_HurtLeft'),
        (0x49E0, '.Loop'),
        (0x49EA, 'SCRIPT_ANIM_MoragHurt_HurtRight'),
        (0x4A14, '.Loop'),
        (0x4A43, '.DownLEFTORRIGHT_1'),
        (0x4A63, '.DownLEFTORRIGHT_2'),
        (0x4AF5, '.Loop'),

        (0x4DC4, 'SCRIPT_ANIM_Ogar_WalkUp'),
        (0x4DD4, 'SCRIPT_ANIM_Ogar_WalkDown'),
        (0x4DE4, 'SCRIPT_ANIM_Ogar_WalkLeft'),
        (0x4DF4, 'SCRIPT_ANIM_Ogar_WalkRight'),
        (0x4E04, 'SCRIPT_ANIM_Ogar_RunUp'),
        (0x4E14, 'SCRIPT_ANIM_Ogar_RunDown'),
        (0x4E24, 'SCRIPT_ANIM_Ogar_RunLeft'),
        (0x4E34, 'SCRIPT_ANIM_Ogar_RunRight'),
        (0x4E44, 'SCRIPT_ANIM_Ogar_FaceUp'),
        (0x4E4E, 'SCRIPT_ANIM_Ogar_FaceDown'),
        (0x4E58, 'SCRIPT_ANIM_Ogar_FaceLeft'),
        (0x4E62, 'SCRIPT_ANIM_Ogar_FaceRight'),
        (0x4E6C, 'SCRIPT_ANIM_Ogar_FaceUpLeft'),
        (0x4E76, 'SCRIPT_ANIM_Ogar_FaceUpRight'),
        (0x4E80, 'SCRIPT_ANIM_Ogar_FaceDownLeft'),
        (0x4E8A, 'SCRIPT_ANIM_Ogar_FaceDownRight'),
        (0x4F56, '.Loop'),
        (0x4F60, 'SCRIPT_ANIM_Ogar_FaceHero'),
        (0x4F77, '.FaceUp'),
        (0x4F7E, '.FaceDown'),
        (0x4F85, '.FaceLeft'),
        (0x4F8C, '.FaceRight'),

        (0x524E, 'SCRIPT_ANIM_Orlon_WalkUp'),
        (0x525E, 'SCRIPT_ANIM_Orlon_WalkDown'),
        (0x526E, 'SCRIPT_ANIM_Orlon_WalkLeft'),
        (0x527E, 'SCRIPT_ANIM_Orlon_WalkRight'),
        (0x528E, 'SCRIPT_ANIM_Orlon_RunUp'),
        (0x529E, 'SCRIPT_ANIM_Orlon_RunDown'),
        (0x52AE, 'SCRIPT_ANIM_Orlon_RunLeft'),
        (0x52BE, 'SCRIPT_ANIM_Orlon_RunRight'),
        (0x52CE, 'SCRIPT_ANIM_Orlon_FaceUp'),
        (0x52D8, 'SCRIPT_ANIM_Orlon_FaceDown'),
        (0x52E2, 'SCRIPT_ANIM_Orlon_FaceLeft'),
        (0x52EC, 'SCRIPT_ANIM_Orlon_FaceRight'),
        (0x52F6, 'SCRIPT_ANIM_Orlon_FaceUpLeft'),
        (0x5300, 'SCRIPT_ANIM_Orlon_FaceUpRight'),
        (0x530A, 'SCRIPT_ANIM_Orlon_FaceDownLeft'),
        (0x5314, 'SCRIPT_ANIM_Orlon_FaceDownRight'),
        (0x531E, 'SCRIPT_ANIM_OrlonRing_MakeRing'),
        (0x53A0, '.Loop'),
        (0x53AA, 'SCRIPT_ANIM_OrlonRing_Idle'),
        (0x53B4, 'SCRIPT_ANIM_OrlonRing_ScreenShake'),
        (0x53ED, 'SCRIPT_ANIM_Orlon_FaceHero'),
        (0x5404, '.FaceUp'),
        (0x540B, '.FaceDown'),
        (0x5412, '.FaceLeft'),
        (0x5419, '.FaceRight'),

        (0x55DB, 'SCRIPT_ANIM_Orwin_WalkUp'),
        (0x55EB, 'SCRIPT_ANIM_Orwin_WalkDown'),
        (0x55FB, 'SCRIPT_ANIM_Orwin_WalkLeft'),
        (0x560B, 'SCRIPT_ANIM_Orwin_WalkRight'),
        (0x561B, 'SCRIPT_ANIM_Orwin_RunUp'),
        (0x562B, 'SCRIPT_ANIM_Orwin_RunDown'),
        (0x563B, 'SCRIPT_ANIM_Orwin_RunLeft'),
        (0x564B, 'SCRIPT_ANIM_Orwin_RunRight'),
        (0x565B, 'SCRIPT_ANIM_Orwin_FaceUp'),
        (0x5665, 'SCRIPT_ANIM_Orwin_FaceDown'),
        (0x566F, 'SCRIPT_ANIM_Orwin_FaceLeft'),
        (0x5679, 'SCRIPT_ANIM_Orwin_FaceRight'),
        (0x5683, 'SCRIPT_ANIM_Orwin_FaceUpLeft'),
        (0x568D, 'SCRIPT_ANIM_Orwin_FaceUpRight'),
        (0x5697, 'SCRIPT_ANIM_Orwin_FaceDownLeft'),
        (0x56A1, 'SCRIPT_ANIM_Orwin_FaceDownRight'),
        (0x56AB, 'SCRIPT_ANIM_Orwin_HurtLeft'),
        (0x56B5, 'SCRIPT_ANIM_Orwin_HurtRight'),
        (0x56BF, 'SCRIPT_ANIM_Orwin_Flicker'),
        (0x56CA, 'SCRIPT_ANIM_Orwin_Spin1'),
        (0x56E3, 'SCRIPT_ANIM_Orwin_Spin2'),
        (0x56FC, 'SCRIPT_ANIM_Orwin_Bedridden1'),
        (0x5706, 'SCRIPT_ANIM_Orwin_Bedridden2'),
        (0x5710, 'SCRIPT_ANIM_Orwin_Bedridden3'),
        (0x571A, 'SCRIPT_ANIM_Orwin_FaceHero'),
        (0x5731, '.FaceUp'),
        (0x5738, '.FaceDown'),
        (0x573F, '.FaceLeft'),
        (0x5746, '.FaceRight'),

        (0x58D5, 'SCRIPT_ANIM_Poad_WalkUp'),
        (0x58E5, 'SCRIPT_ANIM_Poad_WalkDown'),
        (0x58F5, 'SCRIPT_ANIM_Poad_WalkLeft'),
        (0x5905, 'SCRIPT_ANIM_Poad_WalkRight'),
        (0x5915, 'SCRIPT_ANIM_Poad_RunUp'),
        (0x5925, 'SCRIPT_ANIM_Poad_RunDown'),
        (0x5935, 'SCRIPT_ANIM_Poad_RunLeft'),
        (0x5945, 'SCRIPT_ANIM_Poad_RunRight'),
        (0x5955, 'SCRIPT_ANIM_Poad_FaceUp'),
        (0x595F, 'SCRIPT_ANIM_Poad_FaceDown'),
        (0x5969, 'SCRIPT_ANIM_Poad_FaceLeft'),
        (0x5973, 'SCRIPT_ANIM_Poad_FaceRight'),
        (0x597D, 'SCRIPT_ANIM_Poad_FaceUpLeft'),
        (0x5987, 'SCRIPT_ANIM_Poad_FaceUpRight'),
        (0x5991, 'SCRIPT_ANIM_Poad_FaceDownLeft'),
        (0x599B, 'SCRIPT_ANIM_Poad_FaceDownRight'),
        (0x59A5, 'SCRIPT_ANIM_Poad_FaceHero'),
        (0x59BC, '.FaceUp'),
        (0x59C3, '.FaceDown'),
        (0x59CA, '.FaceLeft'),
        (0x59D1, '.FaceRight'),

        (0x5C2D, 'SCRIPT_ANIM_Pruitt_WalkUp'),
        (0x5C3D, 'SCRIPT_ANIM_Pruitt_WalkDown'),
        (0x5C4D, 'SCRIPT_ANIM_Pruitt_WalkLeft'),
        (0x5C5D, 'SCRIPT_ANIM_Pruitt_WalkRight'),
        (0x5C6D, 'SCRIPT_ANIM_Pruitt_RunUp'),
        (0x5C7D, 'SCRIPT_ANIM_Pruitt_RunDown'),
        (0x5C8D, 'SCRIPT_ANIM_Pruitt_RunLeft'),
        (0x5C9D, 'SCRIPT_ANIM_Pruitt_RunRight'),
        (0x5CAD, 'SCRIPT_ANIM_Pruitt_FaceUp'),
        (0x5CB7, 'SCRIPT_ANIM_Pruitt_FaceDown'),
        (0x5CC1, 'SCRIPT_ANIM_Pruitt_FaceLeft'),
        (0x5CCB, 'SCRIPT_ANIM_Pruitt_FaceRight'),
        (0x5CD5, 'SCRIPT_ANIM_Pruitt_FaceUpLeft'),
        (0x5CDF, 'SCRIPT_ANIM_Pruitt_FaceUpRight'),
        (0x5CE9, 'SCRIPT_ANIM_Pruitt_FaceDownLeft'),
        (0x5CF3, 'SCRIPT_ANIM_Pruitt_FaceDownRight'),


        (0x5CFD, 'SCRIPT_ANIM_PruittRing_MakeRing'),
        (0x5D8D, '.Loop'),
        (0x5DB0, 'SCRIPT_ANIM_PruittRing_ScreenShake'),
        (0x5DBB, 'SCRIPT_ANIM_PruittRing_ScreenStopShake'),
        (0x5D9C, 'SCRIPT_ANIM_PruittRing_UNKNOWN1'),
        (0x5DA6, 'SCRIPT_ANIM_PruittRing_UNKNOWN2'),
        (0x5DBC, 'SCRIPT_ANIM_Pruitt_FaceHero'),
        (0x5DD3, '.FaceUp'),
        (0x5DDA, '.FaceDown'),
        (0x5DE1, '.FaceLeft'),
        (0x5DE8, '.FaceRight'),

        (0x601F, 'SCRIPT_ANIM_Salafy_WalkUp'),
        (0x602F, 'SCRIPT_ANIM_Salafy_WalkDown'),
        (0x603F, 'SCRIPT_ANIM_Salafy_WalkLeft'),
        (0x604F, 'SCRIPT_ANIM_Salafy_WalkRight'),
        (0x605F, 'SCRIPT_ANIM_Salafy_RunUp'),
        (0x606F, 'SCRIPT_ANIM_Salafy_RunDown'),
        (0x607F, 'SCRIPT_ANIM_Salafy_RunLeft'),
        (0x608F, 'SCRIPT_ANIM_Salafy_RunRight'),
        (0x609F, 'SCRIPT_ANIM_Salafy_FaceUp'),
        (0x60A9, 'SCRIPT_ANIM_Salafy_FaceDown'),
        (0x60B3, 'SCRIPT_ANIM_Salafy_FaceLeft'),
        (0x60BD, 'SCRIPT_ANIM_Salafy_FaceRight'),
        (0x60C7, 'SCRIPT_ANIM_Salafy_FaceUpLeft'),
        (0x60D1, 'SCRIPT_ANIM_Salafy_FaceUpRight'),
        (0x60DB, 'SCRIPT_ANIM_Salafy_FaceDownLeft'),
        (0x60E5, 'SCRIPT_ANIM_Salafy_FaceDownRight'),
        (0x6148, 'SCRIPT_ANIM_Salafy_FaceHero'),
        (0x615F, '.FaceUp'),
        (0x6166, '.FaceDown'),
        (0x616D, '.FaceLeft'),
        (0x6174, '.FaceRight'),

        (0x628F, 'SCRIPT_ANIM_Shimmer_FaceDownLeft'),
        (0x629F, 'SCRIPT_ANIM_Shimmer_FaceDownRight'),
        (0x62AF, 'SCRIPT_ANIM_Shimmer_FaceUpLeft'),
        (0x62BF, 'SCRIPT_ANIM_Shimmer_FaceUpRight'),
        (0x62CF, 'SCRIPT_ANIM_Shimmer_WalkDownLeft'),
        (0x62DF, 'SCRIPT_ANIM_Shimmer_WalkDownRight'),
        (0x62EF, 'SCRIPT_ANIM_Shimmer_WalkLeft'),
        (0x62FF, 'SCRIPT_ANIM_Shimmer_WalkRight'),
        (0x630F, 'SCRIPT_ANIM_Shimmer_WalkUpLeft'),
        (0x631F, 'SCRIPT_ANIM_Shimmer_WalkUpRight'),

        (0x64BF, 'SCRIPT_ANIM_SirAdam_WalkUp'),
        (0x64CF, 'SCRIPT_ANIM_SirAdam_WalkDown'),
        (0x64DF, 'SCRIPT_ANIM_SirAdam_WalkLeft'),
        (0x64EF, 'SCRIPT_ANIM_SirAdam_WalkRight'),
        (0x64FF, 'SCRIPT_ANIM_SirAdam_RunUp'),
        (0x650F, 'SCRIPT_ANIM_SirAdam_RunDown'),
        (0x651F, 'SCRIPT_ANIM_SirAdam_RunLeft'),
        (0x652F, 'SCRIPT_ANIM_SirAdam_RunRight'),
        (0x653F, 'SCRIPT_ANIM_SirAdam_FaceUp'),
        (0x6549, 'SCRIPT_ANIM_SirAdam_FaceDown'),
        (0x6553, 'SCRIPT_ANIM_SirAdam_FaceLeft'),
        (0x655D, 'SCRIPT_ANIM_SirAdam_FaceRight'),
        (0x6567, 'SCRIPT_ANIM_SirAdam_FaceUpLeft'),
        (0x6571, 'SCRIPT_ANIM_SirAdam_FaceUpRight'),
        (0x657B, 'SCRIPT_ANIM_SirAdam_FaceDownLeft'),
        (0x6585, 'SCRIPT_ANIM_SirAdam_FaceDownRight'),
        (0x658F, 'SCRIPT_ANIM_SirAdam_FaceHero'),
        (0x65A6, '.FaceUp'),
        (0x65AD, '.FaceDown'),
        (0x65B4, '.FaceLeft'),
        (0x65BB, '.FaceRight'),

        (0x6712, 'SCRIPT_ANIM_Tryn_WalkUp'),
        (0x6722, 'SCRIPT_ANIM_Tryn_WalkDown'),
        (0x6732, 'SCRIPT_ANIM_Tryn_WalkLeft'),
        (0x6742, 'SCRIPT_ANIM_Tryn_WalkRight'),
        (0x6752, 'SCRIPT_ANIM_Tryn_RunUp'),
        (0x6762, 'SCRIPT_ANIM_Tryn_RunDown'),
        (0x6772, 'SCRIPT_ANIM_Tryn_RunLeft'),
        (0x6782, 'SCRIPT_ANIM_Tryn_RunRight'),
        (0x6792, 'SCRIPT_ANIM_Tryn_FaceUp'),
        (0x679C, 'SCRIPT_ANIM_Tryn_FaceDown'),
        (0x67A6, 'SCRIPT_ANIM_Tryn_FaceLeft'),
        (0x67B0, 'SCRIPT_ANIM_Tryn_FaceRight'),
        (0x67BA, 'SCRIPT_ANIM_Tryn_FaceUpLeft'),
        (0x67C4, 'SCRIPT_ANIM_Tryn_FaceUpRight'),
        (0x67CE, 'SCRIPT_ANIM_Tryn_FaceDownLeft'),
        (0x67D8, 'SCRIPT_ANIM_Tryn_FaceDownRight'),
        (0x67E2, 'SCRIPT_ANIM_Tryn_FaceHero'),
        (0x67F9, '.FaceUp'),
        (0x6800, '.FaceDown'),
        (0x6807, '.FaceLeft'),
        (0x680E, '.FaceRight'),

        (0x6989, 'SCRIPT_ANIM_Ulk_WalkUp'),
        (0x6999, 'SCRIPT_ANIM_Ulk_WalkDown'),
        (0x69A9, 'SCRIPT_ANIM_Ulk_WalkLeft'),
        (0x69B9, 'SCRIPT_ANIM_Ulk_WalkRight'),
        (0x69C9, 'SCRIPT_ANIM_Ulk_RunUp'),
        (0x69D9, 'SCRIPT_ANIM_Ulk_RunDown'),
        (0x69E9, 'SCRIPT_ANIM_Ulk_RunLeft'),
        (0x69F9, 'SCRIPT_ANIM_Ulk_RunRight'),
        (0x6A09, 'SCRIPT_ANIM_Ulk_FaceUp'),
        (0x6A13, 'SCRIPT_ANIM_Ulk_FaceDown'),
        (0x6A1D, 'SCRIPT_ANIM_Ulk_FaceLeft'),
        (0x6A27, 'SCRIPT_ANIM_Ulk_FaceRight'),
        (0x6A31, 'SCRIPT_ANIM_Ulk_FaceUpLeft'),
        (0x6A3B, 'SCRIPT_ANIM_Ulk_FaceUpRight'),
        (0x6A45, 'SCRIPT_ANIM_Ulk_FaceDownLeft'),
        (0x6A4F, 'SCRIPT_ANIM_Ulk_FaceDownRight'),
        (0x6A59, 'SCRIPT_ANIM_Ulk_FaceHero'),
        (0x6A70, '.FaceUp'),
        (0x6A77, '.FaceDown'),
        (0x6A7E, '.FaceLeft'),
        (0x6A85, '.FaceRight'),

        (0x6C90, 'SCRIPT_ANIM_Valkan_WalkUp'),
        (0x6CA0, 'SCRIPT_ANIM_Valkan_WalkDown'),
        (0x6CB0, 'SCRIPT_ANIM_Valkan_WalkLeft'),
        (0x6CC0, 'SCRIPT_ANIM_Valkan_WalkRight'),
        (0x6CD0, 'SCRIPT_ANIM_Valkan_RunUp'),
        (0x6CE0, 'SCRIPT_ANIM_Valkan_RunDown'),
        (0x6CF0, 'SCRIPT_ANIM_Valkan_RunLeft'),
        (0x6D00, 'SCRIPT_ANIM_Valkan_RunRight'),
        (0x6D10, 'SCRIPT_ANIM_Valkan_FaceUp'),
        (0x6D1A, 'SCRIPT_ANIM_Valkan_FaceDown'),
        (0x6D24, 'SCRIPT_ANIM_Valkan_FaceLeft'),
        (0x6D2E, 'SCRIPT_ANIM_Valkan_FaceRight'),
        (0x6D38, 'SCRIPT_ANIM_Valkan_FaceUpLeft'),
        (0x6D42, 'SCRIPT_ANIM_Valkan_FaceUpRight'),
        (0x6D4C, 'SCRIPT_ANIM_Valkan_FaceDownLeft'),
        (0x6D56, 'SCRIPT_ANIM_Valkan_FaceDownRight'),
        (0x6D60, 'SCRIPT_ANIM_Valkan_Flicker'),
        (0x6D6B, 'SCRIPT_ANIM_Valkan_UNKNOWNDown'),
        (0x6D75, 'SCRIPT_ANIM_ValkanSpear_SpearLeft'),
        (0x6D7C, '.Loop'),
        (0x6D86, 'SCRIPT_ANIM_ValkanSpear_SpearRight'),
        (0x6D8D, '.Loop'),
        (0x6D97, 'SCRIPT_ANIM_Valkan_FaceHero'),
        (0x6DAE, '.FaceUp'),
        (0x6DB5, '.FaceDown'),
        (0x6DBC, '.FaceLeft'),
        (0x6DC3, '.FaceRight'),

        (0x7002, 'SCRIPT_ANIM_Warrada_WalkUp'),
        (0x7012, 'SCRIPT_ANIM_Warrada_WalkDown'),
        (0x7022, 'SCRIPT_ANIM_Warrada_WalkLeft'),
        (0x7032, 'SCRIPT_ANIM_Warrada_WalkRight'),
        (0x7042, 'SCRIPT_ANIM_Warrada_RunUp'),
        (0x7052, 'SCRIPT_ANIM_Warrada_RunDown'),
        (0x7062, 'SCRIPT_ANIM_Warrada_RunLeft'),
        (0x7072, 'SCRIPT_ANIM_Warrada_RunRight'),
        (0x7082, 'SCRIPT_ANIM_Warrada_FaceUp'),
        (0x708C, 'SCRIPT_ANIM_Warrada_FaceDown'),
        (0x7096, 'SCRIPT_ANIM_Warrada_FaceLeft'),
        (0x70A0, 'SCRIPT_ANIM_Warrada_FaceRight'),
        (0x70AA, 'SCRIPT_ANIM_Warrada_FaceUpLeft'),
        (0x70B4, 'SCRIPT_ANIM_Warrada_FaceUpRight'),
        (0x70BE, 'SCRIPT_ANIM_Warrada_FaceDownLeft'),
        (0x70C8, 'SCRIPT_ANIM_Warrada_FaceDownRight'),
        (0x7147, 'SCRIPT_ANIM_Warrada_FaceHero'),
        (0x715E, '.FaceUp'),
        (0x7165, '.FaceDown'),
        (0x716C, '.FaceLeft'),
        (0x7173, '.FaceRight'),

        (0x7334, 'SCRIPT_ANIM_Wence_WalkUp'),
        (0x7344, 'SCRIPT_ANIM_Wence_WalkDown'),
        (0x7354, 'SCRIPT_ANIM_Wence_WalkLeft'),
        (0x7364, 'SCRIPT_ANIM_Wence_WalkRight'),
        (0x7374, 'SCRIPT_ANIM_Wence_RunUp'),
        (0x7384, 'SCRIPT_ANIM_Wence_RunDown'),
        (0x7394, 'SCRIPT_ANIM_Wence_RunLeft'),
        (0x73A4, 'SCRIPT_ANIM_Wence_RunRight'),
        (0x73B4, 'SCRIPT_ANIM_Wence_FaceUp'),
        (0x73BE, 'SCRIPT_ANIM_Wence_FaceDown'),
        (0x73C8, 'SCRIPT_ANIM_Wence_FaceLeft'),
        (0x73D2, 'SCRIPT_ANIM_Wence_FaceRight'),
        (0x73DC, 'SCRIPT_ANIM_Wence_FaceUpLeft'),
        (0x73E6, 'SCRIPT_ANIM_Wence_FaceUpRight'),
        (0x73F0, 'SCRIPT_ANIM_Wence_FaceDownLeft'),
        (0x73FA, 'SCRIPT_ANIM_Wence_FaceDownRight'),
        (0x7404, 'SCRIPT_ANIM_Wence_UNKNOWNUp'),
        (0x7414, 'SCRIPT_ANIM_Wence_UNKNOWNDown'),
        (0x7424, 'SCRIPT_ANIM_WenceBow_ArrowLeft'),
        (0x742E, 'SCRIPT_ANIM_WenceBow_ArrowRight'),
        (0x7438, 'SCRIPT_ANIM_Wence_FaceHero'),
        (0x744F, '.FaceUp'),
        (0x7456, '.FaceDown'),
        (0x745D, '.FaceLeft'),
        (0x7464, '.FaceRight'),
    ],
    'DELETELABELS': [
        0x4548,
    ]
}


def setupSpriteAnim(bank, debug):
    params = sprite_anim_params[bank]
    start = BankAddress(bank, params['START'])
    end = BankAddress(bank, params['END'])
    for addr in params['DELETELABELS']:
        sym.delSymbol(bank, addr)
    for addr, label in params['SPRITE']:
        sym.replaceSymbol(bank, addr, 'SPRITE_' + label)
    for addr, label in params['SCRIPT']:
        sym.replaceSymbol(bank, addr, label)
    return magireader.interpretSpriteAnim(start, end, sym, debug)


table = MainTable(rom)
with open(config.outdir + 'tempbattle.asm', 'w') as f:
    f.write(table.getOutput())
setupSpriteAnim(0x0F, True)
