
from dataclasses import dataclass
from projutils.utils import BankAddress, Rom, SymFile
import projutils.magireader as magireader
import projutils.config as config


rom = Rom()
sym = SymFile()


class MagiTable:

    ANIM_NAMES = [
        "Idle",
        "Taunt", # Tony just has a duplicate Focus animation it seems
        "Summon",
        "Victory",
        "Defeat",
        "Focus", # Tony exclusive
        "Choose", # Tony exclusive
    ]

    def __init__(self, row):
        self.animcount = 7 if row.row == 0 else 5  # Tony has 7 anims exceptionally
        self.name = row.name
        self.address: BankAddress = row.data

        if row.row == 9 or row.row == 10:
            # Skip Agram2 and Agram3
            return

        self.anims = [rom.getBankAddress(self.address + i*3, getobj=True) for i in range(self.animcount)]
        self.symbols = [self.getSymbol(i) for i in range(self.animcount)]
        self.updateSymFile()

        assert(self.anims[0] == min(self.anims))

    def __eq__(self, other):
        return self.address == other.address

    def __hash__(self):
        return self.address.getPos()

    def getOutput(self):
        return '    ; ${:04X}\nBattle_MagiAnim_{}::\n{}'.format(
                self.address.getAddress(),
                self.name,
                '\n'.join(['    dw ' + symbol for symbol in self.symbols])
            )

    def getSymbol(self, anim_i):
        return 'SCRIPT_ANIM_{}Battle_{}'.format(self.name, MagiTable.ANIM_NAMES[anim_i])

    def getAddress(self, anim_i):
        return self.anims[anim_i]

    def updateSymFile(self):
        # Don't run this twice
        for data in zip(self.anims, self.symbols):
            sym.addSymbol(data[0].getBank(), data[0].getAddress(), data[1])

    def __repr__(self):
        return self.getOutput()


class MainTable:

    @dataclass
    class Row:
        def __init__(self, i):
            self.row = i
            self.address = MainTable.TABLE_LOCATION + i*2
            self.data = BankAddress(MainTable.TABLE_LOCATION.getBank(), rom.getWord(self.address))
            self.name = rom.getString(MainTable.MAGI_NAMES_LOCATION + i*10, 10).strip()
            #if 8 <= i <= 10:  # Agram
            #    self.name += str(i - 7)
            if 11 <= i <= 18:  # ShadowMagi
                self.name += str(i - 10)

        def getOutput(self):
            return '    dw Battle_MagiAnim_' + self.name

    TABLE_LENGTH = 0x14
    TABLE_LOCATION = BankAddress(0x05, 0x5CF1)
    MAGI_NAMES_LOCATION = BankAddress(0x19E16)

    def __init__(self, rom):
        self.rows = [self.Row(i) for i in range(MainTable.TABLE_LENGTH)]

        self.magitables = set()
        for row in self.rows:
            self.magitables.add(MagiTable(row))
        self.magitables = sorted(self.magitables, key=lambda x : x.address)

    def getOutput(self):
        return (
            '    ; ${:04X}\nBattle_MagiAnim_Table::\n{}\n\n'.format(MainTable.TABLE_LOCATION.getAddress(), '\n'.join([row.getOutput() for row in self.rows])) +
            '\n\n'.join([magitable.getOutput() for magitable in self.magitables])
        )


sprite_anim_params = {}
sprite_anim_params[0x0E] = {
    'START': 0x4000,
    'END': 0x7FEF,
    'SPRITE': [
        (0x4000, 'Agram_FaceUNKNOWNDIAGONAL2'),
        (0x403D, 'Agram_FaceUNKNOWNDIAGONAL1'),
        (0x407A, 'Agram_WalkDown1'),
        (0x40B7, 'Agram_FaceDown'),
        (0x40F4, 'Agram_WalkDown2'),
        (0x4131, 'Agram_WalkUp1'),
        (0x416E, 'Agram_FaceUp'),
        (0x41AB, 'Agram_WalkUp2'),
        (0x41E8, 'Agram_WalkRight1'),
        (0x4211, 'Agram_FaceRight'),
        (0x423A, 'Agram_WalkRight2'),
        (0x4263, 'Agram_WalkLeft1'),
        (0x428C, 'Agram_FaceLeft'),
        (0x42B5, 'Agram_WalkLeft2'),
        (0x42DE, 'AgramBattle_Idle'),
        (0x431B, 'AgramBattle_Taunt1'),
        (0x4368, 'AgramBattle_Taunt2'),
        (0x43BD, 'AgramBattle_Taunt3'),
        (0x441A, 'AgramBattle_Taunt4'),
        (0x4477, 'AgramBattle_Taunt5'),
        (0x44D4, 'AgramBattle_Taunt6'),
        (0x4531, 'AgramBattle_Taunt7'),
        (0x458E, 'AgramBattle_HandsUp1'),
        (0x45DB, 'AgramBattle_HandsUp2'),
        (0x4628, 'AgramBattle_Victory'),
        (0x4675, 'AgramBattle_Defeat'),
        (0x46AA, 'AgramBattle_Summon1'),
        (0x46EF, 'AgramBattle_Summon2'),
        (0x4738, 'AgramBattle_Summon3'),

        (0x497D, 'Blu_FaceDownRight'),
        (0x4996, 'Blu_FaceDownLeft'),
        (0x49AF, 'Blu_FaceUpRight'),
        (0x49C8, 'Blu_FaceUpLeft'),
        (0x49E1, 'Blu_WalkDown1'),
        (0x49F6, 'Blu_FaceDown'),
        (0x4A0F, 'Blu_WalkDown2'),
        (0x4A24, 'Blu_WalkUp1'),
        (0x4A3D, 'Blu_FaceUp'),
        (0x4A56, 'Blu_WalkUp2'),
        (0x4A6F, 'Blu_WalkRight1'),
        (0x4A88, 'Blu_FaceRight'),
        (0x4AA1, 'Blu_WalkRight2'),
        (0x4ABA, 'Blu_WalkLeft1'),
        (0x4AD3, 'Blu_FaceLeft'),
        (0x4AEC, 'Blu_WalkLeft2'),

        (0x4C08, 'BluSwim_SwimDown1'),
        (0x4C19, 'BluSwim_SwimDown2'),
        (0x4C2A, 'BluSwim_SwimUp1'),
        (0x4C3B, 'BluSwim_SwimUp2'),
        (0x4C54, 'BluSwim_SwimRight1'),
        (0x4C65, 'BluSwim_SwimRight2'),
        (0x4C76, 'BluSwim_SwimLeft1'),
        (0x4C87, 'BluSwim_SwimLeft2'),
        (0x4C98, 'BluSwim_UNKNOWN1_1'),
        (0x4CB5, 'BluSwim_UNKNOWN1_2'),
        (0x4CD2, 'BluSwim_UNKNOWN1_3'),
        (0x4CEF, 'BluSwim_UNKNOWN2_1'),
        (0x4D0C, 'BluSwim_UNKNOWN2_2'),
        (0x4D29, 'BluSwim_UNKNOWN2_3'),
        (0x4D46, 'BluSwim_UNKNOWNDown_1'),
        (0x4D67, 'BluSwim_UNKNOWNDown_2'),
        (0x4D88, 'BluSwim_UNKNOWNDown_3'),
        
        (0x500D, 'Eidon_FaceDownRight'),
        (0x5026, 'Eidon_FaceDownLeft'),
        (0x503F, 'Eidon_FaceUpRight'),
        (0x5058, 'Eidon_FaceUpLeft'),
        (0x5071, 'Eidon_WalkDown1'),
        (0x5086, 'Eidon_FaceDown'),
        (0x509F, 'Eidon_WalkDown2'),
        (0x50B4, 'Eidon_WalkUp1'),
        (0x50CD, 'Eidon_FaceUp'),
        (0x50E6, 'Eidon_WalkUp2'),
        (0x50FF, 'Eidon_WalkRight1'),
        (0x5118, 'Eidon_FaceRight'),
        (0x5131, 'Eidon_WalkRight2'),
        (0x514A, 'Eidon_WalkLeft1'),
        (0x5163, 'Eidon_FaceLeft'),
        (0x517C, 'Eidon_WalkLeft2'),
        (0x5195, 'Eidon_Wave'),
        (0x51AE, 'Eidon_UNKNOWN'),

        (0x51BF, 'EidonWork_ChopRight1'),
        (0x51DC, 'EidonWork_ChopRight2'),
        (0x51FD, 'EidonWork_ChopRight3'),
        (0x521E, 'EidonWork_ChopLeft1'),
        (0x523B, 'EidonWork_ChopLeft2'),
        (0x525C, 'EidonWork_ChopLeft3'),
        (0x527D, 'EidonWork_UNKNOWN2_1'),
        (0x529A, 'EidonWork_UNKNOWN2_2'),
        (0x52B7, 'EidonWork_UNKNOWN1_1'),
        (0x52D4, 'EidonWork_UNKNOWN1_2'),
        (0x52F1, 'EidonWork_UNKNOWNDown_1'),
        (0x531A, 'EidonWork_UNKNOWNDown_2_FACEMAYBE'),
        (0x5347, 'EidonWork_UNKNOWNDown_3'),

        (0x5568, 'Evu_FaceDownRight'),
        (0x5581, 'Evu_FaceDownLeft'),
        (0x559A, 'Evu_FaceUpRight'),
        (0x55B3, 'Evu_FaceUpLeft'),
        (0x55CC, 'Evu_WalkDown1'),
        (0x55E5, 'Evu_FaceDown'),
        (0x55FE, 'Evu_WalkDown2'),
        (0x5617, 'Evu_WalkUp1'),
        (0x5630, 'Evu_FaceUp'),
        (0x5649, 'Evu_WalkUp2'),
        (0x5662, 'Evu_WalkRight'),
        (0x567B, 'Evu_FaceRight'),
        (0x5694, 'Evu_WalkLeft'),
        (0x56AD, 'Evu_FaceLeft'),
        
        (0x597D, 'Fossik_FaceDownRight'),
        (0x5996, 'Fossik_FaceDownLeft'),
        (0x59AF, 'Fossik_FaceUpRight'),
        (0x59C8, 'Fossik_FaceUpLeft'),
        (0x59E1, 'Fossik_WalkDown1'),
        (0x59FA, 'Fossik_FaceDown'),
        (0x5A13, 'Fossik_WalkDown2'),
        (0x5A2C, 'Fossik_WalkUp1'),
        (0x5A45, 'Fossik_FaceUp'),
        (0x5A5E, 'Fossik_WalkUp2'),
        (0x5A77, 'Fossik_WalkRight1'),
        (0x5A90, 'Fossik_FaceRight'),
        (0x5AA9, 'Fossik_WalkRight2'),
        (0x5AC2, 'Fossik_WalkLeft1'),
        (0x5ADB, 'Fossik_FaceLeft'),
        (0x5AF4, 'Fossik_WalkLeft2'),
        (0x5B0D, 'FossikRing_01'),
        (0x5B3E, 'FossikRing_02'),
        (0x5B6F, 'FossikRing_03'),
        (0x5BA0, 'FossikRing_04'),
        (0x5BD1, 'FossikRing_05'),
        (0x5C02, 'FossikRing_06'),
        (0x5C33, 'FossikRing_07'),
        (0x5C64, 'FossikRing_08'),
        (0x5C95, 'FossikRing_09'),
        (0x5CBE, 'FossikRing_10'),
        (0x5CE7, 'FossikRing_11'),
        (0x5D18, 'FossikRing_Idle'),
        
        (0x5EE6, 'Gia_FaceDownRight'),
        (0x5EFF, 'Gia_FaceDownLeft'),
        (0x5F18, 'Gia_FaceUpRight'),
        (0x5F29, 'Gia_FaceUpLeft'),
        (0x5F3A, 'Gia_WalkDown1'),
        (0x5F4F, 'Gia_FaceDown'),
        (0x5F68, 'Gia_WalkDown2'),
        (0x5F7D, 'Gia_WalkUp1'),
        (0x5F92, 'Gia_FaceUp'),
        (0x5FAB, 'Gia_WalkUp2'),
        (0x5FC0, 'Gia_WalkRight1'),
        (0x5FD5, 'Gia_FaceRight'),
        (0x5FEA, 'Gia_WalkRight2'),
        (0x5FFF, 'Gia_WalkLeft1'),
        (0x6014, 'Gia_FaceLeft'),
        (0x6029, 'Gia_WalkLeft2'),
        (0x603E, 'Gia_UNKNOWN'),
        
        (0x615C, 'Gogor_FaceDownRight'),
        (0x6175, 'Gogor_FaceDownLeft'),
        (0x618E, 'Gogor_FaceUpRight'),
        (0x61A7, 'Gogor_FaceUpLeft'),
        (0x61C0, 'Gogor_WalkDown1'),
        (0x61D9, 'Gogor_FaceDown'),
        (0x61F2, 'Gogor_WalkDown2'),
        (0x620B, 'Gogor_WalkUp1'),
        (0x6224, 'Gogor_FaceUp'),
        (0x623D, 'Gogor_WalkUp2'),
        (0x6256, 'Gogor_WalkRight1'),
        (0x626F, 'Gogor_FaceRight'),
        (0x6288, 'Gogor_WalkRight2'),
        (0x62A1, 'Gogor_WalkLeft1'),
        (0x62BA, 'Gogor_FaceLeft'),
        (0x62D3, 'Gogor_WalkLeft2'),
        (0x62EC, 'Gogor_PoseDownRight'),
        (0x6305, 'Gogor_PoseDownLeft'),
        (0x631E, 'Gogor_PoseUpRight'),
        (0x6337, 'Gogor_PoseUpLeft'),
        
        (0x647B, 'Gruk_FaceDownRight'),
        (0x6494, 'Gruk_FaceDownLeft'),
        (0x64AD, 'Gruk_FaceUpRight'),
        (0x64BE, 'Gruk_FaceUpLeft'),
        (0x64CF, 'Gruk_WalkDown1'),
        (0x64E4, 'Gruk_FaceDown'),
        (0x64FD, 'Gruk_WalkDown2'),
        (0x6512, 'Gruk_WalkUp1'),
        (0x652B, 'Gruk_FaceUp'),
        (0x6544, 'Gruk_WalkUp2'),
        (0x655D, 'Gruk_WalkRight1'),
        (0x6576, 'Gruk_FaceRight'),
        (0x6587, 'Gruk_WalkRight2'),
        (0x65A0, 'Gruk_WalkLeft1'),
        (0x65B9, 'Gruk_FaceLeft'),
        (0x65CA, 'Gruk_WalkLeft2'),
        
        (0x66E6, 'Josh_FaceDownRight'),
        (0x66FF, 'Josh_FaceDownLeft'),
        (0x6718, 'Josh_FaceUpRight'),
        (0x6731, 'Josh_FaceUpLeft'),
        (0x674A, 'Josh_WalkDown1'),
        (0x675F, 'Josh_FaceDown'),
        (0x6778, 'Josh_WalkDown2'),
        (0x678D, 'Josh_WalkUp1'),
        (0x67A6, 'Josh_FaceUp'),
        (0x67BF, 'Josh_WalkUp2'),
        (0x67D8, 'Josh_WalkRight1'),
        (0x67F1, 'Josh_FaceRight'),
        (0x6806, 'Josh_WalkRight2'),
        (0x681F, 'Josh_WalkLeft1'),
        (0x6838, 'Josh_FaceLeft'),
        (0x684D, 'Josh_WalkLeft2'),
        
        (0x6978, 'Sly_FaceDownRight'),
        (0x6991, 'Sly_FaceDownLeft'),
        (0x69AA, 'Sly_FaceUpRight'),
        (0x69C3, 'Sly_FaceUpLeft'),
        (0x69DC, 'Sly_WalkDown1'),
        (0x69F1, 'Sly_FaceDown'),
        (0x6A0A, 'Sly_WalkDown2'),
        (0x6A1F, 'Sly_WalkUp1'),
        (0x6A38, 'Sly_FaceUp'),
        (0x6A51, 'Sly_WalkUp2'),
        (0x6A6A, 'Sly_WalkRight1'),
        (0x6A83, 'Sly_FaceRight'),
        (0x6A98, 'Sly_WalkRight2'),
        (0x6AB1, 'Sly_WalkLeft1'),
        (0x6ACA, 'Sly_FaceLeft'),
        (0x6ADF, 'Sly_WalkLeft2'),
        
        (0x6C0A, 'Benny_FaceDownRight'),
        (0x6C23, 'Benny_FaceDownLeft'),
        (0x6C3C, 'Benny_FaceUpRight'),
        (0x6C55, 'Benny_FaceUpLeft'),
        (0x6C6E, 'Benny_WalkDown1'),
        (0x6C87, 'Benny_FaceDown'),
        (0x6CA0, 'Benny_WalkDown2'),
        (0x6CB9, 'Benny_WalkUp1'),
        (0x6CD2, 'Benny_FaceUp'),
        (0x6CEB, 'Benny_WalkUp2'),
        (0x6D04, 'Benny_WalkRight1'),
        (0x6D1D, 'Benny_FaceRight'),
        (0x6D36, 'Benny_WalkRight2'),
        (0x6D4F, 'Benny_WalkLeft1'),
        (0x6D68, 'Benny_FaceLeft'),
        (0x6D81, 'Benny_WalkLeft2'),
        
        (0x6E9D, 'Korg_FaceDownRight'),
        (0x6EB6, 'Korg_FaceDownLeft'),
        (0x6ECF, 'Korg_FaceUpRight'),
        (0x6EE8, 'Korg_FaceUpLeft'),
        (0x6F01, 'Korg_WalkDown1'),
        (0x6F16, 'Korg_FaceDown'),
        (0x6F2F, 'Korg_WalkDown2'),
        (0x6F44, 'Korg_WalkUp1'),
        (0x6F5D, 'Korg_FaceUp'),
        (0x6F76, 'Korg_WalkUp2'),
        (0x6F8F, 'Korg_WalkRight1'),
        (0x6FA8, 'Korg_FaceRight'),
        (0x6FBD, 'Korg_WalkRight2'),
        (0x6FD6, 'Korg_WalkLeft1'),
        (0x6FEF, 'Korg_FaceLeft'),
        (0x7004, 'Korg_WalkLeft2'),
        (0x701D, 'Korg_OuchRight'),
        (0x702E, 'Korg_OuchLeft'),
        (0x703F, 'KorgSwim_FloatRight1'),
        (0x7050, 'KorgSwim_FloatRight2'),
        (0x7061, 'KorgSwim_FloatLeft1'),
        (0x7072, 'KorgSwim_FloatLeft2'),
        (0x7083, 'KorgBattle_IdleDownRight'),
        (0x709C, 'KorgBattle_IdleDownLeft'),
        (0x70B5, 'KorgBattle_Victory'),
        (0x70CE, 'KorgBattle_Defeat'),
        (0x70E7, 'KorgBattle_Taunt1'),
        (0x7100, 'KorgBattle_Taunt4'),
        (0x713A, 'KorgBattle_Taunt2'),
        (0x711D, 'KorgBattle_Taunt3'),
        (0x7157, 'KorgBattle_Summon1'),
        (0x7170, 'KorgBattle_Summon2'),
        (0x718D, 'KorgBattle_Summon3'),
        (0x71AA, 'KorgBattle_IdleDown'),
        
        (0x738B, 'Korremar_FaceDownRight'),
        (0x73A4, 'Korremar_FaceDownLeft'),
        (0x73BD, 'Korremar_FaceUpRight'),
        (0x73D6, 'Korremar_FaceUpLeft'),
        (0x73EF, 'Korremar_WalkDown1'),
        (0x7404, 'Korremar_FaceDown'),
        (0x741D, 'Korremar_WalkDown2'),
        (0x7432, 'Korremar_WalkUp1'),
        (0x744B, 'Korremar_FaceUp'),
        (0x7464, 'Korremar_WalkUp2'),
        (0x747D, 'Korremar_WalkRight1'),
        (0x7496, 'Korremar_FaceRight'),
        (0x74AF, 'Korremar_WalkRight2'),
        (0x74C8, 'Korremar_WalkLeft1'),
        (0x74E1, 'Korremar_FaceLeft'),
        (0x74FA, 'Korremar_WalkLeft2'),
        (0x7513, 'KorremarBattle_IdleDownRight'),
        (0x752C, 'KorremarBattle_IdleDownLeft'),
        (0x7545, 'KorremarBattle_IdleDown'),
        (0x755E, 'KorremarBattle_Taunt1'),
        (0x7577, 'KorremarBattle_Taunt2'),
        (0x7590, 'KorremarBattle_Taunt3'),
        (0x75B1, 'KorremarBattle_Victory'),
        (0x75CA, 'KorremarBattle_Defeat'),
        (0x75EB, 'KorremarBattle_Summon1'),
        (0x7604, 'KorremarBattle_Summon2'),
        (0x7621, 'KorremarBattle_Summon3'),
        
        (0x77AD, 'Logan_FaceDownRight'),
        (0x77C6, 'Logan_FaceDownLeft'),
        (0x77DF, 'Logan_FaceUpRight'),
        (0x77F8, 'Logan_FaceUpLeft'),
        (0x7811, 'Logan_WalkDown1'),
        (0x782A, 'Logan_FaceDown'),
        (0x7843, 'Logan_WalkDown2'),
        (0x785C, 'Logan_WalkUp1'),
        (0x7875, 'Logan_FaceUp'),
        (0x788E, 'Logan_WalkUp2'),
        (0x78A7, 'Logan_WalkRight1'),
        (0x78C0, 'Logan_FaceRight'),
        (0x78D9, 'Logan_WalkRight2'),
        (0x78F2, 'Logan_WalkLeft1'),
        (0x790B, 'Logan_FaceLeft'),
        (0x7924, 'Logan_WalkLeft2'),
        
        (0x7A40, 'Zet_FaceDownRight'),
        (0x7A59, 'Zet_FaceDownLeft'),
        (0x7A72, 'Zet_FaceUpRight'),
        (0x7A8B, 'Zet_FaceUpLeft'),
        (0x7AA4, 'Zet_WalkDown1'),
        (0x7ABD, 'Zet_FaceDown'),
        (0x7AD6, 'Zet_WalkDown2'),
        (0x7AEF, 'Zet_WalkUp1'),
        (0x7B04, 'Zet_FaceUp'),
        (0x7B1D, 'Zet_WalkUp2'),
        (0x7B32, 'Zet_WalkRight1'),
        (0x7B4B, 'Zet_FaceRight'),
        (0x7B64, 'Zet_WalkRight2'),
        (0x7B7D, 'Zet_WalkLeft1'),
        (0x7B96, 'Zet_FaceLeft'),
        (0x7BAF, 'Zet_WalkLeft2'),
        (0x7BC8, 'Zet_BeatRight1'),
        (0x7BE9, 'Zet_BeatRight2'),
        (0x7C0A, 'Zet_BeatRight3'),
        (0x7C2B, 'Zet_BeatLeft1'),
        (0x7C4C, 'Zet_BeatLeft2'),
        (0x7C6D, 'Zet_BeatLeft3'),
        (0x7C8E, 'Zet_OuchLeft'),
        (0x7CA7, 'Zet_OuchRight'),
        (0x7CBC, 'ZetSwim_FloatRight1'),
        (0x7CCD, 'ZetSwim_FloatRight2'),
        (0x7CDE, 'ZetSwim_FloatLeft1'),
        (0x7CEF, 'ZetSwim_FloatLeft2'),
        (0x7D00, 'ZetBattle_IdleDown'),
        (0x7D19, 'ZetBattle_Taunt1'),
        (0x7D32, 'ZetBattle_Taunt2'),
        (0x7D4B, 'ZetBattle_IdleDownLeft'),
        (0x7D64, 'ZetBattle_IdleDownRight'),
        (0x7D7D, 'ZetBattle_Victory'),
        (0x7D96, 'ZetBattle_Defeat'),
        (0x7DAF, 'ZetBattle_Summon1'),
        (0x7DC8, 'ZetBattle_Summon2'),
        (0x7DE5, 'ZetBattle_Summon3'),
    ],
    'SCRIPT': [
        (0x4781, 'SCRIPT_ANIM_Agram_FaceDown'),
        (0x478B, 'SCRIPT_ANIM_Agram_FaceUp'),
        (0x4795, 'SCRIPT_ANIM_Agram_FaceLeft'),
        (0x479F, 'SCRIPT_ANIM_Agram_FaceRight'),
        (0x47A9, 'SCRIPT_ANIM_Agram_FaceUNKNOWNDIAGONAL1'),
        (0x47B3, 'SCRIPT_ANIM_Agram_FaceUNKNOWNDIAGONAL2'),
        (0x47BD, 'SCRIPT_ANIM_Agram_WalkUp'),
        (0x47CD, 'SCRIPT_ANIM_Agram_WalkDown'),
        (0x47DD, 'SCRIPT_ANIM_Agram_WalkRight'),
        (0x47ED, 'SCRIPT_ANIM_Agram_WalkLeft'),
        (0x481D, '.Loop'),
        (0x4868, '.Loop'),
        (0x487E, 'SCRIPT_ANIM_AgramBattle_Anguish'),
        (0x488A, '.Loop'),
        (0x4894, 'SCRIPT_ANIM_AgramBattle_FadeOut'),
        
        (0x4B05, 'SCRIPT_ANIM_Blu_WalkUp'),
        (0x4B15, 'SCRIPT_ANIM_Blu_WalkDown'),
        (0x4B25, 'SCRIPT_ANIM_Blu_WalkLeft'),
        (0x4B35, 'SCRIPT_ANIM_Blu_WalkRight'),
        (0x4B45, 'SCRIPT_ANIM_Blu_RunUp'),
        (0x4B55, 'SCRIPT_ANIM_Blu_RunDown'),
        (0x4B65, 'SCRIPT_ANIM_Blu_RunLeft'),
        (0x4B75, 'SCRIPT_ANIM_Blu_RunRight'),
        (0x4B85, 'SCRIPT_ANIM_Blu_FaceUp'),
        (0x4B8F, 'SCRIPT_ANIM_Blu_FaceDown'),
        (0x4B99, 'SCRIPT_ANIM_Blu_FaceLeft'),
        (0x4BA3, 'SCRIPT_ANIM_Blu_FaceRight'),
        (0x4BAD, 'SCRIPT_ANIM_Blu_FaceUpLeft'),
        (0x4BB7, 'SCRIPT_ANIM_Blu_FaceUpRight'),
        (0x4BC1, 'SCRIPT_ANIM_Blu_FaceDownLeft'),
        (0x4BCB, 'SCRIPT_ANIM_Blu_FaceDownRight'),
        (0x4BD5, 'SCRIPT_ANIM_Blu_FaceHero'),
        (0x4BEC, '.FaceUp'),
        (0x4BF3, '.FaceDown'),
        (0x4BFA, '.FaceLeft'),
        (0x4C01, '.FaceRight'),

        (0x4DA9, 'SCRIPT_ANIM_BluSwim_FloatUp'),
        (0x4DB5, 'SCRIPT_ANIM_BluSwim_FloatDown'),
        (0x4DC1, 'SCRIPT_ANIM_BluSwim_FloatRight'),
        (0x4DCD, 'SCRIPT_ANIM_BluSwim_FloatLeft'),
        (0x4DD9, 'SCRIPT_ANIM_BluSwim_SwimUp'),
        (0x4E56, 'SCRIPT_ANIM_BluSwim_SwimDown'),
        (0x4ED3, 'SCRIPT_ANIM_BluSwim_SwimLeft'),
        (0x4F50, 'SCRIPT_ANIM_BluSwim_SwimRight'),
        (0x4FCD, 'SCRIPT_ANIM_BluSwim_UNKNOWNLeft'),
        (0x4FD5, 'SCRIPT_ANIM_BluSwim_UNKNOWNRight'),
        (0x4FDD, 'SCRIPT_ANIM_BluSwim_UNKNOWN1'),
        (0x4FED, 'SCRIPT_ANIM_BluSwim_UNKNOWN2'),
        (0x4FFD, 'SCRIPT_ANIM_BluSwim_UNKNOWNDown'),
        
        (0x5370, 'SCRIPT_ANIM_Eidon_WalkUp'),
        (0x5380, 'SCRIPT_ANIM_Eidon_WalkDown'),
        (0x5390, 'SCRIPT_ANIM_Eidon_WalkLeft'),
        (0x53A0, 'SCRIPT_ANIM_Eidon_WalkRight'),
        (0x53B0, 'SCRIPT_ANIM_Eidon_RunUp'),
        (0x53C0, 'SCRIPT_ANIM_Eidon_RunDown'),
        (0x53D0, 'SCRIPT_ANIM_Eidon_RunLeft'),
        (0x53E0, 'SCRIPT_ANIM_Eidon_RunRight'),
        (0x53F0, 'SCRIPT_ANIM_Eidon_FaceUp'),
        (0x53FA, 'SCRIPT_ANIM_Eidon_FaceDown'),
        (0x5404, 'SCRIPT_ANIM_Eidon_FaceLeft'),
        (0x540E, 'SCRIPT_ANIM_Eidon_FaceRight'),
        (0x5418, 'SCRIPT_ANIM_Eidon_FaceUpLeft'),
        (0x5422, 'SCRIPT_ANIM_Eidon_FaceUpRight'),
        (0x542C, 'SCRIPT_ANIM_Eidon_FaceDownLeft'),
        (0x5436, 'SCRIPT_ANIM_Eidon_FaceDownRight'),
        (0x5440, 'SCRIPT_ANIM_Eidon_UNKNOWN'),
        (0x544A, 'SCRIPT_ANIM_Eidon_Wave'),
        (0x5454, 'SCRIPT_ANIM_Eidon_Charades'),
        (0x54A9, 'SCRIPT_ANIM_EidonWork_ChopRight'),
        (0x54BD, 'SCRIPT_ANIM_EidonWork_ChopLeft'),
        (0x54D1, 'SCRIPT_ANIM_EidonWork_UNKNOWNChopLeft'),
        (0x54DB, 'SCRIPT_ANIM_EidonWork_ChopChopRight'),
        (0x54EA, 'SCRIPT_ANIM_EidonWork_ChopChopLeft'),
        (0x54F9, 'SCRIPT_ANIM_EidonWork_UNKNOWN1'),
        (0x5500, '.Loop'),
        (0x550A, 'SCRIPT_ANIM_EidonWork_UNKNOWN2'),
        (0x5511, '.Loop'),
        (0x551B, 'SCRIPT_ANIM_EidonWork_UNKNOWNDown1'),
        (0x552B, 'SCRIPT_ANIM_EidonWork_UNKNOWNDown2'),
        (0x5535, 'SCRIPT_ANIM_Eidon_FaceHero'),
        (0x554C, '.FaceUp'),
        (0x5553, '.FaceDown'),
        (0x555A, '.FaceLeft'),
        (0x5561, '.FaceRight'),
        
        (0x56C6, 'SCRIPT_ANIM_Evu_WalkUp'),
        (0x576B, 'SCRIPT_ANIM_Evu_WalkDown'),
        (0x5810, 'SCRIPT_ANIM_Evu_WalkLeft'),
        (0x5865, 'SCRIPT_ANIM_Evu_WalkRight'),
        (0x58BA, 'SCRIPT_ANIM_Evu_RunUp'),
        (0x58CA, 'SCRIPT_ANIM_Evu_RunDown'),
        (0x58DA, 'SCRIPT_ANIM_Evu_RunLeft'),
        (0x58EA, 'SCRIPT_ANIM_Evu_RunRight'),
        (0x58FA, 'SCRIPT_ANIM_Evu_FaceUp'),
        (0x5904, 'SCRIPT_ANIM_Evu_FaceDown'),
        (0x590E, 'SCRIPT_ANIM_Evu_FaceLeft'),
        (0x5918, 'SCRIPT_ANIM_Evu_FaceRight'),
        (0x5922, 'SCRIPT_ANIM_Evu_FaceUpLeft'),
        (0x592C, 'SCRIPT_ANIM_Evu_FaceUpRight'),
        (0x5936, 'SCRIPT_ANIM_Evu_FaceDownLeft'),
        (0x5940, 'SCRIPT_ANIM_Evu_FaceDownRight'),
        (0x594A, 'SCRIPT_ANIM_Evu_FaceHero'),
        (0x5961, '.FaceUp'),
        (0x5968, '.FaceDown'),
        (0x596F, '.FaceLeft'),
        (0x5976, '.FaceRight'),
        
        (0x5D49, 'SCRIPT_ANIM_Fossik_WalkUp'),
        (0x5D59, 'SCRIPT_ANIM_Fossik_WalkDown'),
        (0x5D69, 'SCRIPT_ANIM_Fossik_WalkLeft'),
        (0x5D79, 'SCRIPT_ANIM_Fossik_WalkRight'),
        (0x5D89, 'SCRIPT_ANIM_Fossik_RunUp'),
        (0x5D99, 'SCRIPT_ANIM_Fossik_RunDown'),
        (0x5DA9, 'SCRIPT_ANIM_Fossik_RunLeft'),
        (0x5DB9, 'SCRIPT_ANIM_Fossik_RunRight'),
        (0x5DC9, 'SCRIPT_ANIM_Fossik_FaceUp'),
        (0x5DD3, 'SCRIPT_ANIM_Fossik_FaceDown'),
        (0x5DDD, 'SCRIPT_ANIM_Fossik_FaceLeft'),
        (0x5DE7, 'SCRIPT_ANIM_Fossik_FaceRight'),
        (0x5DF1, 'SCRIPT_ANIM_Fossik_FaceUpLeft'),
        (0x5DFB, 'SCRIPT_ANIM_Fossik_FaceUpRight'),
        (0x5E05, 'SCRIPT_ANIM_Fossik_FaceDownLeft'),
        (0x5E0F, 'SCRIPT_ANIM_Fossik_FaceDownRight'),
        (0x5E19, 'SCRIPT_ANIM_FossikRing_MakeRing'),
        (0x5E9D, '.Loop'),
        (0x5EA8, 'SCRIPT_ANIM_FossikRing_Idle'),
        (0x5EB3, 'SCRIPT_ANIM_Fossik_FaceHero'),
        (0x5ECA, '.FaceUp'),
        (0x5ED1, '.FaceDown'),
        (0x5ED8, '.FaceLeft'),
        (0x5EDF, '.FaceRight'),
        
        (0x604F, 'SCRIPT_ANIM_Gia_WalkUp'),
        (0x605F, 'SCRIPT_ANIM_Gia_WalkDown'),
        (0x606F, 'SCRIPT_ANIM_Gia_WalkLeft'),
        (0x607F, 'SCRIPT_ANIM_Gia_WalkRight'),
        (0x608F, 'SCRIPT_ANIM_Gia_RunUp'),
        (0x609F, 'SCRIPT_ANIM_Gia_RunDown'),
        (0x60AF, 'SCRIPT_ANIM_Gia_RunLeft'),
        (0x60BF, 'SCRIPT_ANIM_Gia_RunRight'),
        (0x60CF, 'SCRIPT_ANIM_Gia_FaceUp'),
        (0x60D9, 'SCRIPT_ANIM_Gia_FaceDown'),
        (0x60E3, 'SCRIPT_ANIM_Gia_FaceLeft'),
        (0x60ED, 'SCRIPT_ANIM_Gia_FaceRight'),
        (0x60F7, 'SCRIPT_ANIM_Gia_FaceUpLeft'),
        (0x6101, 'SCRIPT_ANIM_Gia_FaceUpRight'),
        (0x610B, 'SCRIPT_ANIM_Gia_FaceDownLeft'),
        (0x6115, 'SCRIPT_ANIM_Gia_FaceDownRight'),
        (0x611F, 'SCRIPT_ANIM_Gia_UNKNOWN'),
        (0x6129, 'SCRIPT_ANIM_Gia_FaceHero'),
        (0x6140, '.FaceUp'),
        (0x6147, '.FaceDown'),
        (0x614E, '.FaceLeft'),
        (0x6155, '.FaceRight'),
        
        (0x6350, 'SCRIPT_ANIM_Gogor_WalkUp'),
        (0x6360, 'SCRIPT_ANIM_Gogor_WalkDown'),
        (0x6370, 'SCRIPT_ANIM_Gogor_WalkLeft'),
        (0x6380, 'SCRIPT_ANIM_Gogor_WalkRight'),
        (0x6390, 'SCRIPT_ANIM_Gogor_RunUp'),
        (0x63A0, 'SCRIPT_ANIM_Gogor_RunDown'),
        (0x63B0, 'SCRIPT_ANIM_Gogor_RunLeft'),
        (0x63C0, 'SCRIPT_ANIM_Gogor_RunRight'),
        (0x63D0, 'SCRIPT_ANIM_Gogor_FaceUp'),
        (0x63DA, 'SCRIPT_ANIM_Gogor_FaceDown'),
        (0x63E4, 'SCRIPT_ANIM_Gogor_FaceLeft'),
        (0x63EE, 'SCRIPT_ANIM_Gogor_FaceRight'),
        (0x63F8, 'SCRIPT_ANIM_Gogor_FaceUpLeft'),
        (0x6402, 'SCRIPT_ANIM_Gogor_FaceUpRight'),
        (0x640C, 'SCRIPT_ANIM_Gogor_FaceDownLeft'),
        (0x6416, 'SCRIPT_ANIM_Gogor_FaceDownRight'),
        (0x6420, 'SCRIPT_ANIM_Gogor_PoseUpLeft'),
        (0x642A, 'SCRIPT_ANIM_Gogor_PoseUpRight'),
        (0x6434, 'SCRIPT_ANIM_Gogor_PoseDownLeft'),
        (0x643E, 'SCRIPT_ANIM_Gogor_PoseDownRight'),
        (0x6448, 'SCRIPT_ANIM_Gogor_FaceHero'),
        (0x645F, '.FaceUp'),
        (0x6466, '.FaceDown'),
        (0x646D, '.FaceLeft'),
        (0x6474, '.FaceRight'),
        
        (0x65E3, 'SCRIPT_ANIM_Gruk_WalkUp'),
        (0x65F3, 'SCRIPT_ANIM_Gruk_WalkDown'),
        (0x6603, 'SCRIPT_ANIM_Gruk_WalkLeft'),
        (0x6613, 'SCRIPT_ANIM_Gruk_WalkRight'),
        (0x6623, 'SCRIPT_ANIM_Gruk_RunUp'),
        (0x6633, 'SCRIPT_ANIM_Gruk_RunDown'),
        (0x6643, 'SCRIPT_ANIM_Gruk_RunLeft'),
        (0x6653, 'SCRIPT_ANIM_Gruk_RunRight'),
        (0x6663, 'SCRIPT_ANIM_Gruk_FaceUp'),
        (0x666D, 'SCRIPT_ANIM_Gruk_FaceDown'),
        (0x6677, 'SCRIPT_ANIM_Gruk_FaceLeft'),
        (0x6681, 'SCRIPT_ANIM_Gruk_FaceRight'),
        (0x668B, 'SCRIPT_ANIM_Gruk_FaceUpLeft'),
        (0x6695, 'SCRIPT_ANIM_Gruk_FaceUpRight'),
        (0x669F, 'SCRIPT_ANIM_Gruk_FaceDownLeft'),
        (0x66A9, 'SCRIPT_ANIM_Gruk_FaceDownRight'),
        (0x66B3, 'SCRIPT_ANIM_Gruk_FaceHero'),
        (0x66CA, '.FaceUp'),
        (0x66D1, '.FaceDown'),
        (0x66D8, '.FaceLeft'),
        (0x66DF, '.FaceRight'),
        
        (0x6866, 'SCRIPT_ANIM_Josh_WalkUp'),
        (0x6876, 'SCRIPT_ANIM_Josh_WalkDown'),
        (0x6886, 'SCRIPT_ANIM_Josh_WalkLeft'),
        (0x6896, 'SCRIPT_ANIM_Josh_WalkRight'),
        (0x68A6, 'SCRIPT_ANIM_Josh_RunUp'),
        (0x68B6, 'SCRIPT_ANIM_Josh_RunDown'),
        (0x68C6, 'SCRIPT_ANIM_Josh_RunLeft'),
        (0x68D6, 'SCRIPT_ANIM_Josh_RunRight'),
        (0x68E6, 'SCRIPT_ANIM_Josh_FaceUp'),
        (0x68F0, 'SCRIPT_ANIM_Josh_FaceDown'),
        (0x68FA, 'SCRIPT_ANIM_Josh_FaceLeft'),
        (0x6904, 'SCRIPT_ANIM_Josh_FaceRight'),
        (0x690E, 'SCRIPT_ANIM_Josh_FaceUpLeft'),
        (0x6918, 'SCRIPT_ANIM_Josh_FaceUpRight'),
        (0x6922, 'SCRIPT_ANIM_Josh_FaceDownLeft'),
        (0x692C, 'SCRIPT_ANIM_Josh_FaceDownRight'),
        (0x6936, 'SCRIPT_ANIM_Josh_GlideBackwardsDown'),
        (0x6945, 'SCRIPT_ANIM_Josh_FaceHero'),
        (0x695C, '.FaceUp'),
        (0x6963, '.FaceDown'),
        (0x696A, '.FaceLeft'),
        (0x6971, '.FaceRight'),
        
        (0x6AF8, 'SCRIPT_ANIM_Sly_WalkUp'),
        (0x6B08, 'SCRIPT_ANIM_Sly_WalkDown'),
        (0x6B18, 'SCRIPT_ANIM_Sly_WalkLeft'),
        (0x6B28, 'SCRIPT_ANIM_Sly_WalkRight'),
        (0x6B38, 'SCRIPT_ANIM_Sly_RunUp'),
        (0x6B48, 'SCRIPT_ANIM_Sly_RunDown'),
        (0x6B58, 'SCRIPT_ANIM_Sly_RunLeft'),
        (0x6B68, 'SCRIPT_ANIM_Sly_RunRight'),
        (0x6B78, 'SCRIPT_ANIM_Sly_FaceUp'),
        (0x6B82, 'SCRIPT_ANIM_Sly_FaceDown'),
        (0x6B8C, 'SCRIPT_ANIM_Sly_FaceLeft'),
        (0x6B96, 'SCRIPT_ANIM_Sly_FaceRight'),
        (0x6BA0, 'SCRIPT_ANIM_Sly_FaceUpLeft'),
        (0x6BAA, 'SCRIPT_ANIM_Sly_FaceUpRight'),
        (0x6BB4, 'SCRIPT_ANIM_Sly_FaceDownLeft'),
        (0x6BBE, 'SCRIPT_ANIM_Sly_FaceDownRight'),
        (0x6BC8, 'SCRIPT_ANIM_Sly_GlideBackwardsDown'),
        (0x6BD7, 'SCRIPT_ANIM_Sly_FaceHero'),
        (0x6BEE, '.FaceUp'),
        (0x6BF5, '.FaceDown'),
        (0x6BFC, '.FaceLeft'),
        (0x6C03, '.FaceRight'),
        
        (0x6D9A, 'SCRIPT_ANIM_Benny_WalkUp'),
        (0x6DAA, 'SCRIPT_ANIM_Benny_WalkDown'),
        (0x6DBA, 'SCRIPT_ANIM_Benny_WalkLeft'),
        (0x6DCA, 'SCRIPT_ANIM_Benny_WalkRight'),
        (0x6DDA, 'SCRIPT_ANIM_Benny_RunUp'),
        (0x6DEA, 'SCRIPT_ANIM_Benny_RunDown'),
        (0x6DFA, 'SCRIPT_ANIM_Benny_RunLeft'),
        (0x6E0A, 'SCRIPT_ANIM_Benny_RunRight'),
        (0x6E1A, 'SCRIPT_ANIM_Benny_FaceUp'),
        (0x6E24, 'SCRIPT_ANIM_Benny_FaceDown'),
        (0x6E2E, 'SCRIPT_ANIM_Benny_FaceLeft'),
        (0x6E38, 'SCRIPT_ANIM_Benny_FaceRight'),
        (0x6E42, 'SCRIPT_ANIM_Benny_FaceUpLeft'),
        (0x6E4C, 'SCRIPT_ANIM_Benny_FaceUpRight'),
        (0x6E56, 'SCRIPT_ANIM_Benny_FaceDownLeft'),
        (0x6E60, 'SCRIPT_ANIM_Benny_FaceDownRight'),
        (0x6E6A, 'SCRIPT_ANIM_Benny_FaceHero'),
        (0x6E81, '.FaceUp'),
        (0x6E88, '.FaceDown'),
        (0x6E8F, '.FaceLeft'),
        (0x6E96, '.FaceRight'),
        
        (0x71C3, 'SCRIPT_ANIM_Korg_WalkUp'),
        (0x71D3, 'SCRIPT_ANIM_Korg_WalkDown'),
        (0x71E3, 'SCRIPT_ANIM_Korg_WalkLeft'),
        (0x71F3, 'SCRIPT_ANIM_Korg_WalkRight'),
        (0x7203, 'SCRIPT_ANIM_Korg_RunUp'),
        (0x7213, 'SCRIPT_ANIM_Korg_RunDown'),
        (0x7223, 'SCRIPT_ANIM_Korg_RunLeft'),
        (0x7233, 'SCRIPT_ANIM_Korg_RunRight'),
        (0x7243, 'SCRIPT_ANIM_Korg_FaceUp'),
        (0x724D, 'SCRIPT_ANIM_Korg_FaceDown'),
        (0x7257, 'SCRIPT_ANIM_Korg_FaceLeft'),
        (0x7261, 'SCRIPT_ANIM_Korg_FaceRight'),
        (0x726B, 'SCRIPT_ANIM_Korg_FaceUpLeft'),
        (0x7275, 'SCRIPT_ANIM_Korg_FaceUpRight'),
        (0x727F, 'SCRIPT_ANIM_Korg_FaceDownLeft'),
        (0x7289, 'SCRIPT_ANIM_Korg_FaceDownRight'),
        (0x7293, 'SCRIPT_ANIM_Korg_BeatLeft'),
        (0x729D, 'SCRIPT_ANIM_Korg_BeatRight'),
        (0x72A7, 'SCRIPT_ANIM_Korg_FlyAway'),
        (0x72B3, 'SCRIPT_ANIM_Korg_FallDown'),
        (0x72BF, 'SCRIPT_ANIM_KorgSwim_FloatLeft'),
        (0x72CB, 'SCRIPT_ANIM_KorgSwim_FloatRight'),
        (0x72FC, '.Loop'),
        (0x7358, 'SCRIPT_ANIM_Korg_FaceHero'),
        (0x736F, '.FaceUp'),
        (0x7376, '.FaceDown'),
        (0x737D, '.FaceLeft'),
        (0x7384, '.FaceRight'),
        
        (0x763E, 'SCRIPT_ANIM_Korremar_WalkUp'),
        (0x764E, 'SCRIPT_ANIM_Korremar_WalkDown'),
        (0x765E, 'SCRIPT_ANIM_Korremar_WalkLeft'),
        (0x766E, 'SCRIPT_ANIM_Korremar_WalkRight'),
        (0x767E, 'SCRIPT_ANIM_Korremar_RunUp'),
        (0x768E, 'SCRIPT_ANIM_Korremar_RunDown'),
        (0x769E, 'SCRIPT_ANIM_Korremar_RunLeft'),
        (0x76AE, 'SCRIPT_ANIM_Korremar_RunRight'),
        (0x76BE, 'SCRIPT_ANIM_Korremar_FaceUp'),
        (0x76C8, 'SCRIPT_ANIM_Korremar_FaceDown'),
        (0x76D2, 'SCRIPT_ANIM_Korremar_FaceLeft'),
        (0x76DC, 'SCRIPT_ANIM_Korremar_FaceRight'),
        (0x76E6, 'SCRIPT_ANIM_Korremar_FaceUpLeft'),
        (0x76F0, 'SCRIPT_ANIM_Korremar_FaceUpRight'),
        (0x76FA, 'SCRIPT_ANIM_Korremar_FaceDownLeft'),
        (0x7704, 'SCRIPT_ANIM_Korremar_FaceDownRight'),
        (0x777A, 'SCRIPT_ANIM_Korremar_FaceHero'),
        (0x7791, '.FaceUp'),
        (0x7798, '.FaceDown'),
        (0x779F, '.FaceLeft'),
        (0x77A6, '.FaceRight'),
        
        (0x793D, 'SCRIPT_ANIM_Logan_WalkUp'),
        (0x794D, 'SCRIPT_ANIM_Logan_WalkDown'),
        (0x795D, 'SCRIPT_ANIM_Logan_WalkLeft'),
        (0x796D, 'SCRIPT_ANIM_Logan_WalkRight'),
        (0x797D, 'SCRIPT_ANIM_Logan_RunUp'),
        (0x798D, 'SCRIPT_ANIM_Logan_RunDown'),
        (0x799D, 'SCRIPT_ANIM_Logan_RunLeft'),
        (0x79AD, 'SCRIPT_ANIM_Logan_RunRight'),
        (0x79BD, 'SCRIPT_ANIM_Logan_FaceUp'),
        (0x79C7, 'SCRIPT_ANIM_Logan_FaceDown'),
        (0x79D1, 'SCRIPT_ANIM_Logan_FaceLeft'),
        (0x79DB, 'SCRIPT_ANIM_Logan_FaceRight'),
        (0x79E5, 'SCRIPT_ANIM_Logan_FaceUpLeft'),
        (0x79EF, 'SCRIPT_ANIM_Logan_FaceUpRight'),
        (0x79F9, 'SCRIPT_ANIM_Logan_FaceDownLeft'),
        (0x7A03, 'SCRIPT_ANIM_Logan_FaceDownRight'),
        (0x7A0D, 'SCRIPT_ANIM_Logan_FaceHero'),
        (0x7A24, '.FaceUp'),
        (0x7A2B, '.FaceDown'),
        (0x7A32, '.FaceLeft'),
        (0x7A39, '.FaceRight'),
        
        (0x7E02, 'SCRIPT_ANIM_Zet_WalkUp'),
        (0x7E12, 'SCRIPT_ANIM_Zet_WalkDown'),
        (0x7E22, 'SCRIPT_ANIM_Zet_WalkLeft'),
        (0x7E32, 'SCRIPT_ANIM_Zet_WalkRight'),
        (0x7E42, 'SCRIPT_ANIM_Zet_RunUp'),
        (0x7E52, 'SCRIPT_ANIM_Zet_RunDown'),
        (0x7E62, 'SCRIPT_ANIM_Zet_RunLeft'),
        (0x7E72, 'SCRIPT_ANIM_Zet_RunRight'),
        (0x7E82, 'SCRIPT_ANIM_Zet_FaceUp'),
        (0x7E8C, 'SCRIPT_ANIM_Zet_FaceDown'),
        (0x7E96, 'SCRIPT_ANIM_Zet_FaceLeft'),
        (0x7EA0, 'SCRIPT_ANIM_Zet_FaceRight'),
        (0x7EAA, 'SCRIPT_ANIM_Zet_FaceUpLeft'),
        (0x7EB4, 'SCRIPT_ANIM_Zet_FaceUpRight'),
        (0x7EBE, 'SCRIPT_ANIM_Zet_FaceDownLeft'),
        (0x7EC8, 'SCRIPT_ANIM_Zet_FaceDownRight'),
        (0x7ED2, 'SCRIPT_ANIM_Zet_BeatLeft'),
        (0x7EE0, 'SCRIPT_ANIM_Zet_BeatRight'),
        (0x7EEE, 'SCRIPT_ANIM_Zet_FlyAway'),
        (0x7EFA, 'SCRIPT_ANIM_Zet_FallDown'),
        (0x7F06, 'SCRIPT_ANIM_Zet_Spin'),
        (0x7F16, 'SCRIPT_ANIM_Zet_KnockedRight'),
        (0x7F20, 'SCRIPT_ANIM_Zet_KnockedLeft'),
        (0x7F2A, 'SCRIPT_ANIM_ZetSwim_FloatLeft'),
        (0x7F36, 'SCRIPT_ANIM_ZetSwim_FloatRight'),
        (0x7F62, '.Loop'),
        (0x7FB1, 'SCRIPT_ANIM_ZetBattle_FadeOut'),
        (0x7FBC, 'SCRIPT_ANIM_Zet_FaceHero'),
        (0x7FD3, '.FaceUp'),
        (0x7FDA, '.FaceDown'),
        (0x7FE1, '.FaceLeft'),
        (0x7FE8, '.FaceRight'),
    ],
    'DELETELABELS': [
        0x5768
    ]
}


def setupSpriteAnim(bank, debug):
    params = sprite_anim_params[bank]
    start = BankAddress(bank, params['START'])
    end = BankAddress(bank, params['END'])
    for addr, label in params['SPRITE']:
        sym.replaceSymbol(bank, addr, 'SPRITE_' + label)
    for addr, label in params['SCRIPT']:
        sym.replaceSymbol(bank, addr, label)
    for addr in params['DELETELABELS']:
        sym.delSymbol(bank, addr)
    return magireader.interpretSpriteAnim(start, end, sym, debug)


table = MainTable(rom)
with open(config.outdir + 'tempbattle.asm', 'w') as f:
    f.write(table.getOutput())
setupSpriteAnim(0x0E, True)

# print(sym.getSymbol(0x20, 0x74C8, 'X'))

# for magitable in table.magitables:
#     print(magitable.anims)
#     start = magitable.anims[0]
#     if magitable.name in MagiTable.END_ADDRESSES:
#         end = MagiTable.END_ADDRESSES[magitable.name]
#     else:
#         end = start + 0x200
#     print(magireader.interpret(magitable.anims[0], end, sym))
#     input()
