    db 30        ; wTilemap_Width
    dw $010E     ; wTilemap_YMapPad
    db 19        ;
    db 10        ; wTilemap_VStop
    dw $0258     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/exit_unused1/Naroom_Forest_Exit_UNUSED1.metatile.tilemap.rle"