    db 36        ;wTilemap_Width
    dw $0438     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/vaultentrance/Orothe_Tunnels_VaultEntrance.collision.tilemap.rle"