    db 36        ; wTilemap_Width
    dw $0144     ;wTilemap_YMapPad
    db 25        ;
    db 20        ;wTilemap_VStop
    dw $0438     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/vaultentrance/Orothe_Tunnels_VaultEntrance.metatile.tilemap.rle"