    db 16        ;wTilemap_Width
    dw $0090     ;wTilemap_YMapPad
    db 5         ;
    db 6         ;wTilemap_VStop
    dw $0100     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/middle/house_basementroom/Arderial_Middle_House_BasementRoom.metatile.tilemap.rle"