    db 16        ;wTilemap_Width
    dw $0100     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/middle/house_basementroom/Arderial_Middle_House_BasementRoom.collision.tilemap.rle"