    db 50        ;wTilemap_Width
    dw $09C4     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/glade/field/Naroom_Glade_Field.collision.tilemap.rle"