    db 12        ;wTilemap_Width
    dw $0090     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/glade/cave_exterior/Naroom_Glade_Cave_Exterior.collision.tilemap.rle"