    db 12        ; wTilemap_Width
    dw $0078     ; Uncompressed file size (excluding header)
    ; The imported file size was actually $007B because 3 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/misc/startscreen/main/MASK_Misc_StartScreen_Main.collision.tilemap.rle"