    db 12        ;wTilemap_Width
    dw $0078     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/misc/startscreen/main/Misc_StartScreen_Main.collision.tilemap.rle"