    db 12        ; wTilemap_Width
    dw $00A8     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/middle_southpathway_screwroom/Core_Shadowhold_Middle_SouthPathway_ScrewRoom.collision.tilemap.rle"