    db 30        ; wTilemap_Width
    dw $0384     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/geyser/entrance/Cald_Geyser_Entrance.collision.tilemap.rle"