    db 16        ; wTilemap_Width
    dw $01E0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/palace/secondfloorroom/Arderial_Palace_SecondFloorRoom.collision.tilemap.rle"