    db 30        ;wTilemap_Width
    dw $010E     ;wTilemap_YMapPad
    db 19        ;
    db 2         ;wTilemap_VStop
    dw $0168     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/misc/startscreen/pathway/Misc_StartScreen_Pathway.metatile.tilemap.rle"