    db 30        ;wTilemap_Width
    dw $0168     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/misc/startscreen/pathway/Misc_StartScreen_Pathway.collision.tilemap.rle"