    db 45        ;wTilemap_Width
    dw $0546     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/easttunnel/pathwayfort/Underneath_EastTunnel_PathwayFort.collision.tilemap.rle"