    db 18        ;wTilemap_Width
    dw $0132     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/end/antechamber/Core_End_Antechamber.collision.tilemap.rle"