    db 16        ; wTilemap_Width
    dw $0200     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/geyser/north/Orothe_Geyser_North.collision.tilemap.rle"