    db 24        ; wTilemap_Width
    dw $0240     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/geyser/east/Naroom_Geyser_East.collision.tilemap.rle"