    db 18        ; wTilemap_Width
    dw $00A2     ; wTilemap_YMapPad
    db 7         ;
    db 0         ; wTilemap_VStop
    dw $00B4     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/northwest/Naroom_Vash_Northwest.metatile.tilemap.rle"