    db 18        ; wTilemap_Width
    dw $00B4     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/northwest/Naroom_Vash_Northwest.collision.tilemap.rle"