    db 12        ; wTilemap_Width
    dw $006C     ; wTilemap_YMapPad
    db 1         ;
    db 8         ; wTilemap_VStop
    dw $00D8     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/west_innroom/Cald_Ashyn_West_InnRoom.metatile.tilemap.rle"