    db 12        ;wTilemap_Width
    dw $00D8     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/west_innroom/Cald_Ashyn_West_InnRoom.collision.tilemap.rle"