    db 30        ; wTilemap_Width
    dw $010E     ; wTilemap_YMapPad
    db 19        ;
    db 13        ; wTilemap_VStop
    dw $02B2     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/fort/unused/Arderial_Fort_UNUSED.metatile.tilemap.rle"