    db 60        ; wTilemap_Width
    dw $04B0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/weave/exit/Naroom_Weave_Exit.collision.tilemap.rle"