    db 12        ;wTilemap_Width
    dw $0090     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/north_spookyroom_normal/Naroom_Vash_North_SpookyRoom_Normal.collision.tilemap.rle"