    db 24        ;wTilemap_Width
    dw $0240     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/middle_firstpathway/Core_Shadowhold_Middle_FirstPathway.collision.tilemap.rle"