
    ; Uncompressed card tilesets
    ; 51/51 used. No room for more but can be placed in any other bank.

    ; $4000
BITMAP_Cardscene_TimberHyrn::
    INCBIN "autogenerated/assets/cardscene/cards/TimberHyrn.tileset"
    ; $4140
BITMAP_Cardscene_Cyclone_Vashp_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Cyclone_Vashp.tileset"
    ; $4280
BITMAP_Cardscene_Vashp::
    INCBIN "autogenerated/assets/cardscene/cards/Vashp.tileset"
    ; $43C0
BITMAP_Cardscene_Shryque::
    INCBIN "autogenerated/assets/cardscene/cards/Shryque.tileset"
    ; $4500
BITMAP_Cardscene_ShadwVinoc::
    INCBIN "autogenerated/assets/cardscene/cards/ShadwVinoc.tileset"
    ; $4640
BITMAP_Cardscene_ThundrHyrn::
    INCBIN "autogenerated/assets/cardscene/cards/ThundrHyrn.tileset"
    ; $4780
BITMAP_Cardscene_Sphor::
    INCBIN "autogenerated/assets/cardscene/cards/Sphor.tileset"
    ; $48C0
BITMAP_Cardscene_Stagadan_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Stagadan.tileset"
    ; $4A00
BITMAP_Cardscene_Wudge_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Wudge.tileset"
    ; $4B40
BITMAP_Cardscene_Wellisk_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Wellisk.tileset"
    ; $4C80
BITMAP_Cardscene_Yvohcna::
    INCBIN "autogenerated/assets/cardscene/cards/Yvohcna.tileset"
    ; $4DC0
BITMAP_Cardscene_Xyx::
    INCBIN "autogenerated/assets/cardscene/cards/Xyx.tileset"
    ; $4F00
BITMAP_Cardscene_Vinoc::
    INCBIN "autogenerated/assets/cardscene/cards/Vinoc.tileset"
    ; $5040
BITMAP_Cardscene_Vellup::
    INCBIN "autogenerated/assets/cardscene/cards/Vellup.tileset"
    ; $5180
BITMAP_Cardscene_Weebo::
    INCBIN "autogenerated/assets/cardscene/cards/Weebo.tileset"
    ; $52C0
BITMAP_Cardscene_Vrill_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Vrill.tileset"
    ; $5400
BITMAP_Cardscene_Vulbor::
    INCBIN "autogenerated/assets/cardscene/cards/Vulbor.tileset"
    ; $5540
BITMAP_Cardscene_Orish::
    INCBIN "autogenerated/assets/cardscene/cards/Orish.tileset"
    ; $5680
BITMAP_Cardscene_Orathan_F::
    INCBIN "autogenerated/assets/cardscene/cards/Orathan_F.tileset"
    ; $57C0
BITMAP_Cardscene_Orpus::
    INCBIN "autogenerated/assets/cardscene/cards/Orpus.tileset"
    ; $5900
BITMAP_Cardscene_Ormagon::
    INCBIN "autogenerated/assets/cardscene/cards/Ormagon.tileset"
    ; $5A40
BITMAP_Cardscene_Leaf_Hyren::
    INCBIN "autogenerated/assets/cardscene/cards/Leaf_Hyren.tileset"
    ; $5B80
BITMAP_Cardscene_LavaBalmnt::
    INCBIN "autogenerated/assets/cardscene/cards/LavaBalmnt.tileset"
    ; $5CC0
BITMAP_Cardscene_Mush_Hyren::
    INCBIN "autogenerated/assets/cardscene/cards/Mush_Hyren.tileset"
    ; $5E00
BITMAP_Cardscene_MagmaHyren::
    INCBIN "autogenerated/assets/cardscene/cards/MagmaHyren.tileset"
    ; $5F40
BITMAP_Cardscene_Megathan::
    INCBIN "autogenerated/assets/cardscene/cards/Megathan.tileset"
    ; $6080
BITMAP_Cardscene_Raxis::
    INCBIN "autogenerated/assets/cardscene/cards/Raxis.tileset"
    ; $61C0
BITMAP_Cardscene_Quor::
    INCBIN "autogenerated/assets/cardscene/cards/Quor.tileset"
    ; $6300
BITMAP_Cardscene_ShadwKarak::
    INCBIN "autogenerated/assets/cardscene/cards/ShadwKarak.tileset"
    ; $6440
BITMAP_Cardscene_Rudwot::
    INCBIN "autogenerated/assets/cardscene/cards/Rudwot.tileset"
    ; $6580
BITMAP_Cardscene_Sea_Barl_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Sea_Barl.tileset"
    ; $66C0
BITMAP_Cardscene_Paralit::
    INCBIN "autogenerated/assets/cardscene/cards/Paralit.tileset"
    ; $6800
BITMAP_Cardscene_Pack_Korrit_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Pack_Korrit.tileset"
    ; $6940
BITMAP_Cardscene_Plith::
    INCBIN "autogenerated/assets/cardscene/cards/Plith.tileset"
    ; $6A80
BITMAP_Cardscene_Parmalag::
    INCBIN "autogenerated/assets/cardscene/cards/Parmalag.tileset"
    ; $6BC0
BITMAP_Cardscene_Platheus::
    INCBIN "autogenerated/assets/cardscene/cards/Platheus.tileset"
    ; $6D00
BITMAP_Cardscene_Agovo::
    INCBIN "autogenerated/assets/cardscene/cards/Agovo.tileset"
    ; $6E40
BITMAP_Cardscene_Carillion_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Carillion.tileset"
    ; $6F80
BITMAP_Cardscene_Arbolit::
    INCBIN "autogenerated/assets/cardscene/cards/Arbolit.tileset"
    ; $70C0
BITMAP_Cardscene_Alaban::
    INCBIN "autogenerated/assets/cardscene/cards/Alaban.tileset"
    ; $7200
BITMAP_Cardscene_Fire_Chogo_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Fire_Chogo.tileset"
    ; $7340
BITMAP_Cardscene_Cloud_Narth_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Cloud_Narth.tileset"
    ; $7480
BITMAP_Cardscene_Cave_Hyren::
    INCBIN "autogenerated/assets/cardscene/cards/Cave_Hyren.tileset"
    ; $75C0
BITMAP_Cardscene_Chaos_Jile::
    INCBIN "autogenerated/assets/cardscene/cards/Chaos_Jile.tileset"
    ; $7700
BITMAP_Cardscene_CaveRudwot::
    INCBIN "autogenerated/assets/cardscene/cards/CaveRudwot.tileset"
    ; $7840
BITMAP_Cardscene_Bhatar::
    INCBIN "autogenerated/assets/cardscene/cards/Bhatar.tileset"
    ; $7980
BITMAP_Cardscene_Bisiwog::
    INCBIN "autogenerated/assets/cardscene/cards/Bisiwog.tileset"
    ; $7AC0
BITMAP_Cardscene_Arboll_Stalker_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Arboll_Stalker.tileset"
    ; $7C00
BITMAP_Cardscene_Balamant_Unused::
    INCBIN "autogenerated/assets/cardscene/cards/Balamant.tileset"
    ; $7D40
BITMAP_Cardscene_Ayebaw::
    INCBIN "autogenerated/assets/cardscene/cards/Ayebaw.tileset"
    ; $7E80
BITMAP_Cardscene_Bwill::
    INCBIN "autogenerated/assets/cardscene/cards/Bwill.tileset"
    ; $7FC0