    db 15        ; wTilemap_Width
    dw $0087     ; wTilemap_YMapPad
    db 4         ;
    db 10        ; wTilemap_VStop
    dw $012C     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/westcache_pathway/Underneath_Tunnels_WestCache_Pathway.metatile.tilemap.rle"