    db 30        ; wTilemap_Width
    dw $0384     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/pipes1_pipetostarrycache/Arderial_Geyser_Pipes1_PipeToStarryCache.collision.tilemap.rle"