    db 40        ; wTilemap_Width
    dw $02D0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/detour_pathway/Cald_Caverns_Detour_Pathway.collision.tilemap.rle"