    db 64        ;wTilemap_Width
    dw $0240     ;wTilemap_YMapPad
    db 53        ;
    db 54        ;wTilemap_VStop
    dw $1000     ;Uncompressed file size (excluding header)
    ;The imported file size was actually $1007 because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/core/end/field/Core_End_Field.metatile.tilemap.rle"