    db 25        ; wTilemap_Width
    dw $0271     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/stairshyren/Underneath_Tunnels_StairsHyren.collision.tilemap.rle"