    db 40        ; wTilemap_Width
    dw $05A0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/end/greenery/Core_End_Greenery.collision.tilemap.rle"