    db 20        ;wTilemap_Width
    dw $00B4     ;wTilemap_YMapPad
    db 9         ;
    db 8         ;wTilemap_VStop
    dw $0168     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/southwest_innroom/Naroom_Vash_Southwest_InnRoom.metatile.tilemap.rle"