    db 20        ; wTilemap_Width
    dw $0190     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/mar/libraryroom/Orothe_Mar_LibraryRoom.collision.tilemap.rle"