    db 35        ;wTilemap_Width
    dw $02BC     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/smith/backyard_end/Core_Smith_Backyard_End.collision.tilemap.rle"