    db 45        ;wTilemap_Width
    dw $0627     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/geyser/culdesac/Underneath_Geyser_CulDeSac.collision.tilemap.rle"