    db 20        ;wTilemap_Width
    dw $0578     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/north/west/Arderial_North_West.collision.tilemap.rle"