    db 18        ;wTilemap_Width
    dw $0120     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/glade/pregeyser/Naroom_Glade_Geyser.collision.tilemap.rle"