    db 78        ;wTilemap_Width
    dw $02BE     ;wTilemap_YMapPad
    db 67        ;
    db 42        ;wTilemap_VStop
    dw $0FD8     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/mar/town/Orothe_Mar_Town.metatile.tilemap.rle"