    db 20        ; wTilemap_Width
    dw $00B4     ; wTilemap_YMapPad
    db 9         ;
    db 17        ; wTilemap_VStop
    dw $021C     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/sky/Naroom_Vash_Sky.metatile.tilemap.rle"