    db 36        ; wTilemap_Width
    dw $0360     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/historian/westroom/Arderial_Historian_WestRoom.collision.tilemap.rle"