    db 25        ;wTilemap_Width
    dw $0271     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/grove/pathway/Naroom_Grove_Pathway.collision.tilemap.rle"