    db 20        ; wTilemap_Width
    dw $0320     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/caverns/pathway7/Cald_Caverns_Pathway7.collision.tilemap.rle"