    db 40        ; wTilemap_Width
    dw $0168     ; wTilemap_YMapPad
    db 29        ;
    db 6         ; wTilemap_VStop
    dw $0280     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/middle_firstintersection/Core_Shadowhold_Middle_FirstIntersection.metatile.tilemap.rle"