    db 40        ;wTilemap_Width
    dw $0280     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/middle_firstintersection/Core_Shadowhold_Middle_FirstIntersection.collision.tilemap.rle"