    db 48        ;wTilemap_Width
    dw $0900     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/remix_arderial_keymaze/Arderial_Geyser_Remix_Arderial_KeyMaze.collision.tilemap.rle"