    db 50        ;wTilemap_Width
    dw $09C4     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/ruins/entrance/Orothe_Ruins_Entrance.collision.tilemap.rle"