    db 15        ;wTilemap_Width
    dw $012C     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/bogrom/motashroom/Underneath_Bogrom_MotashRoom.collision.tilemap.rle"