    db 40        ; wTilemap_Width
    dw $0320     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/coral/pathwayhorizontal/Orothe_Coral_PathwayHorizontal.collision.tilemap.rle"