    db 30        ; wTilemap_Width
    dw $010E     ; wTilemap_YMapPad
    db 19        ;
    db 17        ; wTilemap_VStop
    dw $032A     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/marina_jump/Core_Shadowhold_Marina_Jump.metatile.tilemap.rle"