    db 30        ; wTilemap_Width
    dw $032A     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/marina_jump/Core_Shadowhold_Marina_Jump.collision.tilemap.rle"