    db 10        ;wTilemap_Width
    dw $008C     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/middle_northpathway_door/Core_Shadowhold_Middle_NorthPathway_Door.collision.tilemap.rle"