    db 20        ;wTilemap_Width
    dw $0190     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/vents/brokenbridgeend/Cald_Vents_BrokenBridgeEnd.collision.tilemap.rle"