    db 60        ; wTilemap_Width
    dw $04B0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/north/southwest/Arderial_North_Southwest.collision.tilemap.rle"