    db 45        ; wTilemap_Width
    dw $0195     ; wTilemap_YMapPad
    db 34        ;
    db 35        ; wTilemap_VStop
    dw $07E9     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/intersectionfort/Underneath_Tunnels_IntersectionFort.metatile.tilemap.rle"