    db 45        ;wTilemap_Width
    dw $07E9     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/intersectionfort/Underneath_Tunnels_IntersectionFort.collision.tilemap.rle"