    db 16        ;wTilemap_Width
    dw $0100     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/vash/entrance/Naroom_Vash_Entrance.collision.tilemap.rle"