SECTION "Ghost Data $00", ROM0
    ; Ghost data of previous function (3 times)
    ; #1
    db HIGH(Interrupt_VBlankFunc_Idle) ;Truncated Set16_M wVBlank_Func, Interrupt_VBlankFunc_Idle
    ld [wVBlank_Func+1], a
    ret
    db "Defend🡆🡇"

    ; #2
    db "Defend🡆🡇"

    ; #3
    dw wVBlank_Func+1   ;Truncated Set16_M wVBlank_Func, Interrupt_VBlankFunc_Idle
    ret
    db "Defend🡆🡇"

SECTION "Ghost Data $0E", ROMX, BANK[$0E]
     ; Ghost data of the last Script
     db HIGH(SCRIPT_ANIM_Zet_FaceRight) ; Truncated ThisSetAnimSingle(SCRIPT_ANIM_Zet_FaceRight)
     WaitEventText 1
     RestoreActorState

SECTION "Ghost Data $74", ROMX, BANK[$74]
GHOST__COLLMAP_Underneath_Tunnels_IntersectionFort::
    ; The first $F5 bytes are chopped off by the preceding data, so the header is missing + $F2 bytes of the
    ; RLE-compressed data. We directly include the RLE-compressed data
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/intersectionfort/Underneath_Tunnels_IntersectionFort.collision.tilemap.rle",($00F5-$03),$0004

SECTION "Ghost Data $7C", ROMX, BANK[$7C]

    ; $6DF1
GHOST__COLLMAP_Core_Shadowhold_Marina_Pathway::
    ; The first 3 bytes are chopped off by the preceding data, so the header is missing, which is why
    ; we directly just include the RLE-compressed data
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/marina_pathway/Core_Shadowhold_Marina_Pathway.collision.tilemap.rle"

    ; $6E11
GHOST__COLLMAP_Misc_StartScreen_Main::
    INCLUDE "autogenerated/assets/scenes/scenes/misc/startscreen/main/Misc_StartScreen_Main.collision.asm"

    ; $6E33
GHOST__COLLMAP_Orothe_Dock_Eastern_Ferry::
    INCLUDE "autogenerated/assets/scenes/scenes/orothe/dock/eastern_ferry/Orothe_Dock_Eastern_Ferry.collision.asm"

    ; $6E55
GHOST__COLLMAP_Orothe_Dock_Western_Ferry::
    INCLUDE "autogenerated/assets/scenes/scenes/orothe/dock/western_ferry/Orothe_Dock_Western_Ferry.collision.asm"

    ; $6E77
GHOST__BITMAP_Underneath_Geyser_FullMoonBlockPressed::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Underneath_Geyser_FullMoonBlockPressed.tileset"

    ; $6E97
GHOST__BITMAP_Underneath_Geyser_FullMoonBlock::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Underneath_Geyser_FullMoonBlock.tileset"

    ; $6EB7
GHOST__BITMAP_Underneath_Geyser_NewMoonBlock::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Underneath_Geyser_NewMoonBlock.tileset"

    ; $6ED7
GHOST__BITMAP_Orothe_Geyser_EmptyChest::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Orothe_Geyser_EmptyChest.tileset"

    ; $6EF7
GHOST__BITMAP_Orothe_Geyser_FullChest::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Orothe_Geyser_FullChest.tileset"

    ; $6F17
GHOST__BITMAP_Cald_Vents_Block::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Cald_Vents_Block.tileset"

    ; $6F37
GHOST__BITMAP_Cald_Vents_FullChest::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Cald_Vents_FullChest.tileset"

    ; $6F57
GHOST__BITMAP_Cald_Vents_EmptyChest::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Cald_Vents_EmptyChest.tileset"

    ; $6F77
GHOST__BITMAP_Underneath_Geyser_NewMoonButton::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Underneath_Geyser_NewMoonButton.tileset"

    ; $6F97
GHOST__BITMAP_Underneath_Geyser_FullMoonButton::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Underneath_Geyser_FullMoonButton.tileset"

    ; $6FB7
GHOST__BITMAP_Underneath_Geyser_NewMoonButtonPressed::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Underneath_Geyser_NewMoonButtonPressed.tileset"

    ; $6FD7
GHOST__BITMAP_Underneath_Geyser_FullMoonButtonPressed::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Underneath_Geyser_FullMoonButtonPressed.tileset"

    ; $6FF7
GHOST__BITMAP_Naroom_Geyser_FullChest::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Naroom_Geyser_FullChest.tileset"

    ; $7017
GHOST__BITMAP_Naroom_Geyser_EmptyChest::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Naroom_Geyser_EmptyChest.tileset"

    ; $7037
GHOST__BITMAP_Naroom_Vash_PipesRoom_Unknown::
    INCBIN "autogenerated/assets/scenes/graphics/tilesets/Naroom_Vash_PipesRoom_Unknown.tileset"

    ; $7057
GHOST__COLLMAP_Misc_StartScreen_Main_Mask::
    INCLUDE "autogenerated/assets/scenes/scenes/misc/startscreen/main/Misc_StartScreen_Main_Mask.collision.asm"

    ; $7076
GHOST__BITSET_Misc_StartScreen::
    INCLUDE "autogenerated/assets/scenes/graphics/bitmapsets/ghost/Misc_StartScreen.bitmapset.asm"

    ; $7094
GHOST__BITSET_Unknown_1::
    INCLUDE "autogenerated/assets/scenes/graphics/bitmapsets/ghost/Ghost_1.bitmapset.asm"

    ; $70B2
GHOST__BITSET_Overworld_Arderial::
    INCLUDE "autogenerated/assets/scenes/graphics/bitmapsets/ghost/Overworld_Arderial.bitmapset.asm"

    ; $70D0
GHOST__COLLMAP_Core_Shadowhold_Marina_Jump::
    INCLUDE "autogenerated/assets/scenes/scenes/core/shadowhold/marina_jump/Core_Shadowhold_Marina_Jump.collision.asm"

    ; $70EE
GHOST__BITSET_Unknown_2::
    INCLUDE "autogenerated/assets/scenes/graphics/bitmapsets/ghost/Ghost_2.bitmapset.asm"

    ; $710C
GHOST__BITSET_Arderial_Indoors::
    INCLUDE "autogenerated/assets/scenes/graphics/bitmapsets/ghost/Arderial_Indoors.bitmapset.asm"

    ; $712A
GHOST__BITSET_Core_Agram::
    INCLUDE "autogenerated/assets/scenes/graphics/bitmapsets/ghost/Core_Agram.bitmapset.asm"

    ; $7148
GHOST__BITSET_Unknown_3::
    INCLUDE "autogenerated/assets/scenes/graphics/bitmapsets/ghost/Ghost_3.bitmapset.asm"

    ; $7166
GHOST__METAMAP_INDIRECT_UNKNOWN_53::
    INCLUDE "autogenerated/assets/scenes/scenes/INDIRECT_UNKNOWN_53.metatile.asm"

    ; $7183
GHOST__COLLMAP_INDIRECT_UNKNOWN_55::
    INCLUDE "autogenerated/assets/scenes/scenes/INDIRECT_UNKNOWN_55.collision.asm"

    ; $719D
GHOST__COLLMAP_INDIRECT_UNKNOWN_56::
    INCLUDE "autogenerated/assets/scenes/scenes/INDIRECT_UNKNOWN_56.collision.asm"

    ; $71B7
GHOST__COLLMAP_INDIRECT_UNKNOWN_54::
    INCLUDE "autogenerated/assets/scenes/scenes/INDIRECT_UNKNOWN_54.collision.asm"

    ; $71D1
GHOST__COLLMAP_INDIRECT_UNKNOWN_57::
    INCLUDE "autogenerated/assets/scenes/scenes/INDIRECT_UNKNOWN_57.collision.asm"

    ; $71E9
GHOST__COLLMAP_Naroom_Vash_South_Mask::
    INCLUDE "autogenerated/assets/scenes/scenes/naroom/vash/south/Naroom_Vash_South_Mask.collision.asm"

    ; $71F9
GHOST__COLLMAP_Naroom_Vash_Southeast_Mask::
    INCLUDE "autogenerated/assets/scenes/scenes/naroom/vash/southeast/Naroom_Vash_Southeast_Mask.collision.asm"

    ; $7208
GHOST__COLLMAP_Orothe_Dock_Eastern_Empty::
    INCLUDE "autogenerated/assets/scenes/scenes/orothe/dock/eastern_empty/Orothe_Dock_Eastern_Empty.collision.asm"

    ; $7216
GHOST__COLLMAP_Orothe_Dock_Western_Empty::
    INCLUDE "autogenerated/assets/scenes/scenes/orothe/dock/western_empty/Orothe_Dock_Western_Empty.collision.asm"

    ; $7224
GHOST__METAMAP_Orothe_Ocean_Raft::
    INCLUDE "autogenerated/assets/scenes/scenes/orothe/ocean/raft/Orothe_Ocean_Raft.metatile.asm"

    ; $722F
GHOST__COLLMAP_Arderial_Geyser_HorizontalPipe_Unused::
    INCLUDE "autogenerated/assets/scenes/scenes/arderial/geyser/horizontalpipe_unused/Arderial_Geyser_HorizontalPipe_Unused.collision.asm"

    ; $7236
GHOST__COLLMAP_Orothe_Ocean_Raft::
    INCLUDE "autogenerated/assets/scenes/scenes/orothe/ocean/raft/Orothe_Ocean_Raft.collision.asm"

    ; $723D
GHOST__COLLMAP_Orothe_Ocean_Ferry::
    INCLUDE "autogenerated/assets/scenes/scenes/orothe/ocean/ferry/Orothe_Ocean_Ferry.collision.asm"

    ; $7244