    db 48        ;wTilemap_Width
    dw $01E0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/intersectionmain/Orothe_Tunnels_IntersectionMain.collision.tilemap.rle"