    db 12        ;wTilemap_Width
    dw $006C     ;wTilemap_YMapPad
    db 1         ;
    db 54        ;wTilemap_VStop
    dw $0300     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/hyren_entrance/Underneath_Tunnels_Hyren_Entrance.metatile.tilemap.rle"