    db 28        ;wTilemap_Width
    dw $00FC     ;wTilemap_YMapPad
    db 17        ;
    db 18        ;wTilemap_VStop
    dw $0310     ;Uncompressed file size (excluding header)
    ;The imported file size was actually $0317 because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/naroom/geyser/north/Naroom_Geyser_North.metatile.tilemap.rle"