    db 36        ; wTilemap_Width
    dw $0144     ; wTilemap_YMapPad
    db 25        ;
    db 14        ; wTilemap_VStop
    dw $0360     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_twopuzzles/Core_Shadowhold_Deep_TwoPuzzles.metatile.tilemap.rle"