    db 36        ;wTilemap_Width
    dw $0360     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_twopuzzles/Core_Shadowhold_Deep_TwoPuzzles.collision.tilemap.rle"