    db 10        ;wTilemap_Width
    dw $005A     ;wTilemap_YMapPad
    db 255       ;
    db 17        ;wTilemap_VStop
    dw $010E     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/grukroom_basementroom/Underneath_Mushroom_GrukRoom_BasementRoom.metatile.tilemap.rle"