    db 10        ; wTilemap_Width
    dw $010E     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/mushroom/grukroom_basementroom/Underneath_Mushroom_GrukRoom_BasementRoom.collision.tilemap.rle"