    db 40        ; wTilemap_Width
    dw $0320     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/deep_connection/Naroom_Forest_Deep_Connection.collision.tilemap.rle"