    db 40        ; wTilemap_Width
    dw $0168     ; wTilemap_YMapPad
    db 29        ;
    db 10        ; wTilemap_VStop
    dw $0320     ; Uncompressed file size (excluding header)
    ; The imported file size was actually $0327 because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/deep_connection/Naroom_Forest_Deep_Connection.metatile.tilemap.rle"