    db 36        ;wTilemap_Width
    dw $0798     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/pathwaymara/Orothe_Tunnels_PathwayMarA.collision.tilemap.rle"