    db 36        ; wTilemap_Width
    dw $0144     ;wTilemap_YMapPad
    db 25        ;
    db 44        ;wTilemap_VStop
    dw $0798     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/tunnels/pathwaymara/Orothe_Tunnels_PathwayMarA.metatile.tilemap.rle"