    db 60        ; wTilemap_Width
    dw $021C     ; wTilemap_YMapPad
    db 49        ;
    db 40        ; wTilemap_VStop
    dw $0BB8     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/bogrom/normal/Underneath_Bogrom_Normal.metatile.tilemap.rle"