    db 10        ;wTilemap_Width
    dw $0078     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/geyser/southwestpathway/Orothe_Geyser_SouthwestPathway.collision.tilemap.rle"