    db 16        ; wTilemap_Width
    dw $0280     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/labyrinth_puzzlepathway/Core_Shadowhold_Labyrinth_PuzzlePathway.collision.tilemap.rle"