    db 16        ;wTilemap_Width
    dw $0090     ;wTilemap_YMapPad
    db 5         ;
    db 30        ;wTilemap_VStop
    dw $0280     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/labyrinth_puzzlepathway/Core_Shadowhold_Labyrinth_PuzzlePathway.metatile.tilemap.rle"