    db 35        ; wTilemap_Width
    dw $02BC     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/core/shadowhold/deep_southpathway/Core_Shadowhold_Deep_SouthPathway.collision.tilemap.rle"