import os
import re

import sys
sys.path.append('python/')

import magiparser  # noqa: E402
import projutils.hotspot as hotspot  # noqa: E402

# This module converts magiscript .mgi, .hs, .trig files into includeable .asm files

folders = ["magiscript"]

outfolder = "autogenerated"

# All regex is case-sensitive

for folder in folders:
    for header, dirs, files in os.walk(folder):
        if not os.path.exists(os.path.join(outfolder, header)):
            os.makedirs(os.path.join(outfolder, header))
        for file in files:
            relpath = os.path.join(header, file)
            # Include *.mgi
            if(re.match(r"^.*\.mgi$", file)):
                print("MGI       "+relpath)
                magiparser.convert(relpath, os.path.join(outfolder, relpath+".asm"))
            # Include *.hs
            if(re.match(r"^.*\.hs$", file)):
                print("HS        "+relpath)
                hotspot.Hotspot.file_to_hotspot(relpath, os.path.join(outfolder, relpath+".asm"))
            # Include *.trig
            if(re.match(r"^.*\.trig$", file)):
                print("TRIG      "+relpath)
                hotspot.Trigger.file_to_trigger(relpath, os.path.join(outfolder, relpath+".asm"))
