import os
import shutil

# This module deletes the autogenerated magiscript folder

folders = [
    "autogenerated/magiscript",
    ]

for folder in folders:
    if os.path.exists(folder):
        shutil.rmtree(folder)
