import os
import shutil


# This module deletes the autogenerated musyx folder

folders = [
    "autogenerated/musyx",
    # "python/out/" #For tests
    ]

for folder in folders:
    if os.path.exists(folder):
        shutil.rmtree(folder)
