    db 50        ; wTilemap_Width
    dw $01C2     ;wTilemap_YMapPad
    db 39        ;
    db 30        ;wTilemap_VStop
    dw $07D0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/ruins/southwest/Orothe_Ruins_Southwest.metatile.tilemap.rle"