    db 50        ; wTilemap_Width
    dw $07D0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/orothe/ruins/southwest/Orothe_Ruins_Southwest.collision.tilemap.rle"