    ; Use the Macro PortraitAddressBank to refer to an address here
    ; icons must be in banks $00-$0F

    ; Unlike icons0.asm, these icons are not in alphabetical order and so were probably added later

ASSERT BANK(@) < $10
ALIGN 4,0 ;The 4 lowest bits of all portrait addresses must be 0, because the lowest 4 bits are used to store the bank

    ; $4000
ALIGN 4,0
BITMAP_Icon_Ashgar::
    INCBIN "autogenerated/assets/icons/Ashgar.tileset"
    ; $4190
ALIGN 4,0
BITMAP_Icon_Guard1:: ;Naroom
    INCBIN "autogenerated/assets/icons/Guard1.tileset"
    ; $4320
ALIGN 4,0
BITMAP_Icon_Guard2:: ;Naroom
    INCBIN "autogenerated/assets/icons/Guard2.tileset"
    ; $44B0
ALIGN 4,0
BITMAP_Icon_Lasada::
    INCBIN "autogenerated/assets/icons/Lasada.tileset"
    ; $4640
ALIGN 4,0
BITMAP_Icon_Motash::
    INCBIN "autogenerated/assets/icons/Motash.tileset"
    ; $47D0
ALIGN 4,0
BITMAP_Icon_Seer::
    INCBIN "autogenerated/assets/icons/Seer.tileset"
    ; $4960
ALIGN 4,0
BITMAP_Icon_Karyn:: ;TrynCousin01
    INCBIN "autogenerated/assets/icons/Karyn.tileset"
    ; $4AF0
ALIGN 4,0
BITMAP_Icon_Eryn::  ;TrynCousin02
    INCBIN "autogenerated/assets/icons/Eryn.tileset"
    ; $4C80
ALIGN 4,0
BITMAP_Icon_Worveline::
    INCBIN "autogenerated/assets/icons/Worveline.tileset"
    ; $4E10
ALIGN 4,0
BITMAP_Icon_Man::
    INCBIN "autogenerated/assets/icons/Man.tileset"
    ; $4FA0
ALIGN 4,0
BITMAP_Icon_Zet::
    INCBIN "autogenerated/assets/icons/Zet.tileset"
    ; $5130
ALIGN 4,0
BITMAP_Icon_CoreRingsmith::
    INCBIN "autogenerated/assets/icons/CoreRingsmith.tileset"
    ; $52C0
ALIGN 4,0
BITMAP_Icon_DingoCat::
    INCBIN "autogenerated/assets/icons/DingoCat.tileset"
    ; $5450
ALIGN 4,0
BITMAP_Icon_PollyCat2::
    INCBIN "autogenerated/assets/icons/PollyCat.tileset"
    ; $55E0
ALIGN 4,0
BITMAP_Icon_CoolGuy:: ; or generic man
    INCBIN "autogenerated/assets/icons/CoolGuy.tileset"
    ; $5770
ALIGN 4,0
BITMAP_Icon_FriendlyGuy:: ; or generic man
    INCBIN "autogenerated/assets/icons/FriendlyGuy.tileset"
    ; $5900
ALIGN 4,0
BITMAP_Icon_Boatman:: ; or generic man
    INCBIN "autogenerated/assets/icons/Boatman.tileset"
    ; $5A90
ALIGN 4,0
BITMAP_Icon_Oflardt::
    INCBIN "autogenerated/assets/icons/Oflardt.tileset"
    ; $5C20
ALIGN 4,0
BITMAP_Icon_Ora::
    INCBIN "autogenerated/assets/icons/Ora.tileset"
    ; $5DB0
ALIGN 4,0
BITMAP_Icon_ArderialGuard::
    INCBIN "autogenerated/assets/icons/ArderialGuard.tileset"
    ; $5F40
    ; Room for 20 more icons