    db 30        ; wTilemap_Width
    dw $02D0     ; Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/arderial/geyser/pipes1_starrycache/Arderial_Geyser_Pipes1_StarryCache_Mask.collision.tilemap.rle"