    db 60        ;wTilemap_Width
    dw $04B0     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/underneath/tunnels/pathwayfortloopintersections_c/Underneath_Tunnels_PathwayFortLoopIntersections_C.collision.tilemap.rle"