    db 50        ;wTilemap_Width
    dw $0BB8     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/cald/ashyn/northgeyser/Cald_Ashyn_NorthGeyser.collision.tilemap.rle"