name: CI

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      RGBDS_VERSION: 0.7.0

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependancies
        run: |
          pip install -r python/requirements.txt

      - name: Cache RGBDS
        id: cache-rgbds
        uses: actions/cache@v3
        with:
          path: rgbds/**
          key: ${{ runner.os }}-${{ env.RGBDS_VERSION }}-rgbds

      - name: Setup RGBDS
        if: steps.cache-rgbds.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/gbdev/rgbds/releases/download/v$env:RGBDS_VERSION/rgbds-$env:RGBDS_VERSION-win64.zip -OutFile rgbds-$env:RGBDS_VERSION-win64.zip
          Expand-Archive -Path rgbds-$env:RGBDS_VERSION-win64.zip -DestinationPath rgbds/

      - name: Test make file
        shell: pwsh
        run: |
          $env:Path += ";" + (Get-Item .).FullName + "\rgbds"
          make
  
      - name: Verify checksum
        shell: pwsh
        run: |
          $md5 = md5sum game.gbc
          if($md5 -ne "1624f857098ca278b15629914f48352b *game.gbc") {
              Write-Output "ROM Checksum Incorrect!"
              exit 1
          }

      - name: Test make tests
        shell: pwsh
        run: |
          make tests

      - name: Lint with flake8
        shell: pwsh
        run: |
          flake8 python/magiparser python/make python/projutils