name: CI

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache RGBDS
        id: cache-rgbds
        uses: actions/cache@v3
        with:
          path: rgbds/**
          key: ${{ runner.os }}-rgbds

      - name: Setup RGBDS
        if: steps.cache-rgbds.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/gbdev/rgbds/releases/download/v0.5.1/rgbds-0.5.1-win64.zip -OutFile rgbds-0.5.1-win64.zip
          Expand-Archive -Path rgbds-0.5.1-win64.zip -DestinationPath rgbds/

      - name: Cache Python Pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Python Pip Install
        shell: cmd
        run: |
          pip install -r python/requirements.txt

      - name: Test make extras
        shell: pwsh
        run: |
          $env:Path += ";" + (Get-Item .).FullName + "\rgbds"
          make extras

      - name: Test make tests
        shell: pwsh
        run: |
          make tests

      - name: Test make file
        shell: pwsh
        run: |
          $env:Path += ";" + (Get-Item .).FullName + "\rgbds"
          make
  
      - name: Verify checksum
        shell: pwsh
        run: |
          $md5 = md5sum game.gbc
          if($md5 -ne "1624f857098ca278b15629914f48352b *game.gbc") {
              Write-Output "ROM Checksum Incorrect!"
              exit 1
          }