    db 15        ;wTilemap_Width
    dw $00D2     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/misc/startscreen/jukebox/Misc_StartScreen_Jukebox.collision.tilemap.rle"