    db 50        ;wTilemap_Width
    dw $03E8     ;Uncompressed file size (excluding header)
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/deep_pathway/Naroom_Forest_Deep_Pathway.collision.tilemap.rle"