    db 50        ; wTilemap_Width
    dw $01C2     ; wTilemap_YMapPad
    db 39        ;
    db 10        ; wTilemap_VStop
    dw $03E8     ; Uncompressed file size (excluding header)
    ; The imported file size was actually $03EF because 7 extra (unused) $00 bytes (equal to the size of the header) were appended to the end in error
    INCBIN "autogenerated/assets/scenes/scenes/naroom/forest/deep_pathway/Naroom_Forest_Deep_Pathway.metatile.tilemap.rle"